### ISSUE TITLE
wykop.pl

### ISSUE THREAD

**Issue by gwarser** [azet12/PopupBlocker#10]
`pl##.popup` i `pl##.overlay` uniemożliwiają dodanie zdjęcia/filmu do posta.
Przy pisaniu komentarza kliknięcie na ikonkę aparatu powinno wyświetlić warstwę z interfejsem wyboru pliku.

![image](https://cloud.githubusercontent.com/assets/886325/21303779/299a06f8-c5c1-11e6-8043-0b22ac18e414.png)
![image1](https://cloud.githubusercontent.com/assets/886325/21303781/2dce2e7a-c5c1-11e6-9728-49bba16f5e1b.png)

**Comment by azet12** [comment]
reguła `pl##.center` blokuje formularz na `https://www.wykop.pl/zaloguj/`
