### ISSUE TITLE
kupbuty.com

### ISSUE THREAD

**Issue by hawkeye116477** [azet12/PopupBlocker#101]
`kupbuty.com###tidio-chat`

**Comment by blocker999** [comment]
@hawkeye116477 no i popup wyskakuje

**Comment by gomoku** [comment]
> kupbuty

Nie dość, że rozbawili mnie skarpetkami, to teraz jeszcze butami.

**Comment by blocker999** [comment]
@gomoku Poczekaj aż się zima zacznie to będą jeszcz czapki, rękawiczki, szaliki itp.

**Comment by hawkeye116477** [comment]
@blocker999 No i gdzie ten popup? Próbuję go złapać i złapać i nic 😞 .

**Comment by gomoku** [comment]
U mnie też nie ma żadnego popupa.

**Comment by blocker999** [comment]
@hawkeye116477 Popup jest pojawia się po około 5 minutach

![winiary](https://user-images.githubusercontent.com/23176832/30523406-167dad9e-9be1-11e7-83b4-f03b5398b315.png)

winiary.pl##.mask

winiary.pl###newsletter_popup

**Comment by hawkeye116477** [comment]
@blocker999 To Winiary, a na kupbuty gdzie?

**Comment by blocker999** [comment]
@hawkeye116477 

```
kupbuty.com###tws_i_1

kupbuty.com###topLayerBackDrop
```

![kupbuty](https://user-images.githubusercontent.com/23176832/30524858-b8d46e6a-9bfb-11e7-905a-626804c68977.png)

**Comment by gomoku** [comment]
W PopupBlocker są filtry:
```
###newsletter_popup 
###newsletter_popup_overlay
```
Ale one już są na Fanboy’s Annoyance List.

**Comment by hawkeye116477** [comment]
No niby są, tyle, że ja nic o tym nie wiem, że PopupBlocker jest niby uzupełnieniem listy Fanboyów. A Fanboye blokują tez cookies i sociale, a my to traktujemy jako osobne sprawy.

**Comment by gomoku** [comment]
No skoro tak, to ok, właśnie tak się nad tym zastanawiałem pisząc o tych duplikatach i miało to być też swego rodzaju pytanie.

**Comment by blocker999** [comment]
@gomoku  Sprawa dyskusyjna bo ja tylko jako uzupełnienie traktuje sociale ale to inna paczka a PopupBloker jest tylko na Polskie i polsko języczne strony pozatym Fanboy’s Annoyance List. jest mało znaną listą dla zwykłego Kowalskiego no ale może się myle, @hawkeye116477 co robimy?

**Comment by hawkeye116477** [comment]
@blocker999 Zostawiamy, gdyż jeśli powiemy, że Fanboy's Annoyance ma być uzupełnieniem, to może nie każdemu się to spodobać, gdyż ta lista blokuje też sociale i cookies. A może ktoś będzie chciał przeczytać parę komunikatów cookies 😃. A jak nie cookies, to na pewno wielbicieli social media jest pełno, więc nie możemy ich zmusić, by korzystali z listy Fanboya.

**Comment by blocker999** [comment]
@hawkeye116477 100% racja, temat zamykam

**Comment by gomoku** [comment]
Ja też się z wami zgadzam.
