### ISSUE TITLE
rmf.fm

### ISSUE THREAD

**Issue by hawkeye116477** [azet12/PopupBlocker#103]
@blocker999 @gomoku Chłopaki, jest loteria RMF FM, do wygrania jest 500k zł, ktoś wysyła SMS'a 😃 ?
`rmf.fm###loteria-footer`

**Comment by blocker999** [comment]
@hawkeye116477 w swoim radyjku to reklamują, no i czasami w tv otym głośno, no jeszcze niewiem co bym zrobił z taką kasą pewnie oprocentował pod sklepem, więc lepiej nie, natomiast Ty możesz słać ale jak wygrasz to chociasz małą część przeznacz na promocje PopubpBlokera

**Comment by gomoku** [comment]
Może teraz dla odmiany ja was rozbawię:
https://www.youtube.com/watch?v=UZx1QNuUetE
http://www.dzienniklodzki.pl/artykul/738747,wyslal-smsy-za-dwa-tysiace-bo-wygral-bmw-ale,id,t.html
