### ISSUE TITLE
www.kurierlubelski.pl

### ISSUE THREAD

**Issue by gomoku** [azet12/PopupBlocker#107]
Nie wiem , czy to coś po lewej na dole kwalifikuje się do zablokowania, ale wiem, że się uczepiło tego lewego dolnego rogu nawet podczas przewijania strony i mu tam wygodnie, przykładowy artykuł: http://www.kurierlubelski.pl/artykul/970039,dzien-z-zycia-w-areszcie-sledczym-w-lublinie-na-zdjeciach,id,t.html

`www.kurierlubelski.pl###poza-szkieletem`

![](https://s3.dodajfote.pl/2017/09/17/popup1520f.png)

**Comment by hawkeye116477** [comment]
No raczej nie inaczej, kwalifikuje się 😃 .
