### ISSUE TITLE
www.nerwica.com

### ISSUE THREAD

**Issue by gomoku** [azet12/PopupBlocker#108]
Przykładowy link: http://www.nerwica.com/viewtopic.php?f=47&t=34412&start=28

Na tej stronie dosyć grubo, bo aż 3 elementy:
- u góry zwykła reklama `www.nerwica.com##body > .ctr` (to chyba się kwalifikuje do przekazania na POL: polskie filtry do Adblocka i uBlocka listę? ) 
- po środku wsad video player tak jak tu: https://github.com/azet12/PopupBlocker/issues/90
- i na dole też drugi taki wsad

**Comment by hawkeye116477** [comment]
@gomoku No tyle, że te filmiki są static, więc nie wiem czy usuwać czy nie i za bardzo nie chce mi się ich oglądać. Znowu próbują na coś przekabacić czy to coś przydatnego może jednak?
`nerwica.com##div[id^=Player]`

**Comment by gomoku** [comment]
Ja też nie wiem, nie napisałem nigdzie, że koniecznie trzeba je usuwać, ale z drugiej strony chociażby ten po środku automatycznie się odpala i pomimo, że wyciszony, to i tak jest to wkurzające, no i obciąża łącze internetowe, tak wiem, podałeś mi skrypty do blokowania autopleya, ale one mają efekty uboczne https://github.com/azet12/PopupBlocker/issues/90#issuecomment-329891501 i nie mają wygodnej (jedno kliknięcie) opcji zablokowania autopleya na wybranej stronie, tylko trzeba wchodzić i ręcznie wpisywać na każdej stronie, więc przydałoby się, jeśli nie usunąć, to chociaż zastopować te filmiki, tylko że jak pisałeś tak się raczej nie da z poziomu filtra , może jakiś dodatek jest do przeglądarki?

**Comment by hawkeye116477** [comment]
@gomoku Do Chrome coś jest, ale tego autor już chyba nie wspiera, bo Google miało dodać natywną opcję do blokowania autoplaya. 
A do liska jest coś takiego: https://addons.mozilla.org/pl/firefox/addon/disable-autoplay/?src=search, ale ja tego nie testowałem, bo to jakaś nowość zdaje się, wcześniej używałem tego -> https://addons.mozilla.org/pl/firefox/addon/autoplay-toggle/?src=search, ale to już chyba nie działa.

Jesli chodzi o to, że w AutoPlay Disabled for HTML5 Videos video zatrzymuje się przy przełączaniu kart, no to to tak miało być, to jest taka funkcja, ale można to wyłączyć w kodzie skryptu.
`var pauseOnLeaveTab = false;`. A jak przewijam stronę, to mi się nie stopuje, może to śliska małpa nawala , bo na agresywnej małpie jest gites 😃.

**Comment by hawkeye116477** [comment]
@gomoku Do Chrome coś jest, ale tego autor już chyba nie wspiera, bo Google miało dodać natywną opcję do blokowania autoplaya. 
A do liska jest coś takiego: https://addons.mozilla.org/pl/firefox/addon/disable-autoplay/?src=search, ale ja tego nie testowałem, bo to jakaś nowość zdaje się, wcześniej używałem tego -> https://addons.mozilla.org/pl/firefox/addon/autoplay-toggle/?src=search, ale to już chyba nie działa.

Jesli chodzi o to, że w AutoPlay Disabled for HTML5 Videos video zatrzymuje się przy przełączaniu kart, no to to tak miało być, to jest taka funkcja, ale można to wyłączyć w kodzie skryptu.
`var pauseOnLeaveTab = false;`. A jak przewijam filmik, to mi się nie stopuje, może to śliska małpa nawala , bo na agresywnej małpie jest gites 😃.

**Comment by gomoku** [comment]
@hawkeye116477 spoko, to w takim razie te stopowanie przy kartach to faktycznie nie jest problem, bo można wyłączyć, natomiast nadal zostaje reszta problemów, dzięki za linki do dodatków, potestuję.

**Comment by hawkeye116477** [comment]
@gomoku Czyli mówisz, że jesteś miłośnikiem Chrofoxa i ChrOpery, a ja mam Vivaldi jako zastępczą, a jako główną przeglądarkę mam Waterfoksa 😃 .

**Comment by blocker999** [comment]
@gomoku Przejrze tą stronke dogłębnie ale jutro, bo podejrzewam że zajmie mi to sporo czasu.

@hawkeye116477 Spoko od tego tematu masz wolne ale być może jutro Cię wywołam.

**Comment by gomoku** [comment]
@blocker999 OK.
@hawkeye116477 ChrOpera to zgodzę się, ale dlaczego niby FF to Chrofox? Przecież FF jest oryginalną przeglądarką.

**Comment by hawkeye116477** [comment]
@gomoku No może faktycznie jeszcze to nie Chrofox, ale już niedługo Firefoxa zaczną coraz bardziej upodabniać do Chrome, już niedługo nie będzie można nim instalować starych rozszerzeń tj. Classic Theme Restorer, a będą głownie jedynie te z Chrome. A jeszcze mają wywalić pasek wyszukiwania, No i telemetrię rozszerzyć, bo Firefox zbiera za mało danych 😃 , jak nic zaczają żżynać z Chrome. A żeby było jeszcze lepiej, to dodadzą cenzurę, będą mówić gdzie wg nich oszukują, znaczy będą mieszać się w politykę :smile: .

**Comment by blocker999** [comment]
@gomoku Niezabardzo rozumiem co tu usuwać bo to filmiki a nie reklamy więc ja ich nie usune bo ja nie cenzor natomiast autoplaya też niestety niedodam bo mam małą wiedze no chyba że @F4z pomoże .
Na chwile obecną wyłapałem znaczek facebooka w lewym górnym rogu który idzie do socjali.No i ten widzet na dole poprawej też bym usunął, oraz " podpowiadacz " chociaż ja bym go zostawił bo dzięki niemu wiadomo co natępne ( czy warto dalej oglądać ) no ale decyzja należy do Ciebie: 


```
nerwica.com##.skinDefault.npp-container > .top > .social > .facebook

nerwica.com###telemedicoWidget

nerwica.com##.extendedRelated

nerwica.com##.extendedInfo
```

![nerwica](https://user-images.githubusercontent.com/23176832/30540908-5573aa6a-9c79-11e7-9dc5-a19d1a38496c.png)

**Comment by gomoku** [comment]
@hawkeye116477 ten dodatek który mi dałeś: https://addons.mozilla.org/pl/firefox/addon/disable-autoplay/?src=search w ogóle nie działa.

@blocker999 https://github.com/azet12/PopupBlocker/issues/108#issuecomment-330061354

**Comment by hawkeye116477** [comment]
@gomoku No to masz jeszcze 1 opcję, napisać do autorów skryptów, by je poprawili, dopracowali.

**Comment by gomoku** [comment]
Dziwi mnie, że trzeba do nich pisać o tak oczywistej rzeczy, jak wygoda dodawania blokady jednym kliknięciem, jakoś np. autorzy przeglądarek nie mieli problemu, ze zrobieniem tak, że dodaje się stronę do zakładek jednym kliknięciem.

**Comment by blocker999** [comment]
@hawkeye116477 Co robimy ?

**Comment by hawkeye116477** [comment]
@blocker999 No nie wiem, może czekamy na @AdamWr, może ja się mylę i ten autoplay da się jednak zdjąć uBlockiem. A jeśli się naprawdę nie da, to temat zamykamy, no nie będziemy przecież filmików blokować, bo to by już chyba była cenzura 😃 .

**Comment by blocker999** [comment]
@hawkeye116477 O blokowaniu filmików niema mowy ale racja narazie poczekamy

**Comment by hawkeye116477** [comment]
@blocker999 Widget Telemedico dodany, przy okazji usunąłem regułę na programuje.net, bo najwyraźniej pomyliłeś się i zablokowałeś newsy, a ja się dziwiłem, co tam tak pusto 😃 .

**Comment by blocker999** [comment]
Identyczny player ma abczdrowie i pewnie wszelkiej maści stronki od wp więc oprócz tego trzeba by dodać coś ogólnego, co o tym sądzisz?

Przykład:

https://portal.abczdrowie.pl/trudna-sztuka-rozmowy-miedzy-pacjentem-a-lekarzem-w-jaki-sposob-budowac-dobra-komunikacje

**Comment by hawkeye116477** [comment]
@blocker999 Ale co, chodzi ci o podziel się?

**Comment by blocker999** [comment]
@hawkeye116477 Niewiem o jakie podziel się Ci chodzi ale mi chodzi oto co w filmikach na nerwica.com bo na abczdrowie jest to samo więc warto dodać te same reguły tylko z pl, co ?

**Comment by hawkeye116477** [comment]
@blocker999 Podziel się, no ten znaczek Facebookowy. A tobie pewnie chodzi o ten widget medyczny ta?

**Comment by hawkeye116477** [comment]
Ok, dodane -> https://github.com/azet12/PopupBlocker/commit/bc0e757c556e60c57b7aaefb737cb909ee482962
