### ISSUE TITLE
nasygnale.pl

### ISSUE THREAD

**Issue by gomoku** [azet12/PopupBlocker#109]
Do przekazania na listę POL: polskie filtry do Adblocka i uBlocka:

`nasygnale.pl###wpAdvTop` resztki - pusty szary marnujący dużo miejsca konterner u góry oraz
`nasygnale.pl###adv34` reklama po prawej, przykładowy url dla obydwu filtrów: 
http://nasygnale.pl/kat,1025343,name,Kryminal,kategoria.html

`nasygnale.pl###adv05` resztki - pusty marnujący dużo miejsca kontener po środku, przykładowy url: http://nasygnale.pl/gid,17183403,img,17183486,page,5,title,Ptasznik-w-bagazu-studenta,galeria.html

**Comment by hawkeye116477** [comment]
@gomoku Maciej zdjął banana, także możesz już wbijać na https://github.com/MajkiIT/polish-ads-filter.

**Comment by gomoku** [comment]
Spoko, dzięki.

**Comment by hawkeye116477** [comment]
Maciej już to dodał, także zamykam.
