### ISSUE TITLE
wesolakraina.pl

### ISSUE THREAD

**Issue by hawkeye116477** [azet12/PopupBlocker#113]
`wesolakraina.pl##.kontrast_tlo`

**Comment by hawkeye116477** [comment]
@All Chłopaki, takie przyciski do zmiany kontrastu i czcionki, zostawiamy czy blokujemy?

**Comment by hawkeye116477** [comment]
@All @blocker999 Takie przyciski do zmiany kontrastu i powiększania czcionki, zostawiamy czy blokujemy?

**Comment by blocker999** [comment]
@hawkeye116477 ja bym zostawił, bo to ułatwia korzystanie ze strony szczególnie " kontrast " no a powiększanie można uzyskać za pomocą skrótu klawiaturowego no ale niekażdy o tym wie wiec trzeba to zostawić a ewentualnie to usadzić aby nie scrollowało.

**Comment by hawkeye116477** [comment]
@blocker999 Będzie ciężko, bo jak robię static to chowa się tak, że wcale nie widać. No ale może jeszcze coś wykombinuję. Bo na Adama to chyba raczej się nie doczekamy 😃 .

**Comment by hawkeye116477** [comment]
```
wesolakraina.pl##.div_kontrast:style(position: absolute!important;)
wesolakraina.pl##.div_czcionka:style(position: absolute!important;)
```

**Comment by blocker999** [comment]
@hawkeye116477  i elegancko o to chodzi

**Comment by gomoku** [comment]
No to teraz ciepłe skarpetki, buty i mogę na święta wybrać się do wesolej krainy :stuck_out_tongue_winking_eye:
