### ISSUE TITLE
doruchow.pl & krosnice.pl

### ISSUE THREAD

**Issue by hawkeye116477** [azet12/PopupBlocker#114]
Fix na przyciemnienie-> `doruchow.pl###div_loader`
Przyciski z prawej -> `doruchow.pl,krosnice.pl##.menu_prawe_wysuwane_1`

**Comment by hawkeye116477** [comment]
@blocker999 A tutaj chowamy te przyciski z prawej czy zostawiamy?

**Comment by hawkeye116477** [comment]
@All @blocker999 A tutaj chowamy te przyciski z prawej czy usadzamy na miejscu?
`doruchow.pl,krosnice.pl##.div_menu_prawe_wysuwane:style(position: absolute!important;)`

**Comment by blocker999** [comment]
@hawkeye116477  Totalnie niewiem, można by zrobić wyjątek od stron " administracji państwowej " ale te boki usadzić, może warto, niewiem dlatego proszę osoby trzecie o opinie.

**Comment by hawkeye116477** [comment]
Ja to już usadziłem. Także zamykam temat.
