### ISSUE TITLE
twojezaglebie.pl

### ISSUE THREAD

**Issue by gomoku** [azet12/PopupBlocker#116]
Przykładowy link http://twojezaglebie.pl/zycie-pod-cela/

Gdy zaczniemy przewijać stronę w dól, to po chwili wyskoczy po prawej stronie baner i niebieska strzałka, które zostaną z nami aż do samego końca strony, i także gdy zaczniemy przewijać z powrotem w górę do momentu, gdy przewiniemy stronę do tego samego momentu, w którym się pierwszy raz pokazał, wtedy znikną, gdy znowu zaczniemy przewijać w dół, znowu się pojawią i tak w kółko, filtr na baner: 
`twojezaglebie.pl##.td-front-end-display-block.td-more-articles-box`
A co ze strzałką zrobicie, to już w waszej gestii, natomiast jeszcze drugą sprawą jest to, że nawet po usunięciu banera, to też ten panel reklamowy po prawej stronie jeździ za scrollem w górę i w dół, to też zadecydujcie co z tym zrobić.

![](https://s3.dodajfote.pl/2017/09/18/111b35de.png)

**Comment by blocker999** [comment]
@gomoku to " zobacz więcej " do usunięcia, strzałke zostawiamy bo zmieniłem zdanie za namową @hawkeye116477 oraz potym jak zdałem sobie sprawe że to bardziej pomaga niż irytuje szczegulnie na czymś inny niż laptop a ten latający prawy bok usadzimy, @hawkeye116477  zerkniesz?

**Comment by hawkeye116477** [comment]
@blocker999 Tak, zaraz zerknę.

**Comment by gomoku** [comment]
> @blocker999: a ten latający prawy bok usadzimy

 Wyklepie się i sprzeda jako bezwypadkowy :stuck_out_tongue_winking_eye:

**Comment by hawkeye116477** [comment]
`twojezaglebie.pl##.td-ss-main-sidebar:style(position: static!important;)`

**Comment by hawkeye116477** [comment]
Gotowe, ale co ten @blocker999 ostatnio taki bezrobotny, jutro do roboty chłopie,  a nie ja tu tylko ostatnio dodaję 😃 .
