### ISSUE TITLE
telemedi.co

### ISSUE THREAD

**Issue by hawkeye116477** [azet12/PopupBlocker#117]
@blocker999 A tutaj to chyba z 3 rzeczy do wywalenia 😃 . Tylko pytanie jest, sidebar po prawej usadzamy na miejscu czy wywalamy? No i co robimy z konsultacjami i tym, że tylu pacjentów jest online? Bo zmienić tego pozycję to ciężko chyba będzie.

`telemedi.co###ue_widget` -> czat
`telemedi.co##.sidebar-links:style(position: absolute!important;)` -> sidebar

**Comment by blocker999** [comment]
@hawkeye116477 Sidebar usuwamy bo to prywatna firma zresztą niema tu nic przydatnego bo wszysko masz na dole, wiec poco nam te oczojebne duble.

**Comment by hawkeye116477** [comment]
@blocker999 Jeszcze menu górne trzeba usadzić na miejscu -> `telemedi.co##.header__navbar:style(position: absolute!important;)`. 
Ok, czyli sidebar usuwamy, ale co z tymi powiadomieniami, że konsultacje są i paru pacjentów jest online?
