### ISSUE TITLE
wp.pl

### ISSUE THREAD

**Issue by hawkeye116477** [azet12/PopupBlocker#118]
`wp.pl###home-page-button`
![screenshot_20170919_123436](https://user-images.githubusercontent.com/19818572/30588425-f6397a20-9d36-11e7-8a78-1c3110dbc9c4.png)

A to wywalamy? Bo jak dla mnie to zbędne, stronę startową można przecież ustawić w opcjach przeglądarki.

**Comment by gomoku** [comment]
Dokładnie, do wywalenia zdecydowanie.

**Comment by hawkeye116477** [comment]
Ok, dodane,

**Comment by gomoku** [comment]
A co ma dymek do przycisku home?: 
![](https://s3.dodajfote.pl/2017/09/24/wp_home_button39ba7.png)

**Comment by hawkeye116477** [comment]
@gomoku Dymek jest częścią przycisku, naciśniesz przycisk to pojawi się dymek.

**Comment by gomoku** [comment]
Ten dymek to wiem, że on się sam pokazuje czasami, ale że po wciśnięciu przycisku home też się pojawia, to kompletnie o tym zapomniałem, i myślałem, że po wciśnięciu przycisku, strona po prostu doda się do zakładek, tak samo jak po wciśnięciu przycisku "dodaj zakładkę" w przeglądarce stąd myślałem, że dymek jest niezależny od przycisku, i że może zamiast wkleić obrazek przycisku, to omyłkowo wkleiłeś dymka, a tu takie buty, że jeszcze jakieś dymki wyskakują, jeszcze tylko brakuje, żeby po kliknięciu w dymek, wyskoczył kolejny dymek, i tak dalej...

**Comment by gomoku** [comment]
Ale ten twój filtr to jest do poprawki i trzeba do niego dodać `www.` bo z tego co widzę, to tylko na głównej www.wp.pl jest id `home-page-button `, bo na innych stronach z wp.pl zamiast id, jest klasa o nazwie z losowych znaków np. `class="_2RqGnLN" `

**Comment by hawkeye116477** [comment]
@gomoku Ok, poprawione, a do poddomen wp może później coś się wykombinuje.

**Comment by krystian3w** [comment]
Open.fm dodali z tym dziwadłem, dodatkowo ktoś zaktualizował po 3 latach dodatek:

https://addons.mozilla.org/pl/firefox/addon/wp-strona-startowa/versions/
