### ISSUE TITLE
kotkowicz.pl

### ISSUE THREAD

**Issue by gomoku** [azet12/PopupBlocker#119]
Nie wiem czy to się kwalifikuje, ale gdy zaczniemy przewijać stronę w dól, to po chwili górna cześć strony wyjedzie z garażu w postaci paska-banera + strzałka na dole po prawej i zostanie z nami aż do samego końca strony, i także gdy zaczniemy przewijać z powrotem w górę do momentu, gdy przewiniemy stronę do tego samego momentu, w którym się pierwszy raz pokazała, wtedy zniknie, a gdy znowu zaczniemy przewijać w dół, znowu się pojawi i tak w kółko:

Przykładowy link 1): http://kotkowicz.pl/2015/07/16/ten-pierwszy-raz-w-wiezieniu/
Przykładowy link 2): http://avdotia.kotkowicz.pl/

Filtr na ruchomy pasek-baner 1): `kotkowicz.pl###sticky_header`
Filtr na ruchomy pasek-baner 2a): `avdotia.kotkowicz.pl###header`

W przypadku avdotia.kotkowicz.pl jest też dodatkowo u góry statyczny pasek social:
Filtr na statyczny pasek-baner 2b): `avdotia.kotkowicz.pl##.logo_in_nav_header.main-header`
Jako, że 2a) zawiera się w 2b), to 2b) usuwa także jednocześnie 2a) (dwie pieczenie na jednym rożnie)
Więc żeby wywalić wszystko to: 1 + 2b

Ale jako, że jedyną inną zarejestrowaną poddomeną kotkowicz.pl jest strona główna hostingu http://hosting.kotkowicz.pl na której nic nie trzeba blokować, więc może ostatecznie być taka alternatywa filtrów:
Filtr na obydwa ruchome paski-banery: 3)`kotkowicz.pl##DIV[id$="header"]` + 2b, ale raczej lepiej 1 + 2b

Zrzut ekranu z kotkowicz.pl biały pasek-baner wyjechał z garażu:
![](https://s3.dodajfote.pl/2017/09/19/ssaf426.png)

Zrzut ekranu z avdotia.kotkowicz.pl: czarny pasek-baner wyjechał z garażu:
![](https://s3.dodajfote.pl/2017/09/19/avdotia231f8b.png)

Zrzut ekranu z avdotia.kotkowicz.pl: biały pasek-baner social + czarny pasek-baner zaparkowany jeszcze nie wyjechał z garażu:
![](https://s3.dodajfote.pl/2017/09/19/avdotia1da9f6.png)

**Comment by hawkeye116477** [comment]
@gomoku Ta, ruchome headery się kwalifikują jak najbardziej, zaraz zobaczę co da się zrobić. A na avdotia to raczej będzie trzeba wykombinować coś innego, bo nie możemy wywalić nagłówka, trzeba go usadzić na miejscu 😃 .
@blocker999 A co do strzałki, to już sam nie wiem, bo teraz mi się wydaje, że jednak bywa wkurzająca.

**Comment by hawkeye116477** [comment]
@gomoku Tak może być?
```
avdotia.kotkowicz.pl###header:style(position: static!important;)
kotkowicz.pl###sticky_header
kotkowicz.pl##.vce-sticky:style(position: static!important;)
```

**Comment by blocker999** [comment]
@hawkeye116477 Niewiem co z tą strzałką, ale może idzie ją na stałe usadzić, na dole po prawej?

**Comment by gomoku** [comment]
Ten pierwszy nie, bo jeśli przewinie się stronę trochę w dół (tak żeby te headery zniknęły), a potem z powrotem do góry to ten biały header rozjeżdża się brzydko, a szczegółowo i humorystycznie rzecz ujmując zdąży wyjechać z garażu zanim zostanie usadzony i zostaje usadzony dopiero jak już jest przed garażem:

![](https://s3.dodajfote.pl/2017/09/19/rozjazde28fa.png)

A ten ostatni to do czego jest? Bo nigdzie nie znalazłem elementu vce-sticky.

O strzałkę nie pytaj mnie tylko @blocker999 bo mi te strzałki to bez różnicy, on chciał zostawiać strzałki, ty chcesz usunąć, a ja nie mam zdania (wstrzymuję się od głosu), więc macie impas 1:1.

**Comment by hawkeye116477** [comment]
@gomoku 
A fakt, z tym dodatkowo powinno być ok: `avdotia.kotkowicz.pl###catcher`
Ten ostatni jest do tego czegoś po prawej.

@blocker999 A może być strzałka po lewej? Bo przestawia mi się na lewą stronę, a nie wiem jak zrobić by wskoczyła na prawą.
`pl###back-top:style(position: static!important;)`
Tylko co wtedy z tymi biedakami co korzystają z Adblocka, oni będą te strzałki mieli latające, bo Adblock nie ma style 😞 . Ja chyba jednak jestem za ponownym wywaleniem, gdyż można samemu normalnie myszką przescrollować, no może jeszcze na smartfonie czy tablecie, by to się przydało, ale na fonie to może trochę zasłaniać pole widzenia, a na tablecie jak i fonie to w sumie ręką scrollować można.

**Comment by gomoku** [comment]
@hawkeye116477 no już wiem, zauważyłem i edytowałem zanim odpisałeś

@hawkeye116477gdyż można samemu normalnie myszką przescrollować,

Albo klawisz Home.

**Comment by blocker999** [comment]
@hawkeye116477 Zdecyduj sam co z tą strzałką bo jeszcze sam mnie przekonywałeś aż zmieniłem zdanie i pousuwałem reguły z githuba a teraz, zmieniasz zdanie i co zpowrotem je dodać, 
@gomoku to obojętne mi też, możesz to usunąć, może zostać albo przesuń na lewo, jak chcesz, wszystkie opcje dozwolone.

**Comment by hawkeye116477** [comment]
@gomoku Racja. Można też środkowym przyciskiem myszy nacisnąć na górę scrollbara. 
Ok, skoro są dwa, to w takim razie podmienię regułę. Dzięki.

**Comment by hawkeye116477** [comment]
@gomoku Racja. Można też środkowym przyciskiem myszy nacisnąć na górę scrollbara. 
Ok, skoro są dwa, to w takim razie podmienię regułę. Dzięki.
@blocker999 No jednak trochę posurfowałem i zmieniłem zdanie. Także zaraz przywrócę reguły.

**Comment by gomoku** [comment]
`@blocker999: @gomoku to obojętne mi też, możesz to usunąć, może zostać albo przesuń na lewo, jak chcesz, wszystkie opcje dozwolone.`

Mi też to obojętne, mogą zostać, ja tylko tak spytałem, żebyście w razie czego ich nie przeoczyli jeśli w waszych zasadach byłoby ich usuwanie czy coś.

> @hawkeye116477 Można też środkowym przyciskiem myszy nacisnąć na górę scrollbara.

Mógłbyś rozjaśnić?

**Comment by blocker999** [comment]
@gomoku Ja osobiście korzystam z klawiatury Home - góra, End - dół a reszta mychą, no ale niewiem jak uwas

@hawkeye116477 Cieszę się bardzo że ustaliliśmy wspólną wersje

**Comment by gomoku** [comment]
@blocker999 ja też korzystam z Home/End, o którym to klawiszu Home już wcześniej wspomniałem: https://github.com/azet12/PopupBlocker/issues/119#issuecomment-330543315, to @hawkeye116477 wspominał coś o scrollu.

**Comment by hawkeye116477** [comment]
> @hawkeye116477 Cieszę się bardzo że ustaliliśmy wspólną wersje

@blocker999 To znaczy nie będziesz miał mi za złe jak jednak ponownie usunę?

> Mógłbyś rozjaśnić? Bo nie zrozumiałem do końca, a dokładniej tego: "na górę scrollbara" tzn chyba rozumiem, ale jaki to ma dać efekt, chodzi o to że wyskoczy taka ikonka i wtedy scrollujemy stronę myszką? (co de facto jest faktycznie szybszce od scrollowania kółkiem):

@gomoku Normalnie można najechać na górę scrollbara, a potem kliknąć środkowym.

**Comment by gomoku** [comment]
> @hawkeye116477: @gomoku Normalnie można najechać na górę scrollbara, a potem kliknąć środkowym.

No można, to już wiedziałem wcześniej, bo sam to robiłem, o czym wspomniałem, ale chodzi o to jaki to efekt daje, czemu ma to służyć.

**Comment by hawkeye116477** [comment]
@gomoku Jak to jaki, taki sam jak home, co kto woli.

**Comment by gomoku** [comment]
No właśnie nie, a przynajmniej u mnie, i właśnie o tym piszę, u mnie powoduje to efekt jak na obrazu i nic więcej.

**Comment by hawkeye116477** [comment]
@gomoku Aha, u mnie na Linuxie z myszką Logitech M210 jest taki sam efekt jak z home.

**Comment by gomoku** [comment]
U mnie a4tech g7-540 bez zainstalowanego firmowego oprogramowania (wbudowane sterowniki Windowsowe na domyślnych ustawieniach).

**Comment by hawkeye116477** [comment]
@gomoku Ta, Waterfox 55.0.2, ale i na najnowszym Vivaldi 1.11.917.43 jest tak samo. Sterowniki też domyślne. A tak w ogóle to do mojej myszki nie ma żadnych innych sterowników, jest tylko Logitech Connection Utility 😄 .

**Comment by hawkeye116477** [comment]
@gomoku Ta, Waterfox 55.0.2, ale i na najnowszym Vivaldi 1.11.917.43 jest tak samo. Sterowniki też domyślne. A tak w ogóle to do mojej myszki nie ma żadnych innych sterowników, jest tylko Logitech Connection Utility 😄 . Przeloguję się i zobaczę jeszcze jak na Windzie 7.

**Comment by blocker999** [comment]
@hawkeye116477 Niemam tych strzałek Tobie zazłe, przecież moje reguły wróciły, więc temat ze strzałkami uważam za zamknięty.

**Comment by gomoku** [comment]
Nie wiem dlaczego, ale skojarzyło mi się i odczytałem to w myślach tak: "Niemam tych skarpetek Tobie zazłe". Ja po prostu zaraz padnę ze śmiechu.
