### ISSUE TITLE
www.zpozdrowieniem.pl

### ISSUE THREAD

**Issue by gomoku** [azet12/PopupBlocker#120]
To samo co w https://github.com/azet12/PopupBlocker/issues/119 w kotkowicz.pl:
`www.zpozdrowieniem.pl##.header_fixed.header_middle` lub bez `www.`

![](https://s3.dodajfote.pl/2017/09/19/pozdro023dd.png)

Oraz dodatkowo na https://www.zpozdrowieniem.pl/wypiska baner nagabujący do zapłaty po prawej stronie przy przewijaniu strony w dół/górę jeździ za nami razem ze scrollem, filtr usadzający:
`zpozdrowieniem.pl###scroller:style(position: static!important;)`

![](https://s3.dodajfote.pl/2017/09/19/baner6c5ad.png)

**Comment by hawkeye116477** [comment]
@gomoku Co ty tak polubiłeś te strony więzienne 😃 ?

**Comment by gomoku** [comment]
Bo mnie ten film rozbawił https://www.youtube.com/watch?v=v9G5B3gqVqo , prawie popłakałem się do łez ze śmiechu, niektórzy go minusują, ale to tacy co tylko by bajki i Transformesów i Godzillę oglądali, i jeśli nie ma w jakimś filmie wybuchów i robotów to hejtują, tymczasem ten film jest realistyczny do bólu, bo w areszcie każdy dzień jest taki sam.

**Comment by gomoku** [comment]
@hawkeye116477 

> DODANE 17:52: Jeszcze coś do usadzenia znalazłem na tej stronie patrz pierwszy komentarz - edytowałem go.

**Comment by hawkeye116477** [comment]
@gomoku Gotowe. Ale wtopa, wcześniej nie zmieniłem daty w last modified 😃 .
