### ISSUE TITLE
www.ceneo.pl

### ISSUE THREAD

**Issue by gomoku** [azet12/PopupBlocker#121]
Nie wiem czy to kwalifikuje akurat na tej stronie do usadzenia, bo teoretycznie tak, tak czy inaczej, to samo co w https://github.com/azet12/PopupBlocker/issues/119 i https://github.com/azet12/PopupBlocker/issues/120, tzn tylko u góry ten pasek/baner/header wyjeżdza z garażu...itd, 
Przykładowy link: https://www.ceneo.pl/6738005
Filtr usadzający: `www.ceneo.pl##.header-container:style(position: static!important;)` z dwoma zastrzeżeniami:
- musi być te `www.` bo jest wiele poddomen typu *.ceneo.pl na których tego paska nie ma i w ogóle inaczej te strony wyglądają
- filtr ma pewien defekt, po wejściu na stronę strona przewija się automatycznie parę cm w dół, co generalnie nie jest pożądane, a w praktyce może okazać się denerwujące, no ale bawiłem się i nie udało mi się znaleźć lepszego filtra/czegoś wykombinować może ktoś będzie umiał poprawić lub dodać drugi filter naprawczy.

Tak czy inaczej, kilka zrzutów ekranu, najpierw z headerem, który wyjechał z garażu (czyli bez stosowania żadnych filtrów):

![](https://s3.dodajfote.pl/2017/09/19/ceneo50c90.png)

Teraz po zastosowaniu filtra - widoczny ten defekt, że strona po wejściu przewija się sama kilka cm w dół:

![](https://s3.dodajfote.pl/2017/09/19/ceneo2b527e.png)

A teraz tak jak powinna wyglądać z filterm i bez defektu, czyli ma być nieprzewinięta w dół:

![](https://s3.dodajfote.pl/2017/09/19/ceneo33ae9e.png)

**Comment by hawkeye116477** [comment]
@gomoku U mnie tego defektu nie ma zarówno na Waterfoksie jak i Vivaldim.

**Comment by gomoku** [comment]
@hawkeye116477 teraz sprawdziłem i też przez chwilę nie było tego defektu, tzn kilka razy odświeżyłem stronę i wszystko ok, ale po chwili zaczął się pojawiać przy następnych odświeżaniach strony, a dokładniej zrobiłem coś takiego, co wywołało defekt:
- po załadowaniu strony przewinąłem ją kilka cm w dól i odświeżyłem i defekt zaczął się objawiać, i nawet gdy przewinąłem z powrotem do góry i znowu odświeżyłem to d efekt dalej trwa
- i jak coś to testuj na tym linku: https://www.ceneo.pl/6738005, bo zapomniałem go w pierwszym poście wstawić (już wstawiłem). 
- i jak coś to ten defekt występuje na FF i Operze
- i w ogóle to na Operze nawet bez filtra ten defekt występuje tzn baner sam wyjeżdża od razu nawet nie trzeba przewijać strony w dół i wtedy właśnie gdy wyjeżdża to ten jego wyjazd powoduje , że strona się przewija kilka cm w dół
- po dodaniu filtra, baner teoretycznie jest usadzony, ale coś tam jeszcze chyba niewidzialnego wyjeżdża ,tylko dziwne bo nie zawsze

**Comment by hawkeye116477** [comment]
@gomoku Ten defekt to nawet jest i bez tej reguły i bez uBlocka. Także to trzeba chyba zgłosić do admina tej strony.

**Comment by blocker999** [comment]
@gomoku Niestety aż tak nie integrujemy w strone to robota dla admina, natomiast wiem że w tym wypadku będzie to trudne a raczej i tak zostanie tak jak jest, dlatego proponuje napisać do gościa który zajmuje się całkowicie takimi stronkami: alleblock.pl

**Comment by gomoku** [comment]
@blocker999 dzięki, zgłoszę tam, a tak w ogóle to link coś źle dałeś, nie chodzi mi o nazwę, tylko o odnośnik bo gdy się kliknie to idzie pod https://github.com/azet12/PopupBlocker/issues/url i sypie 404 error.

**Comment by hawkeye116477** [comment]
@gomoku Ja ten defekt to widzę chyba na wszystkich stronach. Nawet na GitHubie, tak że to chyba jest normalka i nic z tym nie zrobimy.
