### ISSUE TITLE
www.elblag.net

### ISSUE THREAD

**Issue by gomoku** [azet12/PopupBlocker#122]
Nie wiem czy tego typu widżet się kwalifikuje, ale gdy zaczniemy przewijać stronę do dołu, to tak po przewinięciu do 3/4 wyskoczy po prawej na dole w rogu baner typu "następny artykuł", który z nami zostanie do momentu przewinięcia strony z powrotem w górę do miejsca gdzie się wcześniej ukazał, i tak w kółko, przykładowy link: 
http://www.elblag.net/artykuly/maria-kosecka-wielokrotnie-postulowalam-prowadzeni,32296.htm,
 filtr usadzający: `www.elblag.net##.nextarticle.allpadding` (musi być `www.`, bo jest wiele poddomen *.elblag.net które są inaczej wyglądającymi stronami, nie zawierającymi tego elementu):

![](https://s3.dodajfote.pl/2017/09/19/b1c47b9.png)

**Comment by hawkeye116477** [comment]
Tutaj to w ogóle widzę, że są reklamy. Zaraz zgłoszę do Macieja.
