### ISSUE TITLE
www.cozadzien.pl

### ISSUE THREAD

**Issue by gomoku** [azet12/PopupBlocker#124]
Po prawej są 2 przyciski `###error_widget` i `###recom_widget` które przy przewijaniu strony w dół/górę jeżdżą za scrollem: http://www.cozadzien.pl/blog

Tak naprawdę są tam 3 przyciski, bo jest tam jeszcze jeden przycisk, ale jego nie widać bo jest już blokowany przez PopuBlocker  jako `pl###sugester_widget`.

![](https://s3.dodajfote.pl/2017/09/20/3b32ce.png)

**Comment by hawkeye116477** [comment]
`www.cozadzien.pl###error_widget, #recom_widget`
