### ISSUE TITLE
se.pl

### ISSUE THREAD

**Issue by gomoku** [azet12/PopupBlocker#126]
Coś podobnego do https://github.com/azet12/PopupBlocker/issues/124 , przy przewijaniu strony w dół/górę wyskakują po prawej 3 przyciski typu social i jeżdżą ze scrollem, i tu ciekawostka, gdy najedziemy kursorem na taki przycisk to rozwija się baner:
http://www.se.pl/
http://superbiz.se.pl/
http://superseriale.se.pl/
http://superauto24.se.pl/
http://usa.se.pl/
http://sport.se.pl/
http://superseriale.se.pl/

A np. na tych takich przycisków nie ma:
http://m.se.pl/
http://podroze.se.pl/
http://glamki.se.pl/
http://tv.se.pl/
http://zagle.se.pl/
http://mowimyjak.se.pl/
http://beszamel.se.pl/
http://m.superseriale.se.pl/

Jak widać se.pl to dosyć popularna domena, więc raczej trzeba filtr dodać ogólnie do se.pl żeby nie musieć wypisywać wszystkich domen, chociaż z drugiej strony z poddomenami jest bezpieczniej, bo się niczego nie uwali, ale raczej zbyt dużo tych stron se.pl, a jest ich więcej bo nie wszystkie wypisałem, bo jeśli ma być ogólny filtr do se.pl to po co mam wszystkie wyszukiwać, no ale jak coś to dajcie znać to poszukam więcej jeśli jednak będzie filtr na poddomeny.

![](https://s3.dodajfote.pl/2017/09/20/587c61.png)
![](https://s3.dodajfote.pl/2017/09/20/6de80b.png)

**Comment by hawkeye116477** [comment]
@gomoku Damy ogólnie na se.pl -> `se.pl###social-widget`, nie będziemy się z nimi cackać 😃 .
