### ISSUE TITLE
[Grupa Gremi Media] rp.pl

### ISSUE THREAD

**Issue by gomoku** [azet12/PopupBlocker#127]
1) Przy przewijaniu strony w dół/górę wyskakuje po prawej na dole baner typu "następny artykuł" (zrzut ekranu 1):
http://www.rp.pl/Warszawa/170819148-Warszawa-Kolejne-samobojstwo-w-areszcie-sledczym.html#ap-1
`www.rp.pl##.show.popup-next.art-box`

2) Przy przewijaniu strony w dół wyskakuje po środku jebutny baner typu popup (zrzut ekranu 2) chociaż nie zawsze, chyba losowo, a po zamknięciu banera i przewinięciu dalej na sam dół wyskakuje dolny header-pasek na dole (zrzut ekranu 3):
http://www.rp.pl/
(tego banera nie zdążyłem namierzyć, bo gdy kliknąłęm na niego i wybrałem zablokuj element to skubany zdążył zniknąć)
`www.rp.pl##tqwidget` (pasek na dole)

3) Resztki po ciasteczkach puste kontenery u góry zajmujące sporo miejsca do wywalenia są (zrzut ekranu 4 i 5) ale to chyba trzeba je zgłosić na POL: polskie filtry do Adblocka i uBlocka:
http://archiwum.rp.pl/
http://info.rp.pl/temat/941719.html
`archiwum.rp.pl,info.rp.pl##html > body:style(margin-top: 0px!important;)`

4) U góry biały i szary header jeździ ze scrollem (zrzuty ekranu tu: https://github.com/azet12/PopupBlocker/issues/127#issuecomment-331233842):
https://prenumerata.rp.pl/plusminus 
https://prenumerata.rp.pl/
`prenumerata.rp.pl###header:style(position: static!important;)`

5) Dwa jebutne popupy (zrzut ekranu 6), po przewinięciu strony max w dół wyskakuje na dole po prawej jeden, a drugi mi wyskoczył nie wiem z jakiego powodu, ale wyskoczył po paru/nastu sekundach, próbowałem go wywołać drugi raz (wyczyściłem ciasteczka) ale już nie chcę się pokazać, być może jest przypisany do IP:
https://www.kariera.pl/
`www.kariera.pl###drift-widget-container`
`www.kariera.pl##.listbuilder-popup.me.o.m.u.s`

6) Znalezione przez @blocker999 tu: https://github.com/azet12/PopupBlocker/issues/127#issuecomment-331641922 (zrzut ekranu 7):
! po prawej u góry pasek z przyciskami do usadzenia, który jeździ za scrollem, zrobiłem filtr:
`bloombergbusinessweek.pl###floatingFrameSales:style(top: 0px!important;)`
! puste miejsce po ciasteczkach, więc trzeba body przesunąć do góry (ten filtr powinien iść do https://github.com/MajkiIT/polish-ads-filter/issues), zrobiłem filtr :
`bloombergbusinessweek.pl##body:style(margin-top: 0px!important;)`

Tu nic do zablokowania nie ma bo albo nic nie ma, albo inne listy zbierają:
http://porownywarka.rp.pl/ >> http://www.ebroker.pl/
https://konferencje.rp.pl/
http://czytaj.rp.pl/
https://kancelarierp.pl/
http://ewydanie.rp.pl/ >> https://prenumerata.rp.pl/prenumerata.html?tab=1

Zrzut ekranu 1:
![](https://s3.dodajfote.pl/2017/09/20/700442.png)

Zrzut ekranu 2:
![](https://s3.dodajfote.pl/2017/09/20/85fb27.png)

Zrzut ekranu 3:
![](https://s3.dodajfote.pl/2017/09/20/920c42.png)

Zrzut ekranu 4:
![](https://s3.dodajfote.pl/2017/09/20/10936bf.png)

Zrzut ekranu 5:
![](https://s3.dodajfote.pl/2017/09/20/1161546.png)

Zrzut ekranu 6
![](https://s3.dodajfote.pl/2017/09/23/karieraee157.png)

Zrzut ekranu 7:
![](https://s3.dodajfote.pl/2017/09/23/bloom400a7.png)

**Comment by hawkeye116477** [comment]
prenumerata.rp.pl###header:style(position: static!important;)
prenumerata.rp.pl###contact-form:style(position: absolute!important;)
@gomoku Dość problematyczna strona, nadal coś tam skacze. Także ja to zostawiam, nie chce mi się z nimi bawić.

**Comment by gomoku** [comment]
Problematyczna, ale jakoś dałem radę:
https://prenumerata.rp.pl/ Górny header szary +
https://prenumerata.rp.pl/plusminus ten sam Górny header , tyle, że biały:
`prenumerata.rp.pl###header:style(position: absolute!important;)`

![](https://s3.dodajfote.pl/2017/09/21/szaryc9ac1.png)
![](https://s3.dodajfote.pl/2017/09/21/bialyd0311.png)

Ten to dopiero był problematyczny:
https://www.rp.pl/ Górny Header czarny:
![](https://s3.dodajfote.pl/2017/09/21/czarny75d39.png)

```
www.rp.pl###header-apla:style(position: absolute!important;)
www.rp.pl###main-header:style(position: absolute!important;)
www.rp.pl###header-search:style(position: absolute!important;)
www.rp.pl##.search.modal-fix-search:style(position: absolute!important;)
www.rp.pl##.show.modal-fix-toolbar-showmenu.toolbar-showmenu.toolbar-icon:style(position: absolute!important;)
```
Może jakoś połączysz te 5 filtrów w mniejszą ilość.

**Comment by gomoku** [comment]
Ale jaka tu pomoc potrzebna?, te moje filtry co wyżej w komentarzu, to u mnie śmigają bezproblemowo zarówno na FF jak i Operze, coś u ciebie nie tak?

**Comment by hawkeye116477** [comment]
@gomoku Na tej stronie plusminus tam 1 reguła nie wystarczy.

**Comment by gomoku** [comment]
Wszystko zauważyłem i nic mi nie umknęło, sprawdziłem jeszcze raz na FF i Operze na takich samych jak ustawieniach i listach jak tu: https://github.com/azet12/PopupBlocker/issues/135 i nie ma żadnych problemów. Na jakiej przeglądarce i listach są u ciebie te problemy? Może tu leży pies pogrzebany, przetestuj na tych samych co ja.

**Comment by hawkeye116477** [comment]
@gomoku Sorry, ale jak to ty mówisz, tutaj -> https://prenumerata.rp.pl/plusminus formularz Nie wiesz jaki pakiet wybrać? Zostaw dane. Oddzwonimy. wyjeżdża z garażu, nie wiem jakim cudem ci to umknęło. Dlatego też dałem 2 regułę.
Wszystko sprawdzałem i na Waterfoksie i Vivaldim.
Niech @blocker999 jeszcze sprawdzi, bo ja już nie mam do tego cierpliwości.

**Comment by hawkeye116477** [comment]
@gomoku Sorry, ale jak to ty mówisz, tutaj -> https://prenumerata.rp.pl/plusminus formularz Nie wiesz jaki pakiet wybrać? Zostaw dane. Oddzwonimy. wyjeżdża z garażu, nie wiem jakim cudem ci to umknęło. Dlatego też dałem 2 regułę. To już dałem do update, więc może dlatego tego teraz widzisz, że jest ok.
Wszystko sprawdzałem i na Waterfoksie i Vivaldim.
Niech @blocker999 jeszcze sprawdzi, bo ja już nie mam do tego cierpliwości.

**Comment by blocker999** [comment]
Co do " prenumeraty " to jest ok, sprawdzałem na Waterfoxie,, Vivaldi i Slimjet.
Natomiast główna to rss do usadzenia, najlepiej nadole, i ten napis bym usunoł o wersji beta, co do hedearu to jest ok ale tylko na slimjet i viva;dpm a na waterfoxie po staremu mowa tu o regułach podanych przez @hawkeye116477 
No i beta tu jest kosmos bo znowu ten upierdliwy player a dodatkowo scrollująca ankieta do usadzenia, no ale jutro to dokładnie sprawdze.

**Comment by gomoku** [comment]
**1.) :white_check_mark: ████████████████████████████████████████████████████████████**
> @blocker999: Co do " prenumeraty " to jest ok, sprawdzałem na Waterfoxie,, Vivaldi i Slimjet.

A ja wcześniej sprawdzałem na FF, Operze, a przed chwilą dodatkowo na Vivaldi, i również jest ok.

Oczywiście piszemy tu o tylko o jednej regule - mojej: 
`prenumerata.rp.pl###header:style(position: absolute!important;)`
Podczas testowania wyłączyłem drugą regułę @hawkeye116477'a, którą dodał do PopupBLOCKER Plusa:
`prenumerata.rp.pl#@##contact-form:style(position: absolute!important;)` 

Tak to wygląda na mojej regule (przy przewijaniu nic nie wyjeżdża i nic się nie dzieje):
https://s3.dodajfote.pl/2017/09/23/1regula43775.png

Po włączeniu dodatkowo reguły @hawkeye116477'a jak widać zwalone, bo Prenumerata podstawowa znajduje się pod Wyślij: https://s3.dodajfote.pl/2017/09/23/2regulyc2e03.png

**2.) :white_check_mark: ████████████████████████████████████████████████████████████**

> @hawkeye116477: No i na rp.pl jak przescrollujesz w dół, to nagle ni stąd ni z owąd, margines wskakuje na górę.

Przetestowałem na swoich regułach wcześniej na FF i Operze, a teraz dodatkowo na Vivaldi i również jest ok, żadnego marginesu nie ma i podczas przewijania też nic się nie dzieje: 
https://s3.dodajfote.pl/2017/09/23/rpf71f5.png

@hawkeye116477 chyba kolejne problemy po twojej stronie...

**Comment by hawkeye116477** [comment]
> Po włączeniu dodatkowo reguły @hawkeye116477'a jak widać zwalone, bo Prenumerata podstawowa znajduje się pod Wyślij: https://s3.dodajfote.pl/2017/09/23/2regulyc2e03.png więc ta reguła do wyrzucenia.

@gomoku Sorry nie możemy tego wywalić, bo to się przesuwa. A ty nie pokazałeś jak przewinąłeś.

> Po włączeniu dodatkowo reguły @hawkeye116477'a jak widać zwalone, bo Prenumerata podstawowa znajduje się pod Wyślij: https://s3.dodajfote.pl/2017/09/23/2regulyc2e03.png więc ta reguła do wyrzucenia.

Sorry, ja tego tak nie mam, to problem po twojej stronie.

**Comment by gomoku** [comment]
Zależy co jest problemem, to że coś jeździ (u ciebie), czy to że coś nie jeździ (u mnie i blockera).

> @hawkeye116477: na Windzie

Tzn. na FF i Operze też? Bo jeśli nie testowałeś na nich jeszcze, to czekam.

**Comment by hawkeye116477** [comment]
@gomoku  Na Chroperze na rp.pl tak samo, margines się pojawia, nawet nie musiałem przewijać strony, tylko poczekać aż się załaduje i od razu margines. Tak jak mówię, strona nie jest responsywna i stąd te problemy. A na stronie plus minus z moimi 2 regułami jest ok. Jakby co to mam monitor 19 cali, a wy mniejsze urządzenia i dlatego pewnie u was tego problemu nie ma.
Także nie wiem czy sens jest poprawiać te strony, dodamy reguły i zaraz ktoś inny odezwie się że ma problem na MacBooku czy czymś tam innym.

**Comment by gomoku** [comment]
Sprawdziłem na laptopie WinXP SP3 + FF 52.3.0 & Chrome 49 + uBO:
- jeśli chodzi o https://prenumerata.rp.pl/plusminus problemów nie ma na mojej regule, czyli można powiedzieć, że u 3 osób (ja, @blocker999 i fikcyjna osoba na laptopie) nie ma, a tylko u ciebie jest.
- jeśli chodzi o www.rp.pl to na na moich regułach na FF wszystko w porządku, ale na Chrome wyskakuje margines i to bez przewijania strony, za pierwszym razem (kiedy jeszcze nie ma ciasteczek) ten margines jest o wiele mniejszy bo ma jakieś pół centymetra, ale przy następnych wizytach już jest większy taki jak u ciebie, gdy dodałem  do moich reguł:  
`www.rp.pl##body:style(position: static!important;)` to już marginesu nie ma, czy możesz potwierdzić, że dodanie tej reguły do moich naprawi ci margines? i Ty @blocker999 też sprawdź na WF, bo tobie tez margines wyskakiwał tam.

**Comment by gomoku** [comment]
Tu masz, nie widzisz? https://github.com/azet12/PopupBlocker/issues/127#issuecomment-331501865

**Comment by hawkeye116477** [comment]
@gomoku Tak jak pisałem, u mnie problem jest zapewne dlatego, że ja mam monitor takiej wielkości. 
Jakiej wielkości masz urządzenia?

**Comment by blocker999** [comment]
@hawkeye116477 Plus minus jest ok ale z tym marginesem to dopiero wszystko wiem mianowicie zapewne chodzi o ten biały pasek nad headerem tylko dlaczego na screene nikt go nieoznaczył na czerwono bo ja myślałem że strona zaczyna sie od headeru, wiec zanim ten pasek się załadował to ja już scrollowałem strone i go przeoczyłem a on występuje na slimjet a na waterfoxie nie czekałem i nic, wiec warto dodać regułe od @gomoku chodź by dla części przeglądarek.

Natomiast zastanawia mnie ten scrollujący RSS, co znim robimy?

**Comment by hawkeye116477** [comment]
@blocker999 Powoli, ile cali ma twoje urządzenie? Bo tak jak mówię, u mnie na 19 cali i 55 cali jest problem.

**Comment by gomoku** [comment]
1) Co do tych cali, to nie ilość cali ma znaczenie, lecz rozdzielczość ekranu.
2) To po dodaniu jeszcze tej twojej reguły problem z tym marginesem już całkowicie rozwiązany?

**Comment by hawkeye116477** [comment]
@gomoku Ta, problem z marginesem już całkowicie rozwiązany przynajmniej na PC. Bo tablet się ładuje i nie sprawdzałem czy coś się nie sknoci 😃 .
A no może i masz rację, rozdzielczość, a ty dałeś inne dpi i pewnie dlatego na plusminus ten formularz ci się nie przesuwa, ale skoro moja reguła może powodować problemy jak widzę, no to usunę ją i zostawię ten formularz w spokoju, bo innego pomysłu nie mam.

**Comment by gomoku** [comment]
@hawkeye116477 ale @blocker999'owi też formularz się nie przesuwa, a on z tego co wiem, nie pisał nigdy, że ma zmienione dpi.

**Comment by blocker999** [comment]
@hawkeye116477 Ekran 16,4 cali, rozdzielczość 1920x1080 oraz DPI standardowe tzn nic niezmieniałem, wszystko wiecie, to co robimy z tym marginesem?

**Comment by hawkeye116477** [comment]
A to jest bardzo dziwne, bo na TV w przeglądarce pokazuje mi 1920x1080 i u mnie formularz lata, a u @blocker999 niby nie, ale dobra, nie ważne już i tak na to nic nie poradzimy, więc niech lata 😄 .

**Comment by hawkeye116477** [comment]
A to jest bardzo dziwne, bo na TV w przeglądarce pokazuje mi 1920x1080 i u mnie formularz lata, a u @blocker999 niby nie, ale  on chyba sprawdzał na moich 2 regułach, ale dobra, nie ważne już i tak na to nic nie poradzimy, więc niech lata 😄 .

**Comment by gomoku** [comment]
@blocker999 sprawdzałeś w ten sposób co ja tutaj?: https://github.com/azet12/PopupBlocker/issues/127#issuecomment-331615678

**Comment by hawkeye116477** [comment]
@gomoku To też jest ok, ten widget już jest w PB. A te drugie chyba też już dodałem do ciastkowej listy. 
Tylko co z tym RSSem, chodzi o czytaj.rp.pl? No to niestety ja tam konta nie posiadam.

**Comment by gomoku** [comment]
Wiem, bo w momencie zanim odpisałeś to już zdążyłem edytować i poprawić.

**Comment by blocker999** [comment]
@gomoku Ja wyłączyłem popupblokera i dodałemwww.rp.pl##body:style(position: static!important;) i jest ok.

@hawkeye116477 ten RSS jest po lewej od góry do dołu skroluje, pewnie go usunełeś razem z socialami, dlatego proponuje go przywrócić i usadzić na dole.

**Comment by gomoku** [comment]
> @blocker999: Ja wyłączyłem popupblokera i dodałemwww.rp.pl##body:style(position: static!important;) i jest ok.

A więc to nie rozdzielczość jest winą, bo obaj macie FullHD, a tylko u @hawkeye116477 jest problem z formularzem.

**Comment by hawkeye116477** [comment]
@gomoku Ale @blocker999 pisze tylko o jednej regule.

**Comment by gomoku** [comment]
No bo przecież chodzi o moją regułę, i u mnie i u @blocker999a na mojej regule nie ma problemó z formularzem.

**Comment by blocker999** [comment]
@hawkeye116477 gdzie ta druga w PB ? Konkretnie która to to potestuje.

**Comment by hawkeye116477** [comment]
@gomoku No tak, o twoją, ale nie na tą stronę, blocker teraz pisze o www.rp.pl. A mi chodziło o https://prenumerata.rp.pl/plusminus.
@blocker999 Wpisz to i wyłącz PopupBlocker:
`prenumerata.rp.pl###header:style(position: static!important;)`
I wejdź tu -> https://prenumerata.rp.pl/plusminus. Mi tam formularz zmienia rozmiar i jeździ na PC i TV.

**Comment by gomoku** [comment]
> @blocker999: @gomoku Ja wyłączyłem popupblokera i dodałem www.rp.pl##body:style(position: static!important;) i jest ok.

Myślałem, że o prenumeratę mu chodziło, bo jaki sens jest dodawania samej reguły: `www.rp.pl##body:style(position: static!important;)` ?

**Comment by gomoku** [comment]
No dobra, źle odczytałem, fakt pisał o www.rp.pl.

**Comment by hawkeye116477** [comment]
@gomoku A ty masz ten RSS? Bo ja socjalistyczne wyłączyłem i nadal nie widzę nic takiego. Także proszę @blocker999 o screena.

**Comment by gomoku** [comment]
Może mu chodzi o ten przycisk z 3 kreskami po lewej, który odchodzi i jedzie ze scrollem, ale tylko wtedy gdy zaczniemy przewijać stronę w dół zanim strona się w pełni załaduje, wystarczy poczekać aż strona się załaduje do końca i dopiero przewinąć w dół to wtedy ten przycisk nie odchodzi, czy to się zatem kwalifikuje jako defekt, czy jako wina po stronie użytkownika, który przewija stronę, gdy się jeszcze nie załadowała do końca?:
![](https://s3.dodajfote.pl/2017/09/23/lewadd8d0.png)

**Comment by blocker999** [comment]
@hawkeye116477 Z włączonym PB jest ok natomiast jak wyłączyłem PB i dodałem twoją regułe i ponownie weszłem na strone to ani na slimjet ani na waterfozie niejest poprawnie, aby urzeczywistnić ten fakt, podaje screena:
![prenumerata](https://user-images.githubusercontent.com/23176832/30773567-62983cc6-a073-11e7-892a-620208f08d53.png)

A teraz screen
![rp rss](https://user-images.githubusercontent.com/23176832/30773575-9b776e7c-a073-11e7-96f2-f6ed627dd732.png)
 do tego RSS-a :

**Comment by gomoku** [comment]
O i kolejny guzik odlatuje :)

**Comment by hawkeye116477** [comment]
@gomoku Czyli jednak to kwestia rozdzielczości, ale z tym formularzem to ja nic nie zrobię już, gdyż podawałem 2 regułę, ale jak widać ona powoduje problemy na pewnych urządzeniach, więc ja bym to po prostu zostawił jak jest. 
@blocker999 No tam gdzie wchodziłeś jest formularz -> https://prenumerata.rp.pl/plusminus
Co do RSS, to ja tego nie mam nawet bez uBlocka.  A tego guzika też nie mam.

**Comment by hawkeye116477** [comment]
@gomoku Czyli jednak to kwestia rozdzielczości, ale z tym formularzem to ja nic nie zrobię już, gdyż podawałem 2 regułę, ale jak widać ona powoduje problemy na pewnych urządzeniach, więc ja bym to po prostu zostawił jak jest. 
@blocker999 No tam gdzie wchodziłeś jest formularz -> https://prenumerata.rp.pl/plusminus
Co do RSS, to ja tego nie mam nawet bez uBlocka.  A co do tego guzika, a to widzę na tablecie, ale na PC nie.

**Comment by hawkeye116477** [comment]
@gomoku Czyli jednak to kwestia rozdzielczości, ale z tym formularzem to ja nic nie zrobię już, gdyż podawałem 2 regułę, ale jak widać ona powoduje problemy na pewnych urządzeniach, więc ja bym to po prostu zostawił jak jest. 
@blocker999 No tam gdzie wchodziłeś jest formularz -> https://prenumerata.rp.pl/plusminus
Co do RSS, to ja tego nie mam nawet bez uBlocka.  **A co do tego guzika, a to widzę, po jakimś czasie znika.**

**Comment by blocker999** [comment]
@hawkeye116477 Przepraszam poprostu teraz wiem o jaki formularz chodzi, narazie niech będzie a rss i guzikiem to ja się zajme bo szkoda twojego czasu na to, lepiej zajmij sie pozostałymi tematami.

**Comment by gomoku** [comment]
> @hawkeye116477: Co do RSS, to ja tego nie mam nawet bez uBlocka.

Ja tak samo.

**Comment by blocker999** [comment]
@gomoku Wersja na Waterfoxie bez UBO i dalej jest rss: 
![bez](https://user-images.githubusercontent.com/23176832/30773930-26651c4e-a07b-11e7-91cd-d3e6cad8ca48.png)

**Comment by hawkeye116477** [comment]
@blocker999 No to wychodzi na to, że może admina powinni wymienić, bo ja na PC ani tablecie nie mam takich przycisków, a na TV mam. Niech admin się bierze do roboty i robi stronę w pełni responsywną.

**Comment by blocker999** [comment]
@hawkeye116477 No właśnie bo co urządzenie inne to inaczej a co inna przeglądarka to obyczaj więc chyba to nie dla nas robota,co?

@gomoku A te scrollujące ikonki masz?

Przykładowy artykuł : 

http://www.rp.pl/Firma/309239960-Instytucjonalny-najem--daje-wiecej-bezpieczenstwa.html

![rp ikonki](https://user-images.githubusercontent.com/23176832/30774036-c9fafbac-a07c-11e7-86c6-e941fdf9d888.png)

**Comment by gomoku** [comment]
@blocker999 nie mam.

@hawkeye116477 znalazłem jeszcze jedną stronę i są 2 filtry do dodania, edytowałem i dodałem do pierwszego komentarza, patrz punkt 5.

**Comment by hawkeye116477** [comment]
@gomoku @blocker999 Schowałem All in One Sidebar w Waterfoksie i sidebar w Vivaldim i teraz widzę te ikonki. Ale na tablecie to ja nie mam żadnego sidebara i tam ich nie widzę, także chyba admin coś powinien poprawić.
@gomoku Nie odpisałeś mi -> https://github.com/azet12/PopupBlocker/issues/133 😄 .

**Comment by gomoku** [comment]
Widziałem, i nie odpisałem, bo to a) nie forum polityczne, b) nie chcę pisać tu o polityce c) chcę zachować dla siebie pewne kwestie d) rząd szpieguje po ip

**Comment by hawkeye116477** [comment]
@gomoku Ok

**Comment by blocker999** [comment]
@gomoku Konkretnie co na tej stronie zrobić podnieść ją czy co?

**Comment by hawkeye116477** [comment]
@gomoku A no to teraz wszystko już wiem, czyli nie obrazisz się jak ich pominiemy?

**Comment by gomoku** [comment]
@blocker999 już odświeżyłem pierwszy post, bo faktycznie miałem o tym napisać, a zapomniałem.
@hawkeye116477, tych o którym pisałem tu: https://github.com/azet12/PopupBlocker/issues/127#issuecomment-331639916 ? No jeśli uzasadnisz sensownie.

**Comment by hawkeye116477** [comment]
@gomoku Ja mówię o Republice i Niezależnej.

**Comment by blocker999** [comment]
@gomoku Co chwile edytujesz posty, " znalazłem jeszcze jedną stronę i są 2 filtry do dodania, edytowałem i dodałem do pierwszego komentarza, patrz punkt 5." wieć myslałem o stronie bloombergbusinessweek.pl a teraz się okazało że to kariera.pl, ja mam czas?

**Comment by gomoku** [comment]
@blocker999 źle zrozumiałeś, tę www.kariera.pl to ja znalazłem przed tobą i dodałem do pierwszego posta, a dopiero teraz przeczytałem twój komentarz więc dodałem także bloombergbusinessweek.pl patrz punkt 6, dzięki.

**Comment by hawkeye116477** [comment]
@gomoku @blocker999 Chłopaki ja się zajmuję listą ciasteczkową, także potem to przejrzę i być może dodam.
