### ISSUE TITLE
www.polsatnews.pl

### ISSUE THREAD

**Issue by gomoku** [azet12/PopupBlocker#128]
Header u góry do usadzenia, filtr:
`www.polsatnews.pl##header[id="header"]:style(position: static!important;)`
Odrazu pod headerem pomarańczowy pasek informacyjny do usadzenia, filtr
`www.polsatnews.pl###urgent:style(position: static!important;)`

ale trzeba jeszcze:
- przesunąć hdrinfo (WIDZISZ ZAREAGUJ) w górę
- usunąć margines czyli przesunać body w górę (wyłączyć margin-top: 116px;)

![](https://s3.dodajfote.pl/2017/09/21/poslatnewsf4c79.png)

**Comment by hawkeye116477** [comment]
@gomoku No i mamy problem, bo ja tego pomarańczowego paska nie widzę.
Ale z headerem można zrobić tak:`www.polsatnews.pl##header[id="header"]:style(position: absolute!important;)`, wtedy nie będzie marginesu.

**Comment by gomoku** [comment]
- spoko, faktycznie tak marginesu nie ma
- dalej trza przesunąć hdrinfo (WIDZISZ ZAREAGUJ) w górę
- nie widzisz tego pomarańczowego paska, bo na chwilę obecną zniknął, ja też go teraz nie widzę, ale zapewne niedługo się znowu pojawi, pewnie pojawia się jeśli jest jakieś ważne wydarzenie, tzw. gorący news, tak więc musisz od czasu do czasu tam lunkąć i przyczaić się wiesz ukryty smok, przyczajony tygrys :)

**Comment by hawkeye116477** [comment]
@gomoku Chyba jednak damy na static, bo na absolute to widzę, że nadal się trochę rusza.

```
www.polsatnews.pl##header[id="header"]:style(position: static!important;)
www.polsatnews.pl##.body:style(margin-top: 0px!important;)
```

Przy okazji strzałkę zauważyłem -> `www.polsatnews.pl###fab`

**Comment by gomoku** [comment]
Wiesz, co teraz to w ogóle sieczka jakaś się zrobiła, po tym gdy usunęli ten pomarańczowy pasek, jeśli na moich lub twoich filtrach przewinie się stronę do dołu, a potem do góry to header znowu wyskakuje.
![](https://yt3.ggpht.com/-rXUumPbv_Qw/AAAAAAAAAAI/AAAAAAAAAAA/e3j7Oh-wv44/s48-c-k-no-mo-rj-c0xffffff/photo.jpg)

**Comment by gomoku** [comment]
No teraz jest gitara, tylko jeszcze te 2 ostatnie punkty z tego: https://github.com/azet12/PopupBlocker/issues/128#issuecomment-331174363

**Comment by hawkeye116477** [comment]
@gomoku To z tym napisem jest bardzo dziwne, bo u mnie na Waterfoksie jest ok. Może to te stare polskie filtry coś knocą 😃 .

**Comment by gomoku** [comment]
Nie, bo po pierwsze nie używam starych polskich list do testowania, a po drugie nawet gdy wyłączyłem wszystkie listy, i zostawiłem tylko twoje 2 filtry, to dalej to samo, zagadkę rozwiązałem gdy ustawiłem wielkość strony na 90% lub 110% wtedy ten napis wskakuje na odpowiednie miejsce, tylko, że mnie interesuje rozmiar strony 100% czy zwyczajny, więc o co tu chodzi, mógłbyś u siebie sprawdzić różne rozmiary strony? CTRL + rolka myszki.

**Comment by hawkeye116477** [comment]
@gomoku Sprawdziłem różne rozmiary i jest git na wszystkich. Także nie wiem o co tu chodzi, coś jest chyba najwyraźniej nie tak po twojej stronie.

**Comment by gomoku** [comment]
To niech może @blocker999 jeszcze sprawdzi? I ja też jutro sprawdzę na innym komputerze.

**Comment by hawkeye116477** [comment]
@gomoku Ja tez mam rozdzielczość ekranu 1280x1024. Ok, to niech sprawdzi. Zatwierdzić jeszcze nie możemy, bo musimy załapać się na tego złotego węża.

**Comment by gomoku** [comment]
@hawkeye116477 na Win 7? To weź ustaw 125% DPI + Aero

**Comment by hawkeye116477** [comment]
@gomoku Ustawiałem na Win 7 i jest ok. A może zrób nowy profil z uBlockiem i sprawdź czy na nowym to nie występuje.

**Comment by gomoku** [comment]
Na drugim profilu defektu nie ma. Tylko, że ten drugi profil to taki na co dzień wiesz, dużo dodatków, własne ustawienia itp profile ma już kilkanaście miesięcy, a na świeżym profilu defekt jest, a powinno zdaje się być odwrotnie.

**Comment by gomoku** [comment]
Można zamknąć.

**Comment by hawkeye116477** [comment]
@gomoku Jeszcze nie mogę, bo nie wiem co z tym wężem.

**Comment by gomoku** [comment]
Acha zapomniałem o nim.

**Comment by hawkeye116477** [comment]
@gomoku W końcu się pojawił.
`www.polsatnews.pl###urgent:style(position: static!important;)`
