### ISSUE TITLE
www.bs-legal.pl

### ISSUE THREAD

**Issue by gomoku** [azet12/PopupBlocker#129]
Do usadzenia bo wszystko jeździ razem ze scrollem,:
1) Header u góry do osadzenia składający się z 2 pasków +
2) Likwidacja resztek czyli marginesu czyli przesunięcie strony do góry
3) 4 przyciski social po prawej stronie

Filtry w odpowiedniej kolejności:

```
www.bs-legal.pl##.fl-page-bar, .fl-shrink-header-transition.fl-page-nav-toggle-visible-mobile.fl-page-nav-toggle-button.fl-page-nav-right.fl-page-header-primary.fl-page-header:style(position: static!important;)
www.bs-legal.pl##html > body > .fl-page:style(padding-top: 0px!important;)
www.bs-legal.pl###icon_wrapper
```

![](https://s3.dodajfote.pl/2017/09/21/rrrrrrrrrrrrrrrrrrr4a021.png)

**Comment by hawkeye116477** [comment]
Tak będzie krócej i lepiej.
```
www.bs-legal.pl##.awesome-social
www.bs-legal.pl##.fl-page-bar, .fl-page-header:style(position: absolute!important;)
```
