### ISSUE TITLE
niezalezna.pl

### ISSUE THREAD

**Issue by gomoku** [azet12/PopupBlocker#130]
Sorry, dopiero zorientowałem się, że powinienem był pisać w już istniejącym wątku: https://github.com/azet12/PopupBlocker/issues/21

Header u góry do usadzenia: 
! filtr osadzający header
! filtr usadzający 1 z jeżdżących kontenererów
```
niezalezna.pl###header:style(position: static!important;)
niezalezna.pl###pageWrapper:style(top: -100px!important;)
```
Ale nie umiem usadzić drugiego jeżdżącego kontenera:
`niezalezna.pl###menuLeftContainer:style(top: 100px!important;)`
bo osadzony javaskrypt ciągle to nadpisuje, więc zostaje defekt - przy przewijaniu ten kontener wjeżdża/wyjeżdża, bo top zmienia się ze 100 na 71, a potem z 71 na 100:
https://s3.dodajfote.pl/2017/09/23/niezalezna949a1.png
a o ile mi wiadomo nowa wersja Firefoxa już nie pozwala uBlock Origin'owi na obsługę wyłączania pojedynczych skryptów osadzonych za pomocą: 
`niezalezna.pl##script:contains(...)` 
https://github.com/gorhill/uBlock/wiki/Static-filter-syntax#scriptcontains
więc chyba ktoś będzie musiał pobawić się:
`niezalezna.pl##script:inject(...)` 
https://github.com/gorhill/uBlock/wiki/Static-filter-syntax#scriptinject i może uda mu się uwalić ten osadzony js.

![](https://s3.dodajfote.pl/2017/09/21/niezalezna28d48.png)

**Comment by hawkeye116477** [comment]
![obraz](https://user-images.githubusercontent.com/19818572/30695725-872cdbdc-9ed9-11e7-8f4e-0828a9221249.png) 😃

**Comment by hawkeye116477** [comment]
@gomoku Czyli znowu robota dla @F4z.

**Comment by gwarser** [comment]
Może `niezalezna.pl##script:inject(abort-on-property-read.js, onscroll)`

**Comment by hawkeye116477** [comment]
@gwarser Na uBlocku to działa, a dla tych biedaków co mają AdGuarda znasz jakieś rozwiązanie?
