### ISSUE TITLE
context.reverso.net

### ISSUE THREAD

**Issue by gomoku** [azet12/PopupBlocker#132]
Przykładowy link: http://context.reverso.net/t%C5%82umaczenie/polski-angielski/komus+kto+jest+w+areszcie

To wszystko co widoczne na dole na obrazku, po kolei:
1) Popup na dole po lewej
2) Popup po środku
3) Przyciski social na dole po prawej
```
context.reverso.net###register-popup-bottom, #blocked-results-banner, #global-options
```
Lub jeśli ktoś nie chce usuwać obydwu przycisków, to może usunąć tylko jeden, wystarczy zamiast #global-options dać, jeden z tych dwóch:

4) Sam przycisk kłódki `context.reverso.net##.lock.icon`
5) Sam przycisk strzałki `context.reverso.net##.go-up.icon`

![](https://s3.dodajfote.pl/2017/09/22/1114a328.png)

**Comment by blocker999** [comment]
@gomoku Popup po lewej usuniemy i strzałke, kódke proponuje usadzić a ten Popup na środku chyba zostawimy "Zarejestruj się, żeby zobaczyć więcej przykładów" bo to info chcących kontynuować czytanie, może tak być ?

**Comment by gomoku** [comment]
OK.

**Comment by hawkeye116477** [comment]
Tak będzie najlepiej -> `context.reverso.net###register-popup-bottom, .lock.icon, .go-up.icon`. Popup na środku zostawiamy.
