### ISSUE TITLE
telewizjarepublika.pl

### ISSUE THREAD

**Issue by gomoku** [azet12/PopupBlocker#133]
Header szary u góry do usadzenia, bo lata za scrollem, na
http://telewizjarepublika.pl/ oraz
http://beta.telewizjarepublika.pl/
`telewizjarepublika.pl###header-top:style(position: static!important;)`

![](https://s3.dodajfote.pl/2017/09/22/11112920.png)

Header granatowy u góry do usadzenia, bo lata za scrollem, na:
http://m.telewizjarepublika.pl/
`m.telewizjarepublika.pl##header:style(position: static!important;)`

![](https://s3.dodajfote.pl/2017/09/22/mmmm1236d.png)

Tu czysto:
http://karta.telewizjarepublika.pl
http://arch.telewizjarepublika.pl/praca
http://sklep.telewizjarepublika.pl
http://ri.telewizjarepublika.pl

**Comment by hawkeye116477** [comment]
@gomoku Lubisz PiS?

**Comment by hawkeye116477** [comment]
@gomoku Lubisz PiS? Kaczyński to twój idol 😃 ?
