### ISSUE TITLE
www.ckm.pl

### ISSUE THREAD

**Issue by gomoku** [azet12/PopupBlocker#134]
Header biały u góry do usadzenia, bo lata za scrollem, na http://www.ckm.pl/
`www.ckm.pl##.fixed-active.clearfix:style(position: static!important;)` dosyć dobrze usadzone, z tym, że coś jeszcze leciutko tak magnesuje, chyba jakieś resztki niewidzialne, da się to zauważyć przy wolnym przewijaniu w górę/w dół, nie wiem czy to da się w ogóle poprawić, chodzi mi o coś takiego jak tu opisałem: https://github.com/azet12/PopupBlocker/issues/123#issuecomment-330926079

![](https://s3.dodajfote.pl/2017/09/22/33331319.png)

Tu czysto:
http://magazyn.ckm.pl/
http://ckmbox.ckm.pl/

**Comment by hawkeye116477** [comment]
Pilnie potrzebna pomoc @F4z

**Comment by gwarser** [comment]
```
www.ckm.pl##.nav.fixed-active ul:style(padding: 11px 0!important; margin: auto!important; )
www.ckm.pl##.nav.fixed-active:style(height: auto!important; )
```

**Comment by hawkeye116477** [comment]
@gomoku Sprawdź czy jest ok z regułami @gwarser, bo ja tam wcześniej nie widziałem efektu magnesowania, więc nie dostrzegam różnicy.

**Comment by gwarser** [comment]
Między przerywaną linią pod "livestyle moto..." a pierwszym obrazkiem.

Trochę dużo modyfikacji. Można by też spróbować odwrotnie - dodać styl taki jak przy .fixed-active jak .fixed-active jeszcze nie ma.

**Comment by hawkeye116477** [comment]
@gwarser Już widzę, z twoimi regułami jest ok.

**Comment by gomoku** [comment]
Potwierdzam, że już jest ok.
