### ISSUE TITLE
[Grupa TVN/TVN24 Media]

### ISSUE THREAD

**Issue by gomoku** [azet12/PopupBlocker#135]
https://pl.wikipedia.org/wiki/Grupa_TVN

Usadzenie Grupy TVN/TVN24, testowane na:
- system: Win 7 SP1 64bit & Aero & 125% DPI & ekran 1280x1024 
 - przeglądarki: FF 55.0.3 64bit / Opera 47 64bit 
- blocker: uBlock Origin v1.14.11b4
- listy:
Adblock Warning Removal List
EasyList
EasyPrivacy
Fanboy’s Enhanced Tracking List
Fanboy’s Cookiemonster List
POL: polskie filtry do Adblocka i uBlocka​​​​​użytych
POL: polskie filtry do uBlocka uzupelnienie​
​​​​Adblock & uBlock polish cookies filters​​​​​użytych
KAD - Przekręty​​
Popup Blocker PLUS ( PL )​​
(zapomniałem włączyć Fanboy’s Cookiemonster List)

Wszystkie reguły (poza jedną na Firefoxie, pokazaną czerwoną strzałką na obrazku) działają bezproblemowo:

**1_**
! usadzenie scrolującego headera
`zdrowie.tvn.pl##.l-page__header-content:style(position: absolute!important;)`

![](https://s3.dodajfote.pl/2017/10/10/tvn_zdrowie_headeref3b161ff4c52e7d.png)

**2_**
! http://www.tvn.pl/ usadzenie headera
`www.tvn.pl##.top:style(position: absolute!important;)`

![](https://s3.dodajfote.pl/2017/10/10/tvn_header173bb3e115135322.png)

**3_**
! usadzenie scrollującego podwójnego headera
! http://www.tvn.pl/o-tvn
`www.tvn.pl##.top:style(position: absolute!important;)`
`www.tvn.pl##.text-nav-container:style(position: absolute!important;)`

![](https://s3.dodajfote.pl/2017/10/10/tvn_podwojny_headerac992e2dfe435d02.png)

**4_**
! http://www.tvn24.pl/ i http://sport.tvn24.pl/ górne 2 headery
```
www.tvn24.pl,sport.tvn24.pl##.headerTop:style(position: absolute!important;)
www.tvn24.pl,sport.tvn24.pl###GemiusXYMap\:nav:style(position: absolute!important; top: 128px!important)
```
![](https://s3.dodajfote.pl/2017/09/22/tvn_h104ca1.png)

**5_**
! http://www.tvn24.pl/witamy-w-nowym-tvn24-pl,254522,s.html
! http://sport.tvn24.pl/pilka-nozna,105/korona-pokonala-w-kielcach-wisle-karkow-2-1,775510.html
 pływający ze scrollem social bar:
`www.tvn24.pl,sport.tvn24.pl##.sticky.shareContainerTop.headerShareContainer:style(position: absolute!important;)`

![](https://s3.dodajfote.pl/2017/09/24/s21546d.png)

**6_**
! https://tvnmeteo.tvn24.pl/informacje-pogoda/prognoza,45/nadciaga-pogodowe-zepsucie-z-zachodu,242509,1,0.html
! https://tvnwarszawa.tvn24.pl/informacje,news,zjezdzalem-ze-skrzyzowania-rower-pojawil-sie-nagle,242632.html
pływający ze scrollem podwójny header: social bar + powrót do góry:
`tvnmeteo.tvn24.pl,tvnwarszawa.tvn24.pl##.shareContainerTop`

**_DODANE:_**
! ! https://fakty.tvn24.pl/fakty-po-faktach,57/sebastian-kaleta-i-marcin-swiecicki-w-faktach-po-faktach,779661.html
`fakty.tvn24.pl##.headerStickyContainer`

![](https://s3.dodajfote.pl/2017/10/02/tvn24meteo_header_social665e66dcb6673b0d.png)

**7_**
! http://www.tvn24.pl/magazyn-tvn24/kaczynski-nie-bedzie-negocjowal-z-duda-lojalnosc-wymusi,118,2142 górny header pływający ze scrollem:
`www.tvn24.pl##.main-header:style(position: static!important;)`

![](https://s3.dodajfote.pl/2017/09/24/h1b7020.png)

**8_** 
! http://www.tvn24.pl/magazyn-tvn24/kaczynski-nie-bedzie-negocjowal-z-duda-lojalnosc-wymusi,118,2142
social bar przyciski po lewej : `www.tvn24.pl##.side-info`
(a jeśli ktoś chce te przyciski nie usunąć, tylko usadzić, to będzie miał problem taki jak tu: https://github.com/azet12/PopupBlocker/issues/130 z elementem: `www.tvn24.pl##shareContainerList:style(top: 30px!important)` bo jest nadpisywany przez osadzony js i trzeba będzie otworzyć ponownie wątek i dać etykietę "potrzebna pomoc" https://s3.dodajfote.pl/2017/09/24/ss688b3.png)

![](https://s3.dodajfote.pl/2017/09/24/s1859ee.png)

**9_**
! http://tvn24bis.pl/ górne 2 headery
```
tvn24bis.pl##.header-network:style(position: absolute!important;)
tvn24bis.pl###navigation-main:style(position: static!important;)
```
![](https://s3.dodajfote.pl/2017/09/22/tvn_h37702c.png)

**10_**
! http://tvn24bis.pl/wiadomosci-gospodarcze,71/newsy-programy-i-tvn24-na-zywo-wszedzie-aplikacje-na-smartfony-i-tablety,480902.html górny header
`tvn24bis.pl##.stock-exchange:style(position: static!important;)`
![](https://s3.dodajfote.pl/2017/09/22/tvn_h4a758c.png)
! Na FF wyskakuje cienki szary pasek pod headerem podczas przewijania w górę/w dół (na Operze nie)
![](https://s3.dodajfote.pl/2017/09/22/tvn_h5dc983.png)

**11_**
! http://kontakt24.tvn24.pl/ górny header
`kontakt24.tvn24.pl##.menu-main:style(position: absolute!important; top: 28px!important)`
![](https://s3.dodajfote.pl/2017/09/22/tvn_h6ec783.png)

**12_**
! http://faktypofaktach.tvn24.pl/ górny header
```
faktypofaktach.tvn24.pl,szklokontaktowe.tvn24.pl##header:style(position: static!important;)
faktypofaktach.tvn24.pl,szklokontaktowe.tvn24.pl##.bgHeaderMain:style(position: absolute!important;)
faktypofaktach.tvn24.pl,szklokontaktowe.tvn24.pl##.small.headerContainer:style(position: absolute!important;)
```
![](https://s3.dodajfote.pl/2017/09/22/tvn_h7733d1.png)

**13_**
! https://www.tvnmedia.pl/ górny header (on tak odstawał, bo został pusty pasek po komunikacie o ciasteczkach usuniętym wcześniej przez jakiś inny filtr z jakiejś listy)
`www.tvnmedia.pl##.hamburger-wrapper:style(position: static!important;)`
![](https://s3.dodajfote.pl/2017/09/22/tvn_h842167.png)

**14_**
! http://toteraz.pl footer
`toteraz.pl###footer-bar:style(position: static!important;)`
![](https://s3.dodajfote.pl/2017/09/22/tvn_f9de838.png)

**15_**
! https://player.pl/# header
`player.pl##.navbar-wrapper.js-navbar-scroll.navbar-wrapper--sticky:style(position: static!important;)`

![](https://s3.dodajfote.pl/2017/09/22/tvn_h106ed10.png)

**16_**
! http://kulinarni.tvn.pl/ header + widget social przycisk po lewej
```
kulinarni.tvn.pl##.bgHolder > header:style(position: absolute!important;)
kulinarni.tvn.pl##.fbWidget
```
![](https://s3.dodajfote.pl/2017/09/22/tvn_h11f36b0.png)

**17_**
! https://www.mango.pl/ aż 3 elementy
! jebunty popup
! widżet typu czat-helper na dole strony po prawej
! widżet typu zapisz się na dole strony po lewej
`www.mango.pl###newsletterModal > .modal-lg.modal-dialog, #chat-toggle, #smSubscriptonBox`
![](https://s3.dodajfote.pl/2017/09/22/jebutny_banerdf45f.png)
![](https://s3.dodajfote.pl/2017/09/22/jebutny2i3a6065.png)

**18_**
! usunięcie scrollującego widżetu typu "nastęny artykuł" po prawej przy przewijaniu strony
! http://nawspolnej.tvn.pl/wideo,443,v/daria-pocieszycielka-dominika,1667316.html
`nawspolnej.tvn.pl###nextItem`

![](https://s3.dodajfote.pl/2017/10/10/tvn_podstrona_nastepne_video_po_prawej2fb33023283af8a6.png)

! Tu czysto w sensie, że albo czysto albo inne listy zbierają:
! http://19plus.tvn.pl
! http://36i6.tvn.pl
! http://agent.tvn.pl
! http://azjaexpress.tvn.pl
! http://cozatydzien.tvn.pl
! http://diagnoza.tvn.pl
! http://distribution.tvn.pl
! http://drugaszansa.tvn.pl
! http://drzewomarzen.tvn.pl
! http://drzewomarzen.tvn.pl
! http://dziendobry.tvn.pl
! http://hgtv.pl
! http://itvnextra.pl
! http://kariera.tvn.pl
! http://kuba.tvn.pl
! http://kuchennerewolucje.tvn.pl
! http://mamtalent.tvn.pl
! http://masterchef.tvn.pl
! http://milionerzy.tvn.pl
! http://nakrancuswiata.tvn.pl
! http://nawspolnej.tvn.pl
! http://ncplus.pl
! http://rozmowywtoku.tvn.pl
! http://slub.tvn.pl
! http://superwizjer.tvn.pl
! http://szkola.tvn.pl
! http://ttv.pl
! http://tvnfabula.pl
! http://ukrytaprawda.tvn.pl
! http://www.itvn.pl
! http://www.tvn7.pl
! http://www.tvnstyle.pl
! http://www.tvnturbo.pl
! https://fundacja.tvn.pl
! https://sso.tvn24.pl
! https://x-news.pl

Wszystkie reguły do łatwego kopiuj-wklej, posortowane alfabetycznie:
```
!? www.tvn24.pl##.side-info
faktypofaktach.tvn24.pl,szklokontaktowe.tvn24.pl##.bgHeaderMain:style(position: absolute!important;)
faktypofaktach.tvn24.pl,szklokontaktowe.tvn24.pl##.small.headerContainer:style(position: absolute!important;)
faktypofaktach.tvn24.pl,szklokontaktowe.tvn24.pl##header:style(position: static!important;)
kontakt24.tvn24.pl##.menu-main:style(position: absolute!important; top: 28px!important)
kulinarni.tvn.pl##.bgHolder > header:style(position: absolute!important;)
kulinarni.tvn.pl##.fbWidget
player.pl##.navbar-wrapper.js-navbar-scroll.navbar-wrapper--sticky:style(position: static!important;)
toteraz.pl###footer-bar:style(position: static!important;)
tvn24bis.pl###navigation-main:style(position: static!important;)
tvn24bis.pl##.header-network:style(position: absolute!important;)
tvn24bis.pl##.stock-exchange:style(position: static!important;)
tvnmeteo.tvn24.pl##.shareContainerTop
www.mango.pl###newsletterModal > .modal-lg.modal-dialog, #chat-toggle, #smSubscriptonBox
www.tvn24.pl##.main-header:style(position: static!important;)
www.tvn24.pl,sport.tvn24.pl###GemiusXYMap\:nav:style(position: absolute!important; top: 128px!important)
www.tvn24.pl,sport.tvn24.pl##.headerTop:style(position: absolute!important;)
www.tvn24.pl,sport.tvn24.pl##.sticky.shareContainerTop.headerShareContainer:style(position: absolute!important;)
www.tvnmedia.pl##.hamburger-wrapper:style(position: static!important;)
```

Reguły być może można scalić / połączyć / zoptymalizować, może ktoś znajdzie także jakieś nowe strony TVN do usadzenia, co prawda dosyć dobrze przeczesałem, ale zawsze jakąś stronę mogłem przeoczyć.

**Comment by gomoku** [comment]
Znalazłem 3 nowe elementy do zablokowania, znajdują się w pierwszym komentarzu, który odświeżyłem:
pkt 2) uzupełnienie filtru o domenę `sport.tvn24.pl`
pkt 3) i 4) nowe filtry do dodania

**Comment by gomoku** [comment]
Tu chyba ktoś dać etykiety "potrzebna pomoc".

**Comment by gomoku** [comment]
Do dodania pkt 2a)

**Comment by gomoku** [comment]
Chyba ktoś zapomniał, więc przypominam.

**Comment by hawkeye116477** [comment]
@gomoku Zrobione.

**Comment by gomoku** [comment]
Do dodania pkt 2 ("DODANE")

**Comment by gomoku** [comment]
Ktoś chyba zapomniał/nie zauważył bo wisi od kilku dni, więc przypominam - do dodania (komentarz wyżej).
