### ISSUE TITLE
www.tygodniksiedlecki.com

### ISSUE THREAD

**Issue by gomoku** [azet12/PopupBlocker#136]
Znalazłem ciekawą stronę na której jest od groma syfu i częściowo jest uwalona, i której naprawianie wymagało będzie wrzucenia filtrów na 3 różne listy, napiszę jeszcze tylko, że całą stronę ogarnąłem elegancko i wszystkie filtry działają u mnie bezproblemowo, przetestowane na tych samych ustawieniach co tu https://github.com/azet12/PopupBlocker/issues/135#issue-259897166 (z tym, że dodatkowo tu miałem Fanboyz Cookiemonster włączone):

! http://tygodniksiedlecki.com
! http://tygodniksiedlecki.com/t7366-to.nie.kurort..to.wiezienie.htm

- zacznijmy od rzeczy, które będą naprawiane na PopupBlocker PLUS (PL):
! header u góry jeździ za scrollem (zrzut ekranu 1)
`tygodniksiedlecki.com##.sticky.avoid-print-this.on.bootsnav.navbar-mobile.navbar-default.navbar:style(position: static!important;)`
! subheader slide baner czarny wyjeżdżający z headera (zrzut ekranu 2)
`tygodniksiedlecki.com##.avoid-print-this.bottom-bar:style(position: static!important;)`
`||tygodniksiedlecki.com/assets/mobile/js/ts.js$script,first-party`

- dalej filtr poprawkowy, który będzie szedł na listę Fanboy Cookiemonster: https://github.com/ryanbr/fanboy-adblock/issues/138 , filtr ten naprawia menu od górnego headera, które się nie rozwija (również zrzut ekranu 2):
`@@||tygodniksiedlecki.com/assets/mobile/cookiebar/jquery.cookiebar.js$script,first-party`

- dalej będą szły reklamy oraz dziury po reklamach na POL: polskie filtry do Adblocka i uBlocka https://github.com/MajkiIT/polish-ads-filter/issues/3776:
! reklama flash po środku
`tygodniksiedlecki.com##body > .container > .post-wrapper.row > .col-xs-12.col-sm-12.co-md-8.col-lg-8 > .article > .article-wrapper > .avoid-print-this:nth-of-type(3)`
! reklama środkowy tekst
`tygodniksiedlecki.com##body > .wrapper > .container > .post-wrapper.row > .col-xs-12.col-sm-12.co-md-8.col-lg-8 > .article > .article-wrapper > .avoid-print-this:nth-of-type(3)`
! reklama u góry nad headerem (zrzut ekranu 3)
! reklama u góry pod headerem (również zrzut ekranu 3)
! reklama pod zdjęciem pod headerem (zrzut ekranu 4)
! resztki po reklamie pusty średni kontener po prawej
! resztki po reklamie pusty mały kontener na środku (zrzut ekranu 5)
! resztki po reklamie pusty mały kontener na dole 1
! resztki po reklamie pusty mały kontener na dole 2 (zrzut ekranu 7)
! resztki po reklamie pusty duży kontener na dole  (zrzut ekranu 6)
! resztki po reklamie pusty wielki kontener na dole 1 (również zrzut ekranu 7)
! resztki po reklamie pusty wielki kontener na dole 2 (również zrzut ekranu 7)
`tygodniksiedlecki.com###banner-top-top, .mb-5.row, #baner_glowna_polecamy, #baner_publicystyka1, #baner_dyzur1, #baner_prawa_dyzur1, #baner_glowna_dol1, #baner_lewy, #baner_prawa_aktualnosci, #baner_prawy1` lub
`tygodniksiedlecki.com###banner-top-top, .mb-5.row, div[id^="baner"]`

Zrzut ekranu 1:
![](https://s3.dodajfote.pl/2017/09/23/headerf01f6.png)

Zrzut ekranu 2:
![](https://s3.dodajfote.pl/2017/09/23/headermenudb6fc.png)

Zrzut ekranu 3:
![](https://s3.dodajfote.pl/2017/09/23/reklamy135e2b.png)

Zrzut ekranu 4:
![](https://s3.dodajfote.pl/2017/09/23/reklamy2a8f28.png)

Zrzut ekranu 5:
![](https://s3.dodajfote.pl/2017/09/23/kontenery2d66e0.png)

Zrzut ekranu 6:
![](https://s3.dodajfote.pl/2017/09/23/kontenery33488e.png)

Zrzut ekranu 7:
![](https://s3.dodajfote.pl/2017/09/23/kontenery1e752b.png)

A tu wszystkie filtry kopiuj-wklej żeby przetestować działanie strony na nich:

```
! http://tygodniksiedlecki.com/t7366-to.nie.kurort..to.wiezienie.htm

!! >> idzie na PopupBlocker PLUS (PL):
! header u góry jeździ za scrollem
tygodniksiedlecki.com##.sticky.avoid-print-this.on.bootsnav.navbar-mobile.navbar-default.navbar:style(position: static!important;)

! subheader slide baner czarny wyjeżdżający z headera
tygodniksiedlecki.com##.avoid-print-this.bottom-bar:style(position: static!important;)
||tygodniksiedlecki.com/assets/mobile/js/ts.js$script,first-party

!! >> idzie na Fanboyz Cookiemonster:
! unbreak for cookiemonster, for top header slide menu
@@||tygodniksiedlecki.com/assets/mobile/cookiebar/jquery.cookiebar.js$script,first-party

!! >> idzie na POL: polskie filtry do Adblocka i uBlocka:
! reklama flash po środku
tygodniksiedlecki.com##body > .container > .post-wrapper.row > .col-xs-12.col-sm-12.co-md-8.col-lg-8 > .article > .article-wrapper > .avoid-print-this:nth-of-type(3)

! reklama środkowy tekst
tygodniksiedlecki.com##body > .wrapper > .container > .post-wrapper.row > .col-xs-12.col-sm-12.co-md-8.col-lg-8 > .article > .article-wrapper > .avoid-print-this:nth-of-type(3)

! reklama u góry nad headerem
! reklama u góry pod headerem
! reklama pod zdjęciem pod headerem
! resztki po reklamie pusty średni kontener po prawej
! resztki po reklamie pusty mały kontener na środku
! resztki po reklamie pusty mały kontener na dole 1
! resztki po reklamie pusty mały kontener na dole 2
! resztki po reklamie pusty duży kontener na dole 
! resztki po reklamie pusty wielki kontener na dole 1
! resztki po reklamie pusty wielki kontener na dole 2

! do wyboru dwa filtry
!tygodniksiedlecki.com###banner-top-top, .mb-5.row, #baner_glowna_polecamy, #baner_publicystyka1, #baner_dyzur1, #baner_prawa_dyzur1, #baner_glowna_dol1, #baner_lewy, #baner_prawa_aktualnosci, #baner_prawy1
tygodniksiedlecki.com###banner-top-top, .mb-5.row, div[id^="baner"]
```

**Comment by hawkeye116477** [comment]
@gomoku No i mamy problem, bo tego raczej nie możemy zablokować -> `||tygodniksiedlecki.com/assets/mobile/js/ts.js$script,first-party` , to jest najwyraźniej jakiś skrypt na urządzenia mobilne, by tam strona poprawnie się wyświetlała.

**Comment by hawkeye116477** [comment]
@gomoku A ten skrypt-> `||tygodniksiedlecki.com/assets/mobile/js/ts.js$script,first-party` , to po co on ma być blokowany? Ja nie widzę różnicy po zablokowaniu jego, nadal te czarne coś wyjeżdża.

**Comment by gomoku** [comment]
Masz funkcję edytuj post. :)

To jeden z dwóch skryptów, potrzebnych do usadzenia na dupie tego czarnego subheadera, którego jeśli nie usadzi się na dupie to będzie rozwijał się i zwijał spod górnego headera przy przewijaniu strony. alternatywny skrypt, który też usadza go na dupie to któryś jquery, ale pomyślałem, że blokowanie jquery wyrządziłoby większe szkody, no chyba, że nie?

**Comment by hawkeye116477** [comment]
@gomoku Ta, ok. Mi się nadal rozwija, ale tylko jak mam włączony sidebar, po wyłączeniu o dziwo jest ok. Także zaraz to dodam.

**Comment by blocker999** [comment]
@gomoku Skoro tak Ci wszystko pięknie działa to niemorzesz zrobić pulla a reszte osobiście przesłać do innych list?, z tego co wiem to już bana niemasz.

**Comment by gomoku** [comment]
To, że mi działa, to nie od razu znaczy, że wszystkim działa.

**Comment by blocker999** [comment]
@gomoku Dobra ale przed dodaniem to sprawdzimy a itak jak wiesz z wcześniejszyxh tematów że co przeglądarka to obyczaj wiec reszte do admina bo niedysponujemy taką wiedzą i sprzentem jak oni powinni. A wszystkimi się nieprzejmuj, bo jest ich niewielu a raczej niezaglądają na Twe strony a i zawsze można coś zmienić w Popupblocerze 
a @hawkeye116477 niejest detektywem ma też inne zajęcia ale może się myle, @hawkeye116477 co o tym wszystkim myślisz?

**Comment by hawkeye116477** [comment]
@blocker999  Tak zgadza się, mam też inne zajęcia. Ale to co miało trafić do Popup Blockera to już dodałem, więc raczej ten temat zamknięty. A to co powinno trafić do Macieja, to @gomoku to powinien u niego pisać, a nie tu robić śmietnik.

**Comment by gomoku** [comment]
Spoko, już poprawiłem, tak może być?

**Comment by gomoku** [comment]
Spoko, już poprawiłem, tak może być?

**Comment by gomoku** [comment]
> @hawkeye116477: A to co powinno trafić do Macieja, to @gomoku to powinien raczej u niego pisać, a nie tu robić śmietnik.

Rozumiem i zgadzam się z tobą, tylko w takim razie, dlaczego takiej samej uwagi nie zwróciłeś dla @HateAds tutaj: https://github.com/MajkiIT/polish-ads-filter/issues/3842#issuecomment-333090069

No chyba, że umieszczanie na liście czegoś co powinno iść do innej listy, różni się czymś od umieszczania w wątku czegoś co powinno iść do innego wątku? Tylko czym?

**Comment by hawkeye116477** [comment]
@gomoku Ale tamte repo należy do MajkiIT, ja tam nie jestem nawet collabolaratorem, więc do moich obowiązków tam nie należy zwracanie uwagi, że ktoś nie pisze w odpowiednim wątku/robi śmietnik.

**Comment by gomoku** [comment]
Rozumiem, rzeczywiście pomieszali mi się contributorzy z collaboratorami (widziałem cię tam jako contributor myląc z collaboratorem) więc sorry. Przy okazji dzięki za info, że na repo MajkiIT ktoś robi śmietnik.
