### ISSUE TITLE
policja.pl / policja.gov.pl

### ISSUE THREAD

**Issue by gomoku** [azet12/PopupBlocker#137]
Sorry, dopiero zorientowałem się, że powinienem był pisać w już istniejącym wątku: https://github.com/azet12/PopupBlocker/issues/22, natomiast ciekawostką jest to, że nie ja pierwszy ten wątek zduplikowałem, bo już kiedyś zduplikował go także @gwarser https://github.com/azet12/PopupBlocker/issues/25

1) Jebutny popup na wejściu: 
2) Social facebook przycisk po lewej jeździ ze scrollem, z którego po kliknięciu wyjeżdża baner

Można z pistoletu każdego po kolei z osobna:

`www.policja.pl,swietokrzyska.policja.gov.pl##[id^="popup-"]`

`www.policja.pl,statystyka.policja.pl,praca.policja.pl,www.prawo.policja.pl,www.info.policja.pl,www.zyjbezpiecznie.policja.pl,cbsp.policja.pl,slaska.policja.gov.pl,www.dlakierowcow.policja.pl,przetargi.policja.pl,brd.policja.pl,dlakierowcow.policja.pl###likebox`

lub granatem w tłum :)

`policja.pl,policja.gov.pl##[id^="popup-"], #likebox`

! brd.policja.pl/brd

![](https://s3.dodajfote.pl/2017/09/24/policja11ab95.png)

**Comment by blocker999** [comment]
@gomoku Popup dodany a social doda się do innej paczki

**Comment by gomoku** [comment]
To dlaczego dodałeś do tej?

**Comment by blocker999** [comment]
@gomoku Tak poprawie ale daj mi troche czasu a nie pytasz o wszystko.

**Comment by gomoku** [comment]
Sorry @blocker999, ale z twoja odpowiedź jest niejednoznaczna, więc zmuszasz mnie do dopytania:

> @blocker999: Tak poprawie 

Czyli co:
a) nie pomyliłeś się, tylko celowo dałeś tutaj, z zamiarem późniejszego przeniesienia
b) pomyliłeś się, i dzięki temu, że to zauważyłem, to poprawisz to
?

**Comment by blocker999** [comment]
@gomoku Chodzi Ci żeby to zamienić `policja.pl,policja.gov.pl##[id^="popup-"], #likebox` na `policja.pl,policja.gov.pl##[id^="popup-"]` ?

**Comment by gomoku** [comment]
Tak, bo sam pisałeś, że social do innej paczki, stąd moje pytanie.

**Comment by blocker999** [comment]
ok zaraz poprawie

**Comment by gomoku** [comment]
> @blocker999 @gomoku Tak poprawie ale daj mi troche czasu a nie pytasz o wszystko.

To ja pomogłem, bo zauważyłem pomyłkę, a w zamian słyszę jakieś fochy.

> @blocker999 a nie pytasz o wszystko.

Nie pytam, tak jakbym czegoś nie wiedział i komuś dupę zawracał co próbujesz mi imputować, lecz zgłaszam zauważone u kogoś błędy w formie pytania, a to jest różnica.

> @blocker999: o wszystko.

Czyli o co jeszcze niby wcześniej tyle pytałem?

**Comment by hawkeye116477** [comment]
Ten likebox już jest na liście Social.

**Comment by gwarser** [comment]
Ten _popup_ dalej się wyświetla `#krajowa_mapa_zagrozen` http://www.dolnoslaska.policja.gov.pl/pl/aktualnosci/wiadomosci/biezace_informacje/oswiadczenie_w_sprawie_zatrzymania_kobiety_w_zwiazku_z_podejrzeniem_popelnienia_przestepstwa

**Comment by gomoku** [comment]
Zgadza się, trzeba zmienić 
`policja.pl,policja.gov.pl##[id^="popup-"]` na 
`policja.pl,policja.gov.pl##[id^="popup-"], #krajowa_mapa_zagrozen`

**Comment by gwarser** [comment]
@blocker999

**Comment by blocker999** [comment]
@gomoku Poprawione, @gwarser pasuje?
