### ISSUE TITLE
dorzeczy.pl

### ISSUE THREAD

**Issue by gomoku** [azet12/PopupBlocker#139]
A więc do rzeczy :) :

Górny header jeździ ze scrollem (zrzut ekranu 1) na:
! https://dorzeczy.pl/
! https://dorzeczy.pl/kraj/38803/Dyrektor-aresztu-na-Bialolece-odwolany.html
! https://tygodnik.dorzeczy.pl/
! https://bohaterowie.dorzeczy.pl/
! https://superhistoria.pl/
! https://centkiewicz.dorzeczy.pl/ + kilkadziesiąt kolejnych stron z nazwiskami

`dorzeczy.pl,superhistoria.pl###header:style(position: static!important;)`
`dorzeczy.pl,superhistoria.pl###content:style(padding-top: 0px!important)`

i te filtry generalnie śmigają, z tym, że np. tu:
https://dorzeczy.pl/kraj/38803/Dyrektor-aresztu-na-Bialolece-odwolany.html
jakiś guzik odpada, bo znowu spodnie się prują (zrzut ekranu 2)

Tu czysto:
! http://prenumerata.dorzeczy.pl/cennik/
! http://ewydanie.dorzeczy.pl

A tu przy okazji:  jeden z filtrów na  Adblock & uBlock polish cookies filters uwala w całości https://e.dorzeczy.pl/ >> https://github.com/MajkiIT/polish-ads-filter/issues/3782

Zrzut ekranu 1:
![](https://s3.dodajfote.pl/2017/09/24/areszt_headerdb0f3.png)

Zrzut ekranu 2:
![](https://s3.dodajfote.pl/2017/09/24/areszt279616.png)

**Comment by blocker999** [comment]
@gomoku ze spodniami to do krawca bo guzikami się niezajmujemy

**Comment by gomoku** [comment]
Tzn do admina strony czy do mnie?

**Comment by blocker999** [comment]
@gomoku Z guzikiem do kogo chcesz byle nie do PopupBlockera.

**Comment by gomoku** [comment]
Ale dlaczego? Bo nie rozumiem, zgłosiłem filtry do strony (tak jak zgłaszałem w każdym innym wątku) które ogólnie działają, ale jest jeden defekt, z którym nie mogę sobie poradzić, więc tak jak w każdym innym wątku pomagaliście, to i tu powinniście zdaje się pomóc? Bo jak do tej pory pomagaliście, a teraz co? Przecież to lista jest tworzona przez wszystkich dla wszystkich, i powinna być współpraca i wzajemna pomoc, tak jak do tej pory była, czy coś się w tej kwestii zmieniło? Czy od teraz każdy sobie rzepkę skrobie i nikt nikomu nie pomaga w filtrach? A może w ogóle źle zrozumiałem?

**Comment by blocker999** [comment]
@gomoku Jak najbardziej jestem za pomocą ale nie poprawianiu stron poza oczywiście scrollującym menu, jak widzisz jest nas dwoje czasami jestem sam no i Ty w takim razie gdzie te tłumy wolontariuszy a może je dopiero sprowadzisz?

**Comment by gomoku** [comment]
> @blocker999: @gomoku ze spodniami to do krawca bo guzikami się niezajmujemy
> @blocker999: @gomoku Z guzikiem do kogo chcesz byle nie do PopupBlockera.

A czy ja komuś z PopupBlockera kazałem na siłę to naprawiać lub wołałem o pomoc? Tylko poinformowałem, że jest defekt, przecież tak lepiej, niż gdybym nie poinformował, i jeśli ktoś będzie chciał to się tym defektem zajmie, jeśli ktoś nie chce to niech się nie zajmuje, więc po co te teksty typu "z tym do krawca"? Zresztą przecież zawsze było tak, że każdy pomagał każdemu, coś się zmieniło?

**Comment by blocker999** [comment]
@gomoku  Dobra sprawdze to tylko napisz konkretnie jaka przeglądarka i jakie filtry bo być może to efek uboczny jakiejś paczki.

**Comment by gomoku** [comment]
Na tych samych listach filtrów co tu #135 (comment) z tym, że dodatkowo mam Fanboyz Cookiemonster włączone, a ten defekt jest tylko na FF, na Operze go nie ma.

**Comment by blocker999** [comment]
@gomoku zaraz dorwiemy winowajce bo prawdopodobnie to kawałek headeru, zaktualizuj filtry i sprawdź na FF oraz napisz czy dalej to jest

**Comment by gomoku** [comment]
Ja edytowałem szybko swój komentarz, więc może nie zauważyłeś, ale ja tego defektu już nie mam.

**Comment by blocker999** [comment]
@gomoku czyli temat uważam za zamknięty, a Ty szukaj kolejnych stron, ok ?

**Comment by gomoku** [comment]
Ok.
