### ISSUE TITLE
wprost.pl

### ISSUE THREAD

**Issue by gomoku** [azet12/PopupBlocker#141]
Ten sam pojedyńczy header jeździ ze scrollem na kilku stronach, w zależności od strony różni się wyglądem/kolorem:
! https://www.wprost.pl/kraj/10071157/Dwa-samobojstwa-w-ciagu-8-dni-w-areszcie-sledczym-Warszawa-Bialoleka-Sluzba-Wiezienna-przerywa-milczenie.html (zrzut ekranu 1)
! http://innowatory.wprost.pl/ (zrzut ekranu 3)
! http://zdrowie.wprost.pl/ (zrzut ekranu 4)
! http://rankingi.wprost.pl/ (zrzut ekranu 5)
! http://czlowiekroku.wprost.pl/ (zrzut ekranu 6)
! http://ludzie.wprost.pl/ (zrzut ekranu 7)
! http://orly.wprost.pl/ (zrzut ekranu 8)

Z pistoletu: `www.wprost.pl,innowatory.wprost.pl,zdrowie.wprost.pl,rankingi.wprost.pl,czlowiekroku.wprost.pl,ludzie.wprost.pl,orly.wprost.pl###header:style(position: absolute!important;)` 
lub granat: `wprost.pl###header:style(position: absolute!important;)`

! https://www.wprost.pl/ (zrzut ekranu 2)
Na głównej podwójny czerwony header jeździ ze scrollem (zrzut ekranu2):
Na górny pasek ten sam filtr co wyżej, ale nie wiem jaki filtr na drugi pasek ten dolny bo on ciągle wyjeżdża i wjeżdża, bo to zdaje się jakiś js tak nim steruje.

! tu czysto:
http://kisiel.wprost.pl/
http://prenumerata.wprost.pl/
http://www.nieruchomosci.wprost.pl/
https://e.wprost.pl/ 
http://ewydanie.wprost.pl

A tu przy okazji:  jeden z filtrów na  Adblock & uBlock polish cookies filters uwala w całości https://e.wprost.pl/ >> https://github.com/MajkiIT/polish-ads-filter/issues/3782

Zrzut ekranu 1:
![](https://s3.dodajfote.pl/2017/09/24/headerwprost138456.png)

Zrzut ekranu 2:
![](https://s3.dodajfote.pl/2017/09/24/headerwprost299a38.png)

Zrzut ekranu 3:
![](https://s3.dodajfote.pl/2017/09/24/wprost_innowatory50469.png)

Zrzut ekranu 4:
![](https://s3.dodajfote.pl/2017/09/24/wprost_zdrowie71b38.png)

Zrzut ekranu 5:
![](https://s3.dodajfote.pl/2017/09/24/wprost_rankingi99f2e.png)

Zrzut ekranu 6:
![](https://s3.dodajfote.pl/2017/09/24/wprost_czlowiekrokudd704.png)

Zrzut ekranu 7:
![](https://s3.dodajfote.pl/2017/09/24/wprost_ludzie560e1.png)

Zrzut ekranu 8:
![](https://s3.dodajfote.pl/2017/09/24/wprost_orlybb52b.png)

**Comment by hawkeye116477** [comment]
@gomoku Ten dolny pasek to raczej do wywalenia. No i mamy problem, bo u mnie po scrollowaniu, zauważyłem, że header na głównej zwija się w ten mniejszy i widać, że przyciski podskakują, ale to pewnie z tego powodu, ale nie wiem czy da się coś z tym zrobić. 
Na razie dodam te 2:
```
wprost.pl###element-header
wprost.pl###header:style(position: absolute!important;)
```

**Comment by gwarser** [comment]
Na skakanie `www.wprost.pl##script:inject(addEventListener-defuser.js, scroll)` ale to jest do jQuery podpięte i może więcej psuć.

**Comment by hawkeye116477** [comment]
@gwarser Ta, niestety psuje to wyświetlanie się niektórych obrazków na głównej.
