### ISSUE TITLE
[Grupa Agora] gazeta.pl...

### ISSUE THREAD

**Issue by gomoku** [azet12/PopupBlocker#144]
https://pl.wikipedia.org/wiki/Agora_(przedsi%C4%99biorstwo)

! Usadzenie Grupy Agora

! usadzenie scrollujących headerów:
**_1__**
! czarne headery - na 22 stronach (przykładowy header -  zrzut ekranu 1):
```
wiadomosci.gazeta.pl,kobieta.gazeta.pl,zdrowie.gazeta.pl,podroze.gazeta.pl,www.edziecko.pl,ugotuj.to,weekend.gazeta.pl,polskabiega.sport.pl,www.sport.pl,myfitness.pl,www.junior.sport.pl,www.plotek.pl,deser.gazeta.pl,moto.pl,ladnydom.pl,www.logo24.pl,magazyn-kuchnia.pl,www.swiatmotocykli.pl,rockradio.tuba.pl,zloteprzeboje.tuba.pl,radiopogoda.tuba.pl##.hpFeed.mod_hat2014.mod:style(position: absolute!important;)
www.komunikaty.pl###rwdHat:style(position: absolute!important;)
! na głównej www.gazeta.pl postarali się żeby nie dało się go usadzić, ten filtr niżej nie daje rady
! www.gazeta.pl##.hat_dark.mod_hat.page_top > .container-fluid:style(position: static!important;)
```
**_2__**
! szare headery + 1 granatowy - na 5 stronach (przykładowe headery -  zrzuty ekranu 2, 3, 4):
```
wyborcza.pl,wyborcza.biz,www.wysokieobcasy.pl###wyborczaHat:style(position: absolute!important;)
www.goldenline.pl##.main-header.symfony:style(position: absolute!important;)
kulturalnysklep.pl##.detached.topnav-categories.row:style(position: absolute!important;)
```
**_3__**
! białe headery  - na 10 stronach (przykładowe headery -  zrzuty ekranu 5,6,7,8,9,10,11):
```
www.trader.pl###main-header:style(position: absolute!important;)
yieldbird.com###header:style(position: absolute!important;)
www.domiporta.pl##.fixed.page-header:style(position: absolute!important;)
reklama.gazeta.pl###menu:style(position: absolute!important;)
reklamaczasopisma.agora.pl##.fixed.top:style(position: absolute!important;)
! problem, po usadzeniu robi się biały (www.inforadio.de)
! www.inforadio.de###header:style(position: absolute!important;)
! częściowo usadzone, ale coś lata (ladnydom.pl,avanti24.pl,www.bryla.pl)
ladnydom.pl,avanti24.pl,www.bryla.pl###page-top:style(position: static!important;)
! http://www.autotrader.pl/samochody-osobowe/sprzedam-opel-vivaro-diesel/1000667249
! usunięcie zdublowanych scrollujących headerów
www.autotrader.pl##.is_stuck.basic-info-heading--sticky
www.autotrader.pl##.is_stuck.section--navbar.section
! tu coś lata i trudno usadzić
www.autotrader.pl##.section--navbar.section:style(position: absolute!important;)
```
**_4__**
! po prawej na dole coś się uczepiło do scrolla
`polskabiega.sport.pl,www.junior.sport.pl###embed_iframe`
**_5__**
! widżet typu "nastęny artykuł" po prawej na dole czepia się scrolla (zrzut ekranu 13):
! http://gazetapraca.pl/ogl/2700805/pakowacz+produkt%C3%B3w+spo%C5%BCywczych?q=4410#Rheda%20%E2%80%93%20Wiedenbr%C3%BCck
`gazetapraca.pl##.js-offer-suggested-offer-btn.next-offer-box`
**_6__**
! jebutny popup na wejściu (zrzut ekranu 14):
`zdrowie.gazeta.pl###bottom_wrap`
**_7__**
! header scrollujący biały >> patrz wyżej headery białe  (zrzut ekranu 15):
**_8__**
! popup na wejściu (zrzut ekranu 15):
`yieldbird.com##.newsletter-modal`
`yieldbird.com##.overlay-layer`
**_9__**
! newsletter po prawej na dole (zrzut ekranu 15):
`yieldbird.com##.hidden-widget.float-widget`
**_10__**
! newsletter po prawej czepia się scrolla (zrzut ekranu 16):
`www.helios.pl##.openSuggestionFormButton`
**_11__**
! back to top button prawa dol
`ams.com.pl###back2top` (zrzut ekranu 17):
`outdoortrack.pl##.to-top-container` (zrzut ekranu 18):
! SOCIAL:
**_12__**
! social button like facebook po lewej jeździ ze scrollem >> https://github.com/MajkiIT/polish-ads-filter/issues/3792
**_13__**
! tu czysto:
! http://firmaprzyjaznamamie.pl
! https://oauth.gazeta.pl
! http://www.tokfm.pl
! http://gazetapraca.pl
! http://www.kupsprzedaj.pl
! http://optimizers.pl
! http://localpower.pl
! http://pbi.org.pl
! http://stopklatka-sa.pl
! https://hash.fm
! http://greencontent.pl
! http://www.adpol.pl
! http://www.next-film.pl

Zrzut ekranu 1:
![](https://s3.dodajfote.pl/2017/09/26/gazeta_czarny_headeraac56.png)

Zrzut ekranu 2:
![](https://s3.dodajfote.pl/2017/09/26/gazeta_szary_header4ad2c.png)

Zrzut ekranu 3:
![](https://s3.dodajfote.pl/2017/09/26/gazeta_goldenfile_header_szaryaeef0.png)

Zrzut ekranu 4:
![](https://s3.dodajfote.pl/2017/09/26/gazeta_prenumerata_header_granatowy99711.png)

Zrzut ekranu 5:
![](https://s3.dodajfote.pl/2017/09/26/gazeta_bialy_headere9baf.png)

Zrzut ekranu 6:
![](https://s3.dodajfote.pl/2017/09/26/gazeta_agora_trader_header_bialy87852.png)

Zrzut ekranu 7:
![](https://s3.dodajfote.pl/2017/09/26/gazeta_domiporta_header_bialy5306e.png)

Zrzut ekranu 8:
![](https://s3.dodajfote.pl/2017/09/26/gazeta_inforadio_header_bialycaeb7.png)

Zrzut ekranu 9:
![](https://s3.dodajfote.pl/2017/09/26/gazeta_yieldbird_header_bialyb0dec.png)

Zrzut e kranu 10:
![](https://s3.dodajfote.pl/2017/09/26/gazeta_czaspoisma_headerbialy978b4.png)

Zrzut ekranu 12:
![](https://s3.dodajfote.pl/2017/09/26/gazeta_autotrader_headere965f.png)

Zrzut ekranu 13:
![](https://s3.dodajfote.pl/2017/09/26/gazeta_praca_nastepny_artykul04bc3.png)

Zrzut ekranu 14:
![](https://s3.dodajfote.pl/2017/09/26/gazeta_zdrowie_popup588d0.png)

Zrzut ekranu 15:
![](https://s3.dodajfote.pl/2017/09/26/gazeta_yieldbird_header_popup_newsletterb676f.png)

Zrzut ekranu 16:
![](https://s3.dodajfote.pl/2017/09/26/gazeta_helios_newsletter_po_prawejbc358.png)

Zrzut ekranu 17:
![](https://s3.dodajfote.pl/2017/09/26/gazeta_ams_back_to_top5eecb.png)

Zrzut ekranu 18:
![](https://s3.dodajfote.pl/2017/09/26/gazeta_outdoortrack_back_to_top1c82f.png)

Kopiuj & wklej bez komentarzy:
```
!
!
! Agora
ams.com.pl###back2top
gazetapraca.pl##.js-offer-suggested-offer-btn.next-offer-box
kulturalnysklep.pl##.detached.topnav-categories.row:style(position: absolute!important;)
ladnydom.pl,avanti24.pl,www.bryla.pl###page-top:style(position: static!important;)
outdoortrack.pl##.to-top-container
polskabiega.sport.pl,www.junior.sport.pl###embed_iframe
reklama.gazeta.pl###menu:style(position: absolute!important;)
reklamaczasopisma.agora.pl##.fixed.top:style(position: absolute!important;)
wiadomosci.gazeta.pl,kobieta.gazeta.pl,zdrowie.gazeta.pl,podroze.gazeta.pl,www.edziecko.pl,ugotuj.to,weekend.gazeta.pl,polskabiega.sport.pl,www.sport.pl,myfitness.pl,www.junior.sport.pl,www.plotek.pl,deser.gazeta.pl,moto.pl,ladnydom.pl,www.logo24.pl,magazyn-kuchnia.pl,www.swiatmotocykli.pl,rockradio.tuba.pl,zloteprzeboje.tuba.pl,radiopogoda.tuba.pl##.hpFeed.mod_hat2014.mod:style(position: absolute!important;)
www.autotrader.pl##.is_stuck.basic-info-heading--sticky
www.autotrader.pl##.is_stuck.section--navbar.section
www.autotrader.pl##.section--navbar.section:style(position: absolute!important;)
www.domiporta.pl##.fixed.page-header:style(position: absolute!important;)
www.goldenline.pl##.main-header.symfony:style(position: absolute!important;)
www.helios.pl##.openSuggestionFormButton
www.komunikaty.pl###rwdHat:style(position: absolute!important;)
www.trader.pl###main-header:style(position: absolute!important;)
wyborcza.pl,wyborcza.biz,www.wysokieobcasy.pl###wyborczaHat:style(position: absolute!important;)
yieldbird.com###header:style(position: absolute!important;)
yieldbird.com##.hidden-widget.float-widget
yieldbird.com##.newsletter-modal
yieldbird.com##.overlay-layer
zdrowie.gazeta.pl###bottom_wrap
```

**Comment by gomoku** [comment]
Ale w złe miejsce wkleiłeś, bo to jest jako grupa, więc trzeba nad tym:
```
!
!
! Movable elements
```
A przy okazji gdy będziesz przenosił, to skopiuj z mojego komentarza, bo posortowałem alfabetycznie.

**Comment by blocker999** [comment]
@gomoku Poprawione, może tak być?

**Comment by gomoku** [comment]
Generalnie jest w odpowiednim miejscu, ale są drobne braki, bo

Zamiast
```
!
Agora
```
Tak
```
!
!
! Agora
```
A zamiast
```
!
! Movable elements
! 
```

Tak
```
!
!
! Movable elements
```

**Comment by hawkeye116477** [comment]
@gomoku Poprawione 😄 .

**Comment by gomoku** [comment]
Dlaczego ten wątek został zamknięty przy trzech nie rozwiązanych problemach, kiedy np. ten https://github.com/azet12/PopupBlocker/issues/123 jest otwarty + "potrzebna pomoc", przy 1 nierozwiązanym problemie.

**Comment by hawkeye116477** [comment]
@gomoku To @blocker999 zamknął, ale tak właściwie to jakie tu jeszcze są problemy, o które punkty chodzi?

**Comment by gomoku** [comment]
> @hawkeye116477: To @blocker999 zamknął,

Wiem, że blocker999 zamknął, ale ty nic z tym nie zrobiłeś, nie sprawdziłeś, nie zapytałeś go o to, nie poprawiłeś go, nie otworzyłeś + "potrzebna pomoc", więc jesteś współwinny i  dlatego zwróciłem się do was obu, więc nie pal głupa.

> @hawkeye116477: ale tak właściwie to jakie tu jeszcze są problemy, o które punkty chodzi?

Znowu palisz głupa, więc odpowiem ci pytaniem na pytanie: a jakie są problemy tam https://github.com/azet12/PopupBlocker/issues/123? Tzn wiesz jakie problemy są tam, a jednocześnie nie wiesz jakie są tu, zadziwiające.

**Comment by hawkeye116477** [comment]
Ok, faktycznie są jeszcze jakieś problemy, nie zauważyłem. Ale to trzeba normalnie powiedzieć o co chodzi, a nie od razu robić awanturę....

**Comment by gomoku** [comment]
@hawkeye116477: Jasne, czyli ja mam siedzieć 24h na dobę

Nie 24 godziny na dobę, tylko gdy zajrzysz do wątku z własnej woli, tak jak do tego właśnie zajrzałeś 
https://github.com/azet12/PopupBlocker/issues/144#issuecomment-332318869

@hawkeye116477: i pilnować @blocker999.

Siebie, bo nie zauważyłeś tak samo jak on, ale tylko na niego zwalasz winę.

**Comment by hawkeye116477** [comment]
Ok, masz rację, sorry, to jest też moja wina.

**Comment by gomoku** [comment]
Z ciekawości zapytam, margines ci wyskoczył?

**Comment by hawkeye116477** [comment]
@gomoku Tak, zgadłeś.

**Comment by gwarser** [comment]
`gazeta.pl##script:inject(abort-on-property-read.js, gazeta_pl.HP.Hat)` całkiem znika czarny pasek. Trzeba by go włączyć ustawiając to co robi `.hat_dark`. No chyba, że psuje.

**Comment by hawkeye116477** [comment]
@gomoku Czarny pasek miał zniknąć, ale to prowadzi do defektu takiego, że wyszukiwarka przestaje działać. Znalazłem lepsze rozwiązanie -> `www.gazeta.pl##.mod_hat.page_top.hat_dark`.

**Comment by gwarser** [comment]
Jak ma znikać, a nie tylko zostać przypięty to może `www.gazeta.pl##.hat_dark.page_top > .container-fluid:style(position: static!important;)`? I tak wszystko z tego paska jest powtórzone w menu obok logo.
