### ISSUE TITLE
www.igbbaltica.pl

### ISSUE THREAD

**Issue by gomoku** [azet12/PopupBlocker#146]
Header do usadzenia bo jeździ ze scrollem:

![](https://s3.dodajfote.pl/2017/09/27/baltica_header3cfb3.png)

(A ten e-prawnik.pl to na razie zignorujcie bo okazało się, że to część Grupy WP, i to będzie później usadzone jako Grupa WP)

**Comment by hawkeye116477** [comment]
@gomoku No i tutaj mamy problem, bo jeśli spróbuję zrobić `igbbaltica.pl###header:style(position: static!important;)` to header frunie do boku, a jeśli tak -> `igbbaltica.pl##.fixed_header` to znowu po scrollowaniu włącza tryb ninja. Więc nie wiem który sposób lepszy, a może lepiej poczekać aż pojawi się ekspert @F4z.

**Comment by gwarser** [comment]
`igbbaltica.pl##script:inject(abort-current-inline-script.js, $, fixed_header)`

**Comment by hawkeye116477** [comment]
@gwarser Działa, dzięki.
