### ISSUE TITLE
Tymczasowe zmiany

### ISSUE THREAD

**Issue by azet12** [azet12/PopupBlocker#15]
@blocker999 będzie niedostępny przez kilka następnych dni. Wprowadziłem trochę zmian i opisuję je tutaj aby wszystko było jasne

1. Reguła `pl##.carousel` powoduje błędy na niektórych stronach (np. allegro.pl) więc ją usunąłem (sądzę, że jest zbędna).

2. @F4z mogę prosić o pomoc z https://github.com/azet12/PopupBlocker/issues/13?

3. (https://github.com/azet12/PopupBlocker/issues/14) reguła `pl##.c1` blokuje niektóre artykuły na polska-zbrojna.pl, tak więc zamieniłem na `~polska-zbrojna.pl,pl##.c1`. Zastanawiam się, czy ta reguła nie jest zbyt ogólna i czy nie lepiej byłoby ją usunąć.

4. Reguła `pl##.center` czyściła stronę logowania do wykop.pl, więc zmieniłem `~wykop.pl,pl##.center`

5. Podczas próby dodania blokera do listy filtrów w ABP wyskakuje błąd:
![Błąd ABP](https://cloud.githubusercontent.com/assets/18347726/21502241/c2f73df0-cc4e-11e6-94e7-6bbc0593357b.PNG) 
Czy tylko u mnie tak jest?

**Comment by gwarser** [comment]
Co do błędu ABP, to pewnie te filtry psują

    aligoo.pl##html.remodal-is-locked:style(overflow: auto !important;) 
    pl###PopupSignupForm_0 > .mc-modal > .mc-layout__modalContent >
    pl##html.remodal-is-locked:style(overflow: auto !important;)

**Comment by F4z** [comment]
@azet12 odnośnie tego drugiego punktu, to tam @gwarser  już podał dobrą regułę dla uBlocka.
W przypadku Adblocka raczej nie da się nic zrobić.

Odnośnie punktu czwartego.
Moim zdaniem reguła `pl##.center` jest zbyt ogólna.
Na stronie `http://www.benchmark.pl/` za dużo ukrywa.
![image](https://cloud.githubusercontent.com/assets/11742596/21505898/f20fa326-cc6b-11e6-8544-89635c17b0e4.png)

Tutaj - `http://pclab.pl/` - ukrywa całkowicie stopkę, a oprócz tego, reguła `pl##.special` ukrywa sekcję z artykułami.

Jeśli chodzi o punkt piąty, to też tak mam.
Jak dodasz `[Adblock Plus 2.0]` na samym początku listy, to powinno normalnie działać.
![image](https://cloud.githubusercontent.com/assets/11742596/21506090/c419ee5c-cc6d-11e6-9076-a6ae78b5b4f3.png)

**Comment by gwarser** [comment]
Czyli, że ta co podałem w https://github.com/azet12/PopupBlocker/issues/13 też jest tylko do Ublocka

**Comment by azet12** [comment]
Kompletnie zapomniałem o `[Adblock Plus 2.0]`. Dzięki

**Reguły usunięte:**
`pl##.center` (https://github.com/azet12/PopupBlocker/issues/15#issuecomment-269371285, https://github.com/azet12/PopupBlocker/issues/16, https://github.com/azet12/PopupBlocker/issues/17)
`pl##.up` (https://github.com/azet12/PopupBlocker/issues/16)
`pl##html.remodal-is-locked:style(overflow: auto !important;)` (https://github.com/azet12/PopupBlocker/issues/15#issuecomment-269366635)
`aligoo.pl##html.remodal-is-locked:style(overflow: auto !important;)` (jw.)
`pl###PopupSignupForm_0 > .mc-modal > .mc-layout__modalContent >` (jw.)

**Zmiany:**
`pl###colorbox` na `~purepc.pl,pl###colorbox` (https://github.com/azet12/PopupBlocker/issues/17)
`pl###cboxOverlay` na `~purepc.pl,pl###cboxOverlay` (jw.)

Chyba nic nie ominąłem?
Jak @blocker999 wróci, to będzie mógł się z tym pobawić, nie chcę tutaj mocno mieszać.

**Comment by blocker999** [comment]
OK, jestem i postaram się to ewentualnie poprawić ale itak uważam że @azet12  wprowadził wystarczające zmiany lecz pomimo to czekam na wasze dalsze uwagi i przy okazji życze szczęśliwego nowego roku.

**Comment by blocker999** [comment]
@gwarser Wszystko?

**Comment by gwarser** [comment]
Jak dla mnie, jest OK
