### ISSUE TITLE
kotrak.pl

### ISSUE THREAD

**Issue by gomoku** [azet12/PopupBlocker#164]
! usunięcie czat-widżetu 1 https://kotrak.pl/ - zrzut ekranu 1
! usunięcie czat-widżetu 2 https://kotrak.pl/oferta/comarch-erp-2-0/comarch-erp-xl/aplikacje-dedykowane/ - zrzut ekranu 2

`kotrak.pl##[title="chat widget"], .kotrak_infobox_button`

Zrzut ekranu 1:
![](https://s3.dodajfote.pl/2017/09/29/kotrak_czat_widzet571da.png)

Zrzut ekranu 2:
![](https://s3.dodajfote.pl/2017/09/29/kotrak_widzet24706d.png)

**Comment by hawkeye116477** [comment]
Do czatu mam lepszą regułę -> ||embed.tawk.to^$script,domain=kotrak.pl 😄 .
