### ISSUE TITLE
www.purepc.pl

### ISSUE THREAD

**Issue by gomoku** [azet12/PopupBlocker#165]
! usadzenie headera + wyrównanie
! usunięcie scroll to top z headera

`www.purepc.pl##.navbox:style(position: static!important; margin-left: 4px!important;)`
`www.purepc.pl##.mtotop`

![](https://s3.dodajfote.pl/2017/09/29/purepc_header_to_top5c206.png)

**Comment by hawkeye116477** [comment]
Tak będzie lepiej, bo 5 to tylko przesunie za dużo w lewo `www.purepc.pl##.navbox:style(position: static!important; margin-left: 116px!important;)` 😛 .

**Comment by gomoku** [comment]
> @hawkeye116477: Tak będzie lepiej, bo 5 to tylko przesunie za dużo w lewo `www.purepc.pl##.navbox:style(position: static!important; margin-left: 116px!important;)` 😛 .

Ale tylko u ciebie, bo u mnie będzie gorzej:

![](https://s3.dodajfote.pl/2017/09/29/purepc_11643511.png)

**Comment by hawkeye116477** [comment]
@gomoku Tak wygląda ![screenshot_20170929_203901](https://user-images.githubusercontent.com/19818572/31030631-5735eac6-a556-11e7-9196-51b41030b0ce.png)
W takim razie tak już powinno być ok -> `purepc.pl##.navbox:style(position: static!important; margin-left: auto!important;)`, u każdego ustawi się tyle ile ma być i problem z głowy.

**Comment by gomoku** [comment]
Potwierdzam, teraz jest ok.
