### ISSUE TITLE
[Grupa Bauer Media] interia.pl...

### ISSUE THREAD

**Issue by gomoku** [azet12/PopupBlocker#168]
!! Usadzenie Grupy Bauer Media

```
! usadzenie szarych headerów znajdujących się na 30 stronach - przykładowe zrzuty ekranu 1,2:
www.interia.pl##[id^="pasek_"]:style(position: absolute!important;)
swiatseriali.interia.pl,pogoda.interia.pl,lotto.interia.pl,film.interia.pl,programtv.interia.pl,encyklopedia.interia.pl,fakty.interia.pl,biznes.interia.pl,mojeinwestycje.interia.pl,praca.interia.pl,sport.interia.pl,motoryzacja.interia.pl,nowahistoria.interia.pl,nt.interia.pl,mobtech.interia.pl,gry.interia.pl,kobieta.interia.pl,mamdziecko.interia.pl,on.interia.pl,muzyka.interia.pl,forum.interia.pl,ding.interia.pl,kartki.interia.pl,dzikikraj.interia.pl,zkarnego.interia.pl,wideo.interia.pl,funduszeue.interia.pl,raportdrogowy.interia.pl,www.interia.pl##.account:style(position: absolute!important;)
swiatseriali.interia.pl,pogoda.interia.pl,lotto.interia.pl,film.interia.pl,programtv.interia.pl,encyklopedia.interia.pl,fakty.interia.pl,biznes.interia.pl,mojeinwestycje.interia.pl,praca.interia.pl,sport.interia.pl,motoryzacja.interia.pl,nowahistoria.interia.pl,nt.interia.pl,mobtech.interia.pl,gry.interia.pl,kobieta.interia.pl,mamdziecko.interia.pl,on.interia.pl,muzyka.interia.pl,forum.interia.pl,ding.interia.pl,kartki.interia.pl,dzikikraj.interia.pl,zkarnego.interia.pl,wideo.interia.pl,funduszeue.interia.pl,raportdrogowy.interia.pl##.portal-bar:style(position: absolute!important;)
! tu problem na tipy.interia.pl bo po usadzeniu robi się dziwny "margines" który najeżdża na body
! tipy.interia.pl##.hidden-xs.tbar:style(position: absolute!important;)
! problem rozwiązany dzięki @hawkeye116477 >> https://github.com/azet12/PopupBlocker/issues/168#issuecomment-333389637
tipy.interia.pl##.tbar:style(position: absolute!important; top: -40px!important;)
ebrokerpartner.pl###top-page:style(position: absolute!important;)

! usadzenie białych headerów znajdujących się na 19 stronach - przykładowe zrzuty ekranu 3,4,5,6,7:
smaker.pl,www.styl.pl,www.pcformat.pl,www.cdaction.pl,www.grazia.pl,uroda.swiatkobiety.pl,www.swiatkobiety.pl,www.pomponik.pl,teksciory.interia.pl,deccoria.pl,porady.swiatkobiety.pl,przepisy.swiatkobiety.pl,finanse.swiatkobiety.pl,podroze.swiatkobiety.pl,rodzina.swiatkobiety.pl,interia.tv,magazynauto.interia.pl##.topbar:style(position: absolute!important;)
cyfrowypolsat.interia.pl##.fixed.doNotResize.v7header:style(position: relative!important;)
teletydzien.interia.pl###channels-wrapper:style(position: absolute!important; top: auto!important;)
pogoda.interia.pl##.weather-forecast-longterm-list-head-entry:style(position: static!important;)
pogoda.interia.pl##.weather-head-entry:style(position: static!important;)
grupaebroker.pl##body > .skrollable:style(position: absolute!important;)

! usunięty popup, ale trzeba jeszcze naprawić scroll - zrzut ekranu 8:
! ebrokerpartner.pl##.overlay
! problem rozwiązany dzięki @hawkeye116477 >> https://github.com/azet12/PopupBlocker/issues/168#issuecomment-333389637
||ebrokerpartner.pl/js/frontend/modules/popup.js$script

! usadzenie headera niebieskiego - zrzut ekranu 9:
opinie24.pl##.fixed.mobile:style(position: static!important;)

! usadzenie headera czarnego - zrzut ekranu 10:
! podciągnięcie ciała w górę
www.rmfclassic.pl##.header:style(position: absolute!important;)
www.rmfclassic.pl##html > body:style(padding: 0px!important;)

! usadzenie headera czarnego - zrzut ekranu 11
! usunięcie strzałki powrót do góry - zrzut  ekranu 11
www.gruparmf.pl##.chaser:style(position: absolute!important;)
www.gruparmf.pl###totop

! usadzenie headera zielono-czarnego  - zrzut ekranu 12
! usadzenie panelu banerowego po prawej, który jeździ ze scrollem - zrzut ekranu 12
www.bryk.pl##.header-wrapper:style(position: static!important;)
www.bryk.pl##.sticky.col-wrapper:style(position: relative!important;)

! usadzenie headera czarno-białego  - zrzut ekranu 13
! usadzenie procenta na headerze - zrzut ekranu 13
! usadzenie logo na headerze  - zrzut ekranu 13
! usunięcie dymka
! usunięcie przewiń do góry - zrzut ekranu 16
! przy okazji usunięcie widżetu social także idzie na social >> https://github.com/MajkiIT/polish-ads-filter/issues/3876
www.promocyjni.pl###main-nav:style(position: absolute!important; top: 0px!important;)
www.promocyjni.pl##.rebate-codes-main.rebate-toggling:style(top: 20px!important;)
www.promocyjni.pl##.show-main-logo:style(display: block!important;)
www.promocyjni.pl##.show-mini-logo:style(display: none!important;)
www.promocyjni.pl##.new-dymek-holder
www.promocyjni.pl##.scroll-up, .socials-float

! usadzenie headerów - zrzut ekranu 17
programtv.interia.pl##.slider-wrapper-bar1:style(top: auto!important;)
programtv.interia.pl##.time-list:style(top: auto!important;)
programtv.interia.pl##.hour-select:style(top: auto!important;)

! usadzenie panelu po prawej jeżdżącego ze scrollem, zrzuty ekranu 18,19,20,:
dzikikraj.interia.pl###RankingTopicsUsers:style(position: absolute!important;)
forum.interia.pl##.f3-sidebar-container:style(position: static!important;)
deccoria.pl##.sidebar-container:style(position: static!important;)
www.maxmodels.pl##.right:style(position: static!important;)

! usunięcie banera typu następny artykuł na dole, który wyjeżdża/wjeżdża do/z garażu po przewinięciu strony w dół
! http://swiatseriali.interia.pl/newsy/seriale/m-jak-milosc-383/news-m-jak-milosc-franek-wyjedzie-w-bieszczady,nId,2446732
! zrzuty ekranu 22,23
swiatseriali.interia.pl##.is-fixed.recommend-flybar-block
www.maxmodels.pl###moreArticles

! usunięcie widżetu typu następny artykuł - zrzut ekranu 24:
! http://uroda.swiatkobiety.pl/fryzury/news-regeneracja-wlosow,nId,2282288
uroda.swiatkobiety.pl###articleObjectSeeAlso1

! usadzenie widżetu po prawej uczepionego do scrolla i wyjeżdżającego/wjeżdżającego - zrzut ekranu 25:
teksciory.interia.pl###rmf-player

! baner na dole - zrzut ekranu 26:
rankomat.pl##.searching-cheap-oc

! usunięcie popupu brązowego - zrzut ekranu 27:
nowahistoria.interia.pl###fb_layer_box

! uzupełnienie
! dodanie ,magazynauto.interia.pl do ##.topbar:style(position: absolute!important;)

! https://www.artefakt.pl
! usadzenie scrollującego headera białego - zrzut ekranu 28
! usunięcie scrollującego czat-widżetu po prawej na dole - zrzut ekranu 28
! https://www.artefakt.pl/oferta
! usunięcie scrollującego przewiń do góry - zrzut ekranu 29
www.artefakt.pl##header:style(position: absolute!important;)
www.artefakt.pl###tidio-chat, #scrollUp

! usadzenie scrollującego headera białego - zrzut ekranu 30
! usunięcie scrollującej stopki - zrzut ekranu 30
www.sunrisesystem.pl##.head:style(position: absolute!important;)
www.sunrisesystem.pl##.messages

! usadzenie headera szarego - zrzut ekranu 31
! usunięcie popupa - zrzut ekranu 32
! usadzenie scrollującego przycisku przewiń do góry po lewej na dole - zrzut ekranu 33
! usadzenie scrollującego przycisku kontakt po lewej na dole - zrzut ekranu 31
przewiń do góry i kontaktu
www.topsolutions.pl###Top_bar:style(position: absolute!important;)
www.topsolutions.pl###cp-widget
www.topsolutions.pl###back_to_top:style(position: absolute!important;)
www.topsolutions.pl###popup_contact:style(position: absolute!important;)

! usunięcie popupa i przewiń do góry - zrzuty ekranu 34, 35
! usadzenie scrollującego przycisku mapy po lewej na środku - zrzut ekranu 36
www.widzialni.pl###cp-widget, #toTop
www.widzialni.pl##.toggle-contact:style(position: absolute!important;)

! usunięcie przewiń do góry i przycisków  - zrzut ekranu 37
tube.ad##.go-top, .nav
```
! przy okazji usunięcie widżetu social idzie także na social >> https://github.com/MajkiIT/polish-ads-filter/issues/3876

Kopiuj-wklej, posortowane + ! uzupełnienie:
```
!
!
! Bauer Media
cyfrowypolsat.interia.pl##.fixed.doNotResize.v7header:style(position: relative!important;)
deccoria.pl##.sidebar-container:style(position: static!important;)
dzikikraj.interia.pl###RankingTopicsUsers:style(position: absolute!important;)
ebrokerpartner.pl###top-page:style(position: absolute!important;)
forum.interia.pl##.f3-sidebar-container:style(position: static!important;)
grupaebroker.pl##body > .skrollable:style(position: absolute!important;)
nowahistoria.interia.pl###fb_layer_box
opinie24.pl##.fixed.mobile:style(position: static!important;)
pogoda.interia.pl##.weather-forecast-longterm-list-head-entry:style(position: static!important;)
pogoda.interia.pl##.weather-head-entry:style(position: static!important;)
programtv.interia.pl##.hour-select:style(top: auto!important;)
programtv.interia.pl##.slider-wrapper-bar1:style(top: auto!important;)
programtv.interia.pl##.time-list:style(top: auto!important;)
rankomat.pl##.searching-cheap-oc
smaker.pl,www.styl.pl,www.pcformat.pl,www.cdaction.pl,www.grazia.pl,uroda.swiatkobiety.pl,www.swiatkobiety.pl,www.pomponik.pl,teksciory.interia.pl,deccoria.pl,porady.swiatkobiety.pl,przepisy.swiatkobiety.pl,finanse.swiatkobiety.pl,podroze.swiatkobiety.pl,rodzina.swiatkobiety.pl,interia.tv,magazynauto.interia.pl##.topbar:style(position: absolute!important;)
swiatseriali.interia.pl##.is-fixed.recommend-flybar-block
swiatseriali.interia.pl,pogoda.interia.pl,lotto.interia.pl,film.interia.pl,programtv.interia.pl,encyklopedia.interia.pl,fakty.interia.pl,biznes.interia.pl,mojeinwestycje.interia.pl,praca.interia.pl,sport.interia.pl,motoryzacja.interia.pl,nowahistoria.interia.pl,nt.interia.pl,mobtech.interia.pl,gry.interia.pl,kobieta.interia.pl,mamdziecko.interia.pl,on.interia.pl,muzyka.interia.pl,forum.interia.pl,ding.interia.pl,kartki.interia.pl,dzikikraj.interia.pl,zkarnego.interia.pl,wideo.interia.pl,funduszeue.interia.pl,raportdrogowy.interia.pl##.portal-bar:style(position: absolute!important;)
swiatseriali.interia.pl,pogoda.interia.pl,lotto.interia.pl,film.interia.pl,programtv.interia.pl,encyklopedia.interia.pl,fakty.interia.pl,biznes.interia.pl,mojeinwestycje.interia.pl,praca.interia.pl,sport.interia.pl,motoryzacja.interia.pl,nowahistoria.interia.pl,nt.interia.pl,mobtech.interia.pl,gry.interia.pl,kobieta.interia.pl,mamdziecko.interia.pl,on.interia.pl,muzyka.interia.pl,forum.interia.pl,ding.interia.pl,kartki.interia.pl,dzikikraj.interia.pl,zkarnego.interia.pl,wideo.interia.pl,funduszeue.interia.pl,raportdrogowy.interia.pl,www.interia.pl##.account:style(position: absolute!important;)
teksciory.interia.pl###rmf-player
teletydzien.interia.pl###channels-wrapper:style(position: absolute!important; top: auto!important;)
tipy.interia.pl##.tbar:style(position: absolute!important; top: -40px!important;)
tube.ad##.go-top, .nav
uroda.swiatkobiety.pl###articleObjectSeeAlso1
www.artefakt.pl###tidio-chat, #scrollUp
www.artefakt.pl##header:style(position: absolute!important;)
www.bryk.pl##.header-wrapper:style(position: static!important;)
www.bryk.pl##.sticky.col-wrapper:style(position: relative!important;)
www.gruparmf.pl###totop
www.gruparmf.pl##.chaser:style(position: absolute!important;)
www.interia.pl##[id^="pasek_"]:style(position: absolute!important;)
www.maxmodels.pl###moreArticles, .right:style(position: static!important;)
www.promocyjni.pl###main-nav:style(position: absolute!important; top: 0px!important;)
www.promocyjni.pl##.new-dymek-holder
www.promocyjni.pl##.rebate-codes-main.rebate-toggling:style(top: 20px!important;)
www.promocyjni.pl##.scroll-up, .socials-float
www.promocyjni.pl##.show-main-logo:style(display: block!important;)
www.promocyjni.pl##.show-mini-logo:style(display: none!important;)
www.rmfclassic.pl##.header:style(position: absolute!important;)
www.rmfclassic.pl##html > body:style(padding: 0px!important;)
www.sunrisesystem.pl##.head:style(position: absolute!important;)
www.sunrisesystem.pl##.messages
www.topsolutions.pl###Top_bar:style(position: absolute!important;)
www.topsolutions.pl###back_to_top:style(position: absolute!important;)
www.topsolutions.pl###cp-widget
www.topsolutions.pl###popup_contact:style(position: absolute!important;)
www.widzialni.pl###cp-widget, #toTop
www.widzialni.pl##.toggle-contact:style(position: absolute!important;)
||ebrokerpartner.pl/js/frontend/modules/popup.js$script
```
! Tu czysto czyli inne listy zbierają albo nic nie ma:
! http://25lat.rmf.fm
! http://domeny.interia.pl
! http://firma.interia.pl
! http://gameboard.pl
! http://gramy.interia.pl
! http://kodyrabatowe.interia.pl
! http://kodyrabatowe.interia.pl
! http://krs.interia.pl
! http://leksykony.interia.pl
! http://leszekgorzelnik.w.interiowo.pl
! http://lider4x4.interia.pl
! http://m.rmf.fm
! http://magicpiano.w.interiowo.pl
! http://nazywo.interia.pl
! http://polonista.w.interiowo.pl
! http://pomoc.poczta.interia.pl
! http://porownywarka.interia.pl
! http://prawojazdy.interia.pl
! http://rss.interia.pl
! http://staze.interia.pl
! http://szukaj.interia.pl
! http://tlumacz.interia.pl
! http://twojezdrowie.rmf24.pl
! http://www.biznes-firma.pl
! http://www.click.pl
! http://www.opracowania.pl
! http://www.rmf.fm
! http://www.rmf24.pl
! http://www.rmfmaxxx.pl
! http://www.rmfon.pl
! http://www.wsuknislubnej.pl
! http://wyniki.interia.pl
! https://czateria.interia.pl
! https://euro-tax.pl
! https://konto.interia.pl
! https://poczta.interia.pl
! https://sowafinansowa.pl
! uzupełnienie
! http://gra.fm
! http://swiatwiedzy.interia.pl
! http://www.fun-club.pl
! http://www.radio90.pl
! http://www.radiojura.pl
! http://www.twist.pl

Zrzut ekranu 1:
![](https://s3.dodajfote.pl/2017/09/30/interia_glowna_headera12c8.png)

Zrzut ekranu 2:
![](https://s3.dodajfote.pl/2017/09/30/interia_ebroker_header_szary074ac.png)

Zrzut ekranu 3:
![](https://s3.dodajfote.pl/2017/09/30/interia_styl_header47094.png)

Zrzut ekranu 4:
![](https://s3.dodajfote.pl/2017/09/30/interia_cyfrowypolsat_header_bialye9cdb.png)

Zrzut ekranu 5:
![](https://s3.dodajfote.pl/2017/09/30/interia_teletydzien_header46bf7.png)

Zrzut ekranu 6:
![](https://s3.dodajfote.pl/2017/09/30/interia_pogoda_headerb0470.png)

Zrzut ekranu 7:
![](https://s3.dodajfote.pl/2017/09/30/interia_grupaebroker_header_bialye1325.png)

Zrzut ekranu 8:
![](https://s3.dodajfote.pl/2017/09/30/interia_ebroker_partner_popupff212.png)

Zrzut ekranu 9:
![](https://s3.dodajfote.pl/2017/09/30/interia_opinie_header_niebieski7057d.png)

Zrzut e kranu 10:
![](https://s3.dodajfote.pl/2017/09/30/interia_rmf_classic_header_black2ba9e.png)

Zrzut ekranu 11:
![](https://s3.dodajfote.pl/2017/09/30/interia_grupa_rmffm_header_i_do_gory71b76.png)

Zrzut ekranu 12:
![](https://s3.dodajfote.pl/2017/09/30/interia_bryk_header_black_i_panel_po_prawej_Scroll0869b.png)

Zrzut ekranu 13:
![](https://s3.dodajfote.pl/2017/09/30/interia_promocyni_hedaer_czarnobialy_i_popupd0d67.png)

Zrzut ekranu 16:
![](https://s3.dodajfote.pl/2017/09/30/interia_promocyjni_do_goryd64df.png)

Zrzut ekranu 17:
![](https://s3.dodajfote.pl/2017/09/30/interia_programtv_time_header27f52.png)

Zrzut ekranu 18:
![](https://s3.dodajfote.pl/2017/09/30/interia_dziki_kraj_po_prawej_baner_scrollba048.png)

Zrzut ekranu 19:
![](https://s3.dodajfote.pl/2017/09/30/interia_forum_scroll_panel_po_prawejed256.png)

Zrzut ekranu 20:
![](https://s3.dodajfote.pl/2017/09/30/interia_deccoria_panel_po_prawej_scroll70eb5.png)

Zrzut ekranu 21:
![]()

Zrzut ekranu 22:
![](https://s3.dodajfote.pl/2017/09/30/interia_swiat_seriali_stopkab8266.png)

Zrzut ekranu 23:
![](https://s3.dodajfote.pl/2017/09/30/interia_maxmodels_nastepny_artykulbab1d.png)

Zrzut ekranu 24:
![](https://s3.dodajfote.pl/2017/09/30/interia_uroda_swiatkobiety_next_article_widget0d11a.png)

Zrzut ekranu 25:
![](https://s3.dodajfote.pl/2017/09/30/interia_teksciory_widzget_po_prawej6f1e5.png)

Zrzut ekranu 26:
![](https://s3.dodajfote.pl/2017/09/30/interia_rankomat_stopkab794c.png)

Zrzut ekranu 27:
![](https://s3.dodajfote.pl/2017/09/30/interia_nowahistoria_popup_brazowydf555.png)

Zrzut ekranu 28:
![](https://s3.dodajfote.pl/2017/10/02/bauer_artefakt_header_bialy_i_gadzet_prawa_dol9b186cbe0276d453.png)

Zrzut ekranu 29:
![](https://s3.dodajfote.pl/2017/10/02/bauer_artefakt_przewin_do_gory_prawa_dol6493dfd1664fd717.png)

Zrzut ekranu 30:
![](https://s3.dodajfote.pl/2017/10/02/bauer_sunrisesystem_header_i_stopka8384b870947fce2b.png)

Zrzut ekranu 31:
![](https://s3.dodajfote.pl/2017/10/02/bauer_topsolutions_header_szary_i_gadzet_prawa_dola645c5e9a5eb2b5f.png)

Zrzut ekranu 32:
![](https://s3.dodajfote.pl/2017/10/02/bauer_topsolutions_popup304cf1e9356efb6d.png)

Zrzut ekranu 33:
![](https://s3.dodajfote.pl/2017/10/02/bauer_topsolutions_przewin_do_goryc94f31a173281c08.png)

Zrzut ekranu 34:
![](https://s3.dodajfote.pl/2017/10/02/bauer_widzilalni_popupebbc42b6eb3a4e96.png)

Zrzut ekranu 35:
![](https://s3.dodajfote.pl/2017/10/02/bauer_widzilalni_przewin_do_gory6b9b2b3fcfd981c5.png)

Zrzut ekranu 36:
![](https://s3.dodajfote.pl/2017/10/02/bauer_widzilalni_mapa_widzet_po_lewej2520b553a3a247f4.png)

Zrzut ekranu 37:
![](https://s3.dodajfote.pl/2017/10/02/bauer_tubead_przyciski_i_przewin_do_gory_nadole4884de3910a8f519.png)

**Comment by gomoku** [comment]
**_1__**
Dopiero dzisiaj w południe zorientowałem się, że 
`www.promocyjni.pl##.scroll-up, .socials-float` trzeba zredukować do
`www.promocyjni.pl##.scroll-up` bo  
`www.promocyjni.pl##.socials-float` poszło na social.

**_2_**
Jeśli nikt nic nie wykombinuje na 2 problemy, to trzeba będzie wątkowi dać etykietę "potrzebna pomoc".

**Comment by hawkeye116477** [comment]
Tak właściwie to są jeżdżące przyciski, a na dole i tak są zwykłe statyczne, więc nie trzeba nic redukować.

**Comment by gomoku** [comment]
**_1__**

> @hawkeye116477: changed the title from [Grupa Interia] to [Grupa Bauer Media]

No na początku ogarniania tej grupy Interia rozglądałem się czy ta Interia to jeszcze do czegoś nie należy, ale chyba tak pochłonęła mnie robota, że zapomniałem o tym, żeby dokładniej sprawdzić, no jak widać to teraz będę miał trochę dodatkowych stron tego Bauera do ogarnięcia, więc jeszcze nie zamykaj wątku. A w ogóle czy to ten sam niemiecki Bauer od wysokiej klasy łyżworolek?

**_2__**
> @hawkeye116477:  Tak właściwie to są jeżdżące przyciski, a na dole i tak są zwykłe statyczne, więc nie trzeba nic redukować.

Albo ja nie czaję tego co ty napisałeś, albo ty nie czaisz tego co ja napisałem, bo przecież od elementów social zdaje się jest lista social?

**_3__**
> @hawkeye116477:  A co do popupu blokującego scroll, to nie trzeba dawać kosmetycznej na popup, można go tak zablokować -> `||ebrokerpartner.pl/js/frontend/modules/popup.js$script`, a wtedy scroll się nie zablokuje 😃 .

Tak się już przyzwyczaiłem do tego, że większość filtrów tutaj to kosmetyczne, że wpadłem w pewną rutynę - zapomniałem o filtrach sieciowych.

**_4__**
> @hawkeye116477: A jeśli chodzi o tipy.interia.pl, to można dać tak -> `tipy.interia.pl##.tbar:style(position: absolute!important; top: -40px!important;)` Tylko czy u ciebie @gomoku tak będzie ok?

No jest dobrze, a w ogóle to ja właśnie dokładnie taki filtr próbowałem, i ten margines nie schodził, a na twoim filtrze schodzi, pewnie gdzieś po prostu jakiś błąd popełniłem, może ze zmęczenia, a może ze zwykłego przeoczenia.

Dobrze, że wyłapałeś moje braki 1, 3 i 4, jak to mawiają co dwie głowy to nie jedna.

**Comment by hawkeye116477** [comment]
> Albo ja nie czaję tego co ty napisałeś, albo ty nie czaisz tego co ja napisałem, bo przecież od elementów social zdaje się jest lista social?

No może i od tego jest tego lista social, ale na dole masz takie same przyciski tylko, że statyczne, więc nic nie zaszkodzi jak schowamy te jeżdżące.

> A w ogóle czy to ten sam niemiecki Bauer od wysokiej klasy łyżworolek?
Firma jest niemiecka, ale czy to ta sama to nie wiem.

**Comment by gomoku** [comment]
> @hawkeye116477:  No może i od tego jest tego lista social, ale na dole masz takie same przyciski tylko, że statyczne, więc po co 2 razy to samo, to jest nachalne działanie, a my takie nachalne rzeczy blokujemy 😄 . Także to kwalifikuje się do obu filtrów.

Sorry, ale nie czaję tak do końca, ok nachalne bo 2 razy, a, że lata przyklejone do scrolla to już nie nachalne? Tzn, że jeśli na dole nie byłoby drugich takich samych przycisków, to nie byłoby nachalne, pomimo, że lata ze scrollem i wtedy poszłoby tylko do sociala? Bo wiele razy zgłaszałem social przyciski i zawsze szły tylko na social, pomimo, że latały ze scrollem.

> @hawkeye116477: Właścicielem Bauer Media Polska jest niemieckie przedsiębiorstwo Heinrich Bauer Verlag Kommanditgesellschaft z Hamburga , ale czy oni też produkują łyżworolki to nie wiem.

O takie łyżworolki mi chodzi https://www.google.pl/search?q=bauer+%C5%82y%C5%BCworolki

**Comment by hawkeye116477** [comment]
@gomoku Masz rację, jeżdżące za scrollem też nachalne, tutaj po prostu przegięli pałę, dając 2 razy to samo. Ale może jednak jeśli social elementy jeżdżą za scrollem, to reguły powinny trafiać do obu list, takie jest moje zdanie, ale @blocker999 widać ma inne.

**Comment by gomoku** [comment]
**_1__**
Zaktualizowałem i uzupełniłem pierwszy post o nowe strony Bauera, onzaczyłem tagiem: `! uzupełnienie`

**_2__**
- a) no właśnie z tymi socialami to o mi chodziło, o konsekwentną logikę, że nachalność to nachalność, bez względu na to jaka - więc idzie do obu list, a statyczne tylko do sociali. 
- b) drugą kwestią jest to, że to dopiero od tej chwili, więc kto teraz pokopiuje te zaległe nachalności z Sociali do PopupBlockera, które wcześniej nie zostały dodane do PopupBlockera.

**Comment by hawkeye116477** [comment]
@gomoku Na chat Tidio jest już reguła ogólna na wszystkie strony pl, więc nie trzeba dawać tego na artefakt.pl, ale tak powinno być lepiej -> `||code.tidio.co^$third-party`, będzie oszczędność transferu dla niektórych ludzi 😄 .

**Comment by blocker999** [comment]
@gomoku  

1 - Już poprawiłem, może być?

2
a) To ustalone

b) Spoko, przy poszukiwaniach do PB wystarczy wyłączyć sociale zresztą mam kilka przeglądarek, no i sam problem nie jest tak częsty, zresztą licze też na @hawkeye116477 jak i Twoją pomoc a i może ktoś nowy do pomocy się pojawi.

**Comment by gomoku** [comment]
@hawkeye116477 i @blocker999: jest OK.

**Comment by blocker999** [comment]
Acha, przy okazji, @gomoku jak byś sklasyfikował popup zachęcający do polubienia facebooku jakiejś firmy?

**Comment by gomoku** [comment]
Popupy są do dupy, czeba je blokować z buta.
