### ISSUE TITLE
www.ravelo.pl

### ISSUE THREAD

**Issue by gomoku** [azet12/PopupBlocker#169]
! usadzenie dolnego headera - zrzut ekranu 1 , defekt - zrzut ekranu 2
! usunięcie jebutnego popupa - zrzut ekranu 3
```
www.ravelo.pl##.searchRow:style(position: absolute!important; margin-top: 0px!important;)
www.ravelo.pl###modalAlertMethodNL
```
Tylko na tych regułach od dolnego headera, ten dolny header coś tak, znika/pojawia się gdy jest przy krawędzi przy przewijaniu, w sumie nie jest to aż tak krytyczne, bo znika/pojawia się akurat wtedy gdy powinien, więc możnaby te reguły dodać, ale jeśli ktoś dałby radę to doszlifować...to byłoby dobrze, bo te znikanie/pojawianie może trochę wkurzać. Tak czy inaczej regułę od popupa można od razu dodać

Zrzut ekranu 1:
![](https://s3.dodajfote.pl/2017/09/30/ravelo_headerb1965.png)

Zrzut ekranu 2:
![](https://s3.dodajfote.pl/2017/09/30/ravelo_header-znika37514.png)

Zrzut ekranu 3:
![](https://s3.dodajfote.pl/2017/09/30/ravelo_popup44779.png)

**Comment by blocker999** [comment]
@gomoku Na jakiej przeglądarce masz te pykanie no i najlepiej screena wrzuć to może jutro to dorwe.

**Comment by gomoku** [comment]
Muszę siebie trochę sprostować, to nie pykanie, tylko znikanie/pojawianie się, chodzi o to, że, gdy coś jest dobrze usadzone to przy przewijaniu znika naturalnie tzn. po prostu wjeżdża/wyjeżdża pod/spod górną krawędź okna strony, a ten header znika/pojawia się (po zniknięciu jest pusty kontener). Jak coś to FF 56 i Opera 47

**Comment by hawkeye116477** [comment]
Też tak mam jak @gomoku, ale ja nic z tym nie poradzę, to raczej zadanie dla jakiegoś eksperta typu @F4z.

**Comment by blocker999** [comment]
@gomoku Naprawde niewiem czy dobrze się rozumiemy czy chodzi Ci dokładnie  o ten wystający kawałek headeru?, bo jeśli tak to masz kilka opcji:

- Usunąć ten pierwszy od góry pasek `##.topLine` ( niepolecam )
- Napisać do admina strony
- Dać sobie spokój z tą stroną, bo to szczegół
- Samemu coś wymyśleć
- Poczekać na Experta.

**Comment by gomoku** [comment]
Nie wiem czy mi chodzi o to o co ci chodzi, bo nie wiem czy ci chodzi o to o co mi chodzi (ale raczej nie), bo mi chodzi o to o co chodzi w tym komentarzu https://github.com/azet12/PopupBlocker/issues/169#issuecomment-333357663, a że nie umiem tego inaczej napisać to nagrałem filmik: https://vimeo.com/236461297

**Comment by gwarser** [comment]
Znikające przy przewijaniu menu pod topem `www.ravelo.pl##.mainMenu:style(display: block!important;)`. Coś tam jeszcze wystaje, ale już mi się nie chce.

**Comment by hawkeye116477** [comment]
@gomoku Działa, dzięki. Te wystające coś to jest margines dolny wewnętrzny i cień. Więc wystarczy dodać coś takiego do stylu searchRow `padding-bottom: 0px!important; box-shadow: none!important;` i będzie git 😄 .

**Comment by gomoku** [comment]
Potwierdzam, teraz wszystko jest tak ładnie wyklepane, że można sprzedać komuś jak nowe, bezwypadkowe.
