### ISSUE TITLE
www.polskieradio.pl

### ISSUE THREAD

**Issue by gomoku** [azet12/PopupBlocker#170]
! usadzenie scrollującego headera, to go częściowo usadza ale dalej coś tam skacze:
`www.polskieradio.pl###prMenu:style(position: relative!important;)`

![](https://s3.dodajfote.pl/2017/10/03/polskieradio_headerea6bf199d932c88d.png)

Tu czysto, bo inne listy zbierają albo nic nie ma:
http://herbert.polskieradio.pl
http://kennedy.polskieradio.pl/
http://kulturapomaga.polskieradio.pl/
http://lp3.polskieradio.pl/
http://moje.polskieradio.pl/
http://piesniniepokornych.polskieradio.pl/
http://sklep.polskieradio.pl/
http://zolnierzewykleci.polskieradio.pl/

**Comment by gomoku** [comment]
Trzeba zmienić etykietę na "potrzebna pomoc".

**Comment by gwarser** [comment]
Skakanie topu `polskieradio.pl##script:inject(setTimeout-defuser.js, scrolling, 25)`

**Comment by hawkeye116477** [comment]
@gwarser Działa, dzięki.
