### ISSUE TITLE
[Grupa Wirtualna Polska Holding] wp.pl / o2.pl...

### ISSUE THREAD

**Issue by gomoku** [azet12/PopupBlocker#171]
https://pl.wikipedia.org/wiki/Wirtualna_Polska_Holding

```
! Usadzenie Grupy Wirtualna Polska Holding

! najpierw przeniesiemy do grupy to co jest w PopupBlockerze (a z PopupBlockera trzeba usunąć):
www.wp.pl###home-page-button, #newsfeed-player-column 
! koniec

! usadzenie scrollujących headerów - zrzuty ekranu 1-25 + 46,50:
dom.wp.pl,facet.wp.pl,film.wp.pl,finanse.wp.pl,gry.wp.pl,gwiazdy.wp.pl,kobieta.wp.pl,ksiazki.wp.pl,kuchnia.wp.pl,moto.wp.pl,opinie.wp.pl,tech.wp.pl,teleshow.wp.pl,turystyka.wp.pl,wiadomosci.wp.pl##div[data-reactid="11"]:style(position: relative!important;)
wp.tv###stgHeader:style(position: static!important;)
wp.tv##body:style(padding-top: 0px!important;)
inwestor.wp.pl##.desktop-fixed.jq-header-height:style(position: absolute!important;)
reklama.wp.pl##.headerLinks > .fixed.in:style(position: absolute!important;)
reklama.wp.pl##.main > .fixed.in:style(position: absolute!important;)
parenting.pl##.top-header.header:style(position: absolute!important;)
blomedia.pl##.agregator-haeder:style(position: absolute!important;)
domodi.pl##.js-header.dm-header:style(position: absolute!important;)
www.wakacje.pl###searchBox:style(position: absolute!important;)
ranking.abczdrowie.pl##.group.page-header--new-nav.page-header-2013.page-header.stickypanel:style(position: absolute!important;)
fitness.wp.pl##.fixed-header--display.adsize_header.x-header.main-header-small.agregator-header:style(position: static!important;)
fitness.wp.pl##.wpfitness.homepage:style(padding-top: 0px!important;)
hosting.wp.pl##.navbar-fixed-top.navbar:style(position: absolute!important;)
www.multikurs.pl##.topbar-discount.row:style(position: absolute!important;)
m.money.pl###header:style(position: absolute!important;)
m.sportowefakty.wp.pl###mainheader:style(position: absolute!important;)
www.homebook.pl##.hbk-page-header__container:style(position: absolute!important;)
! (fotoblogia.pl) znalezione przez @xxcriticxx tu >> https://github.com/MajkiIT/polish-ads-filter/issues/3907#issue-262980340
fotoblogia.pl##.fixed-header--display.adsize_header.x-header.main-header-small.agregator-header:style(position: absolute!important;)
! https://e-prawnik.pl/porady-prawne-online/zadaj-pytanie.html
e-prawnik.pl##.navbar-fixed-top.navbar-default.navbar:style(position: absolute!important;)
! pytamy.wp.pl >> pytamy.pl
pytamy.pl###Main:style(position: absolute!important;)
! http://www.wp.pl/mobile
www.wp.pl##header.header:style(position: absolute!important;)
! tutaj usunięcie headera bo jest zdublowany
biztok.money.pl,dom.money.pl,manager.money.pl,moto.money.pl,msp.money.pl,pogoda.money.pl,praca.money.pl,prawo.money.pl,przetargi.money.pl,tech.money.pl,www.money.pl###fixedHeader
tv.wp.pl###Slider
! tutaj usadzonne ale coś tam jeszcze fika
www.dobreprogramy.pl###header:style(position: absolute!important;)
direct.money.pl###main-menu:style(position: static!important;)
www.pudelek.tv###header:style(position: absolute!important;)
! tutaj nie mogę usadzić, bo chyba jakaś ramka
! bigfarm.wp.pl,empire.wp.pl,forgeofempires.wp.pl,klondike.wp.pl,lowcyzombi.wp.pl,naryby.wp.pl,railnation.wp.pl###stgHeader:style(position: static!important;)
! tutaj nie mogę usadzić bo zostaje margines
! mail.tlen.pl##.header:style(position: static!important;)

! usadzenie scrollującego widżetu - dymka z komentarzami po prawej - zrzut ekranu 46
! znalezione przez @xxcriticxx tu >> https://github.com/MajkiIT/polish-ads-filter/issues/3907#issue-262980340
fotoblogia.pl##.btn-comments.btn

! usunięcie popup-reklama - zrzut ekranu 49
! znalezione przez @xxcriticxx tu >> https://github.com/MajkiIT/polish-ads-filter/issues/3908#issue-263107662
komediowo.pl###adv03

! usadzenie popup-widżetów, po prawej, po środku, po lewej - zrzut ekranu 26
! http://e-prawnik.pl/porady-prawne/prawo-karne/prawo-do-widzen-z-tymczasowo-aresztowanym-1.html
e-prawnik.pl###order-box, #chat-application, .o-window.windowTop

! usunięcie popupa po lewej u góry - zrzut ekranu 27
! usunięcie przycisków scrollujących po prawej i przewiń do góry po prawej na dole - zrzut ekranu 27
domodi.pl###acc-alert
domodi.pl##.dm-sticky-buttons, .is-active.js-scroll-top.dm-go-up

! czat widżet po prawej na dole - zrzut ekranu 28
fantasyliga.wp.pl###wp_main_header > div:nth-of-type(6)

! widżet typu następny artykuł na doel po prawej - zrzut ekranu 29
direct.money.pl,www.totalmoney.pl###widget-fc-mobile-button

! usunięcie przewiń do góry po prawej na dole - zrzut ekranu 30
www.nocowanie.pl##.is-sticky.btn--top.btn
! usunięcie popupa newsletter - zrzut ekranu 31
! ale coś nie do końca działa, bo popup zostaje usunięty ale, pozostaje wyciemnione tło
! www.nocowanie.pl##.fancybox-opened.fancybox--alt.fancybox-type-html.fancybox-desktop.fancybox-wrap

! usunięcie przewiń do góry - zrzut ekranu 32
www.multikurs.pl##.scrollup
www.homebook.pl##.is-active.js-go-top.go-top

! usunięcie popupu - zrzut ekranu 33
www.foto.wp.pl##.main-container

! usadzenie panelu scrollującego po lewej - zrzut ekranu 34
! https://direct.money.pl/numerkonta/
direct.money.pl##.stick.col-10:style(position: absolute!important;)

! usadzenie panelu scrollującego po prawej
! http://sportowybar.wp.pl/gid,17041713,kat,1726,page,8,title,Pilkarski-wtorek-tak-graly-europejskie-reprezentacje,galeria.html
sportowybar.wp.pl###stgCol300:style(position: absolute!important;)

! usunięcie jebutnego popupa na środku przy przewijaniu strony w dół - zrzuty ekranu 36 i 37
www.pudelek.pl##body > div:nth-of-type(7)
! może da się ten skrócić
misioweopowiesci.o2.pl##.shepherd-abutted-top.shepherd-abutted-right.shepherd-enabled.shepherd-target-attached-center.shepherd-element-attached-center.shepherd-pinned-top.shepherd-pinned.shepherd-abutted-left.shepherd-abutted.shepherd-has-title.shepherd-theme-arrows.shepherd-open.shepherd-element.shepherd-step

! znalezione przez @HateAds >> https://github.com/MajkiIT/polish-ads-filter/issues/3901#issuecomment-334101267
! usunięcie natrętnego scrollującego widżetu typu nastęny artykuł po lewej - zrzut ekranu 38
! https://www.money.pl/gospodarka/wiadomosci/artykul/stopy-procentowe-decyzja-rpp-oprocentowanie,199,0,2372807.html
www.money.pl##.float.more-news

! usadzenie scrollującego panelu nawigacji/headera po lewej - zrzut ekranu 39
misioweopowiesci.o2.pl##.site-nav:style(position: absolute!important;)
! usunięcie scrollującego widżetu po prawej - zrzut ekranu 39
misioweopowiesci.o2.pl##.playlist__wrapper

! jebutny popup nie wiem jak go usadzić - zrzut ekranu 40
! https://forgeofempires.wp.pl

! scrollujący panel po prawej nie mogę usadzić - zrzut ekranu 41
! https://www.dobreprogramy.pl/Microsoft-konczy-z-muzyka-Spotify-zastapi-Windows-Store-i-Groove-Music-Pass,News,83459.html

! zrzuty ekranu 42 i 43
! usunięcie prawego górnego widżetu
www.o2.pl##div[data-st-area="ST-CrnrML-main-area"]
! nie wiem jak usadzić/usunąć pozostałe 3 widżety w pozostałych rogach, bo mają losowe nazwy
! a w ogóle to nie wiem czy te widżety usadzać czy usuwać, bo odsyłają do funkcjonalnych 
! części strony, do których nie ma prowadzących innych odnośników/przycisków niż właśnie te widżety

! nie wiem jak usunąć przyciski i dymki dodawania strony startowej na headerze - przykładowe zrzuty ekranu 44 i 45

! popupy-reklamy-nowe
! https://github.com/MajkiIT/polish-ads-filter/issues/3893
! https://github.com/MajkiIT/polish-ads-filter/issues/3892
! tylko, że trzeba je upolować, bo gdy się pojawiały to byłem zajęty robieniem i obrabianiem zrzutu ekranu, a gdy wróciłem żeby stworzyć filtr i zablokować to skubane zdążyły zniknąć, 
! znikają po kilkunastu sekundach, następnym razem tylko zrobię szybko zrzut, ale nie będę obrabiał, zamiast tego stworzę filtr i zablokuję najpierw, a obrabianiem zrzut zajmę się potem.
```

Kopiuj-wklej posortowane alfabetycznie:
```
!
!
! WP
biztok.money.pl,dom.money.pl,manager.money.pl,moto.money.pl,msp.money.pl,pogoda.money.pl,praca.money.pl,prawo.money.pl,przetargi.money.pl,tech.money.pl,www.money.pl###fixedHeader
blomedia.pl##.agregator-haeder:style(position: absolute!important;)
direct.money.pl###main-menu:style(position: static!important;)
direct.money.pl##.stick.col-10:style(position: absolute!important;)
direct.money.pl,www.totalmoney.pl###widget-fc-mobile-button
dom.wp.pl,facet.wp.pl,film.wp.pl,finanse.wp.pl,gry.wp.pl,gwiazdy.wp.pl,kobieta.wp.pl,ksiazki.wp.pl,kuchnia.wp.pl,moto.wp.pl,opinie.wp.pl,tech.wp.pl,teleshow.wp.pl,turystyka.wp.pl,wiadomosci.wp.pl##div[data-reactid="11"]:style(position: relative!important;)
domodi.pl###acc-alert
domodi.pl##.dm-sticky-buttons, .is-active.js-scroll-top.dm-go-up
domodi.pl##.js-header.dm-header:style(position: absolute!important;)
e-prawnik.pl###order-box, #chat-application, .o-window.windowTop
e-prawnik.pl##.navbar-fixed-top.navbar-default.navbar:style(position: absolute!important;)
fantasyliga.wp.pl###wp_main_header > div:nth-of-type(6)
fitness.wp.pl##.fixed-header--display.adsize_header.x-header.main-header-small.agregator-header:style(position: static!important;)
fitness.wp.pl##.wpfitness.homepage:style(padding-top: 0px!important;)
fotoblogia.pl##.btn-comments.btn
fotoblogia.pl##.fixed-header--display.adsize_header.x-header.main-header-small.agregator-header:style(position: absolute!important;)
hosting.wp.pl##.navbar-fixed-top.navbar:style(position: absolute!important;)
inwestor.wp.pl##.desktop-fixed.jq-header-height:style(position: absolute!important;)
m.money.pl###header:style(position: absolute!important;)
m.sportowefakty.wp.pl###mainheader:style(position: absolute!important;)
misioweopowiesci.o2.pl##.playlist__wrapper
misioweopowiesci.o2.pl##.shepherd-abutted-top.shepherd-abutted-right.shepherd-enabled.shepherd-target-attached-center.shepherd-element-attached-center.shepherd-pinned-top.shepherd-pinned.shepherd-abutted-left.shepherd-abutted.shepherd-has-title.shepherd-theme-arrows.shepherd-open.shepherd-element.shepherd-step
misioweopowiesci.o2.pl##.site-nav:style(position: absolute!important;)
parenting.pl##.top-header.header:style(position: absolute!important;)
pytamy.pl###Main:style(position: absolute!important;)
ranking.abczdrowie.pl##.group.page-header--new-nav.page-header-2013.page-header.stickypanel:style(position: absolute!important;)
reklama.wp.pl##.headerLinks > .fixed.in:style(position: absolute!important;)
reklama.wp.pl##.main > .fixed.in:style(position: absolute!important;)
sportowybar.wp.pl###stgCol300:style(position: absolute!important;)
tv.wp.pl###Slider
wp.tv###stgHeader:style(position: static!important;)
wp.tv##body:style(padding-top: 0px!important;)
www.dobreprogramy.pl###header:style(position: absolute!important;)
www.foto.wp.pl##.main-container
www.homebook.pl##.hbk-page-header__container:style(position: absolute!important;)
www.homebook.pl##.is-active.js-go-top.go-top
www.money.pl##.float.more-news
www.multikurs.pl##.scrollup
www.multikurs.pl##.topbar-discount.row:style(position: absolute!important;)
www.nocowanie.pl##.is-sticky.btn--top.btn
www.o2.pl##div[data-st-area="ST-CrnrML-main-area"]
www.pudelek.pl##body > div:nth-of-type(7)
www.pudelek.tv###header:style(position: absolute!important;)
www.wakacje.pl###searchBox:style(position: absolute!important;)
www.wp.pl###home-page-button, #newsfeed-player-column
www.wp.pl##header.header:style(position: absolute!important;)
```

! Tu czysto bo inne listy zbierają albo nic nie ma:
! http://bigfarm.wp.pl
! http://casino.pl
! http://czat.wp.pl
! http://dladzieci.pl
! http://druk.bauer.pl
! http://dzieci.pl
! http://ebooki.wp.pl
! http://empire.wp.pl
! http://f.kafeteria.pl
! http://forum.o2.pl
! http://gryonline.wp.pl
! http://kafeteria.pl
! http://lowcyzombi.wp.pl
! http://magazyn.wp.pl
! http://muzyka.wp.pl
! http://naryby.wp.pl
! http://ogloszenia.wp.pl
! http://onas.wp.pl
! http://owabgxis.wp.pl
! http://poczta.wp.pl/info-antyspam-polityka.html
! http://pogoda.wp.pl
! http://pomoc.wp.pl
! http://profil.wp.pl
! http://pudelekx.pl/
! http://railnation.wp.pl
! http://rekrutacja.wp.pl
! http://sportowybar.wp.pl/gid,17041713,kat,1726,page,8,title,Pilkarski-wtorek-tak-graly-europejskie-reprezentacje,galeria.html
! http://techsterowniki.wp.pl 
! http://torebka.kafeteria.pl
! http://twojeip.wp.pl
! http://www.bloog.wp.pl >> http://bloog.pl
! http://www.easygo.pl
! http://www.enovatis.pl
! http://www.grymix.pl
! http://www.mojestypendium.pl
! http://www.wypoczynek.pl
! https://biore.to
! https://centralagier.wp.pl
! https://dlaprasy.wp.pl
! https://firmoweewolucje.money.pl
! https://forgeofempires.wp.pl
! https://kodyrabatowe.wp.pl
! https://m.sportowefakty.wp.pl
! https://portal.abczdrowie.pl
! https://sportowefakty.wp.pl

Zrzut ekranu 1:
![](https://s3.dodajfote.pl/2017/10/04/wp_bloomedia_header_bialy83633738410608e6.png)

Zrzut ekranu 2:
![](https://s3.dodajfote.pl/2017/10/04/wp_dobreprogramy_header_czarny34ac9b51cf28dbc1.png)

Zrzut ekranu 3:
![](https://s3.dodajfote.pl/2017/10/04/wp_dom_headerf2888ed111f4ec01.png)

Zrzut ekranu 4:
![](https://s3.dodajfote.pl/2017/10/04/wp_eprawnik_header756ea25ba67a10c9.png)

Zrzut ekranu 5:
![](https://s3.dodajfote.pl/2017/10/04/wp_gry_dymek_i_home_header_wjezdza960398b73b27c28f.png)

Zrzut ekranu 6:
![](https://s3.dodajfote.pl/2017/10/04/wp_gwiazdy_headerf65418a98bf18d85.png)

Zrzut ekranu 7:
![](https://s3.dodajfote.pl/2017/10/04/wp_homebook_header7ecd2201bc861cb4.png)

Zrzut ekranu 8:
![](https://s3.dodajfote.pl/2017/10/04/wp_hosting_headerbd8dc490b556c5dd.png)

Zrzut ekranu 9:
![](https://s3.dodajfote.pl/2017/10/04/wp_inwestor_header_bialybca0309c9525dcc6.png)

Zrzut ekranu 10:
![](https://s3.dodajfote.pl/2017/10/04/wp_klondike_header2e07f8e5a2783753.png)

Zrzut ekranu 11:
![](https://s3.dodajfote.pl/2017/10/04/wp_kobieta_header_i_home01db54b72b0fe42a.png)

Zrzut ekranu 12:
![](https://s3.dodajfote.pl/2017/10/04/wp_money_driect_header_i_nastepny_artykul5ae8bf8c9bac935f.png)

Zrzut ekranu 13:
![](https://s3.dodajfote.pl/2017/10/04/wp_money_headerd6a1e4cf0f53fefe.png)

Zrzut ekranu 14:
![](https://s3.dodajfote.pl/2017/10/04/wp_multikurs_header_i_przewin_do_gory66f692323bf5eca4.png)

Zrzut ekranu 15:
![](https://s3.dodajfote.pl/2017/10/04/wp_opinie_dymek_i_home_header_wjezdza29a5516fd462ed9b.png)

Zrzut ekranu 16:
![](https://s3.dodajfote.pl/2017/10/04/wp_parenting_header73b6cc463af1ed24.png)

Zrzut ekranu 17:
![](https://s3.dodajfote.pl/2017/10/04/wp_pudelek_tv_header91ce52957823ac7d.png)

Zrzut ekranu 18:
![](https://s3.dodajfote.pl/2017/10/04/wp_pytamywp_pl_header5f35c41d2a70ef21.png)

Zrzut ekranu 19:
![](https://s3.dodajfote.pl/2017/10/04/wp_ranking_abczdrowie_header0483777bcd11e3e3.png)

Zrzut ekranu 20:
![](https://s3.dodajfote.pl/2017/10/04/wp_reklama_wp_header040d977dfbe937b2.png)

Zrzut ekranu 21:
![](https://s3.dodajfote.pl/2017/10/04/wp_tech_dymek_i_home_header_wjezdza1c4861fde9fc92e3.png)

Zrzut ekranu 22:
![](https://s3.dodajfote.pl/2017/10/04/wp_turystyka_header_wjezdza0fb80d5717a493b3.png)

Zrzut ekranu 23:
![](https://s3.dodajfote.pl/2017/10/04/wp_tv_header0241594872ba736c.png)

Zrzut ekranu 24:
![](https://s3.dodajfote.pl/2017/10/04/wp_tvwppl_header8eda0234d1872a0d.png)

Zrzut ekranu 25:
![](https://s3.dodajfote.pl/2017/10/04/wp_www_wakacje_header_nebieski525cf2d026940116.png)

Zrzut ekranu 26:
![](https://s3.dodajfote.pl/2017/10/04/wp_eprawnik_widgets79025c2db8583c20.png)

Zrzut ekranu 27:
![](https://s3.dodajfote.pl/2017/10/04/wp_domodi284be1635c049e6e.png)

Zrzut ekranu 28:
![](https://s3.dodajfote.pl/2017/10/04/wp_fantasyliga_char_widget_prawy_dol6a166c42e0b1fe42.png)

Zrzut ekranu 30:
![](https://s3.dodajfote.pl/2017/10/04/wp_nocowanie_pl_przewin_do_gory83042581bb4792bc.png)

Zrzut ekranu 31:
![](https://s3.dodajfote.pl/2017/10/04/wp_nocowanie_pl_popup8a1b23f124c87c71.png)

Zrzut ekranu 32:
![](https://s3.dodajfote.pl/2017/10/04/wp_homebook_przewin_do_gory97da497b717d89e0.png)

Zrzut ekranu 33:
![](https://s3.dodajfote.pl/2017/10/04/wp_foto_popup3d44877b101a92da.png)

Zrzut ekranu 34:
![](https://s3.dodajfote.pl/2017/10/04/wp_direct_money_panel_scrollujacye60ae46729bdee60.png)

Zrzut ekranu 36:
![](https://s3.dodajfote.pl/2017/10/04/wp_pudelek_popup185e59899b3a5d8a.png)

Zrzut ekranu 37:
![](https://s3.dodajfote.pl/2017/10/04/wp_o2_misioweopowiescib98dec7d2388cf33.png)

Zrzut ekranu 38:
![](https://s3.dodajfote.pl/2017/10/04/wp_www_money_nastepny_artykul3a697e42d3508e68.png)

Zrzut ekranu 39:
![](https://s3.dodajfote.pl/2017/10/04/wp_o2_misioweopowiesci_widzet_po_prawejce46d5a8ab0fcf15.png)

Zrzut ekranu 40:
![](https://s3.dodajfote.pl/2017/10/04/wp_forgeofempire_jebunty_popup8b8731b2a698a4b7.png)

Zrzut ekranu 41:
![](https://s3.dodajfote.pl/2017/10/04/wp_dobreprogramy_panel_po_prawej6f4b131f6a748502.png)

Zrzut ekranu 42:
![](https://s3.dodajfote.pl/2017/10/04/wp_o264313fad32bca7c2.png)

Zrzut ekranu 43:
![](https://s3.dodajfote.pl/2017/10/04/wp_o2_26553c206f2ef4cb8.png)

Zrzut ekranu 44:
![](https://s3.dodajfote.pl/2017/10/04/wp_dom_dymek_i_home8f9bd2b76a3241e4.png)

Zrzut ekranu 45:
![](https://s3.dodajfote.pl/2017/10/04/wp_gwiazdy_dymek_i_home73aec515512a019c.png)

Zrzut ekranu 46:
![](https://s3.dodajfote.pl/2017/10/05/wp_fotoblogia_header_i_dymek75f9003103e9428e.png)

Zrzut ekranu 47:
![](https://s3.dodajfote.pl/2017/10/05/wp_m_sportowe_fakty1b82de47cff8f911.png)

Zrzut ekranu 48:
![](https://s3.dodajfote.pl/2017/10/05/wp_biztok_money_popup50056256db74f0eb.png)

Zrzut ekranu 49:
![](http://website.informer.com/thumbnails/280x202/k/komediowo.pl.png)

Zrzut ekranu 50:
![](https://s3.dodajfote.pl/2017/10/12/wp_mobile_header0527bc5358a37367.png)

**Comment by gomoku** [comment]
- zapomniałeś usunąć zdublowany `www.wp.pl###home-page-button, #newsfeed-player-column` - wiersz 400.
- przy okazji zauważyłem, że te grupy są umieszczane jedna pod drugą jak leci, bez składu i ładu - tzn. ani nie są wg alfabetu, ani wg. wielkości, trzeba zdecydować się na jakąś kolejność, ogarnąć to i trzymać się jej.

**Comment by blocker999** [comment]
@gomoku 

Poprawione, a co do kolejności to poprawie ale później, masz racje musi być też jasno i przejrzyście.

**Comment by gomoku** [comment]
OK, a gdy będziesz sortował grupy, to przy okazji popraw moją pomyłkę w sortowaniu w samej grupie, tzn skopiuj-wklej całą grupę jeszcze raz z pierwszego komentarza bo następujące filtry:
`fotoblogia.pl##.btn-comments.btn`
`fotoblogia.pl##.fixed-header--display.adsize_header.x-header.main-header-small.agregator-header:style(position: absolute!important;)`
umieściłem w złej kolejności alfabetycznej, ale odświeżyłem znowu pierwszy post - teraz jest już na pewno poprawnie posortowane.

**Comment by gomoku** [comment]
Trzeba zmienić etykietę na "potrzebna pomoc".

**Comment by gomoku** [comment]
Do dodania:
! http://www.wp.pl/mobile - zrzut ekranu 50
`www.wp.pl##header.header:style(position: absolute!important;)`

**Comment by hawkeye116477** [comment]
Jeszcze to do ponownego dodania -> `wp.pl,~www.wp.pl##div[class^="_"]:matches-css(position: relative):matches-css(display: inline-block):matches-css(vertical-align: -11px)`, nie wiem dlaczego @blocker999 to usunął, to jest od blokowania tego dodawania do strony startowej poddomen wp.

**Comment by gwarser** [comment]
@gomoku sprawdzałeś co `www.wp.pl###home-page-button, #newsfeed-player-column` ukrywa?

Sidebar musi być ukryty? `#newsfeed-player-column`? Tam jest radio(?), ankieta i jakieś skróty z ostatnich wydarzeń. Jest to z boku i nie zakrywa treści.
?

**Comment by gomoku** [comment]
https://github.com/azet12/PopupBlocker/issues/195#issuecomment-338487252

**Comment by hawkeye116477** [comment]
Ja to uznałem za natrętny element, ale jeśli uważacie, że to jest przydatne, to przywrócimy.

**Comment by blocker999** [comment]
Może się przyda:

http://reklama.wp.pl/gid,17925036,kat,1039565,title,dziejesiewgrupiewirtualnapolska,galeria.html#rekGal,4
