### ISSUE TITLE
alles-bhp.pl / greattrade.pl / szkolnaspizarnia.pl

### ISSUE THREAD

**Issue by gomoku** [azet12/PopupBlocker#178]
! usadzenie scrollującego headera: `alles-bhp.pl,greattrade.pl,szkolnaspizarnia.pl##.navbar-fixed-top.navbar-inverse.navbar:style(position: absolute!important;)`

![](https://s3.dodajfote.pl/2017/10/07/alles_bhp_headercc9f97fa333075c1.png)

![](https://s3.dodajfote.pl/2017/10/07/greattrade_headerd381fcc052cc643a.png)

![](https://s3.dodajfote.pl/2017/10/07/szkolnaspizarnia_header258a2a36c9169ed1.png)

**Comment by gomoku** [comment]
"zatwierdzone"

**Comment by hawkeye116477** [comment]
@gomoku Oj tam, szczegół 😛 .
