### ISSUE TITLE
wykop.pl

### ISSUE THREAD

**Issue by FadeMind** [azet12/PopupBlocker#18]
```
pl###lightbox
```
uniemożliwia duży podgląd zdjęć na wykop.pl

**Comment by FadeMind** [comment]
Fix:
```
~wykop.pl###lightbox
```
@azet12 @blocker999

**Comment by FadeMind** [comment]
Aktualizacja 2

```
###lightbox 
```
jest za silny. 

Uniemożliwia wyświetlenie grafiki na `wprost.pl` w artykułach.

**Comment by blocker999** [comment]
`~wykop.pl,~wprost.pl,pl###lightbox`

@FadeMind 

Może tak być?, ewentualnie zaproponuj inną regułe.

**Comment by FadeMind** [comment]
@blocker999 ok, w razie czego można rozbudować o kolejne domeny

**Comment by blocker999** [comment]
ok to aktualizuje
