### ISSUE TITLE
www.polityka.pl / www.politykainsight.pl

### ISSUE THREAD

**Issue by gomoku** [azet12/PopupBlocker#182]
Usadzenie scrollujących headerów - zrzuty ekranu 1 i 2:

`www.polityka.pl##.md-pc-access-menu.pc-access-menu_no-access:style(position: static!important;)`
`! www.politykainsight.pl##.start-v3-nav:style(position: static!important;)`

Tylko jeśli chodzi o ten drugi filtr, to on ma defekt, bo po usadzeniu headera znika pewien element z headera - zrzut ekranu 3 - tam gdzie kursor-łapka.

Czysto: 
! http://archiwum.polityka.pl
! http://komiks.blog.polityka.pl
! http://sklep.polityka.pl
! http://www.lesniczowkanibork.pl
! http://www.lista500.polityka.pl
! https://www.fiszkipolityki.pl

Zrzut ekranu 1:
![](https://s3.dodajfote.pl/2017/10/08/polityka_header5aa07652caee4ae8.png)

Zrzut ekranu 2:
![](https://s3.dodajfote.pl/2017/10/08/politykainsight.pl9acb4bc9b2a02318.png)

Zrzut ekranu 3:
![](https://s3.dodajfote.pl/2017/10/08/politykainsight_icon.plcdc1c0e9f9ed02c2.png)

**Comment by gomoku** [comment]
Można dodać pierwszy filtr, i ustawić etykietę "potrzebna pomoc"

**Comment by hawkeye116477** [comment]
`www.politykainsight.pl##.start-v3-nav:style(position: absolute!important;)`
