### ISSUE TITLE
[Grupa International Data Group Poland] idg.pl / idg.com.pl...

### ISSUE THREAD

**Issue by gomoku** [azet12/PopupBlocker#183]
https://pl.wikipedia.org/wiki/IDG_Poland

```
! usadzenie headera - zrzut ekranu 1
www.idg.com.pl##.menu:style(position: absolute!important;)
! https://www.idg.pl/kiosk - zrzut ekranu 2
www.idg.pl###top-header:style(position: static!important;)
www.idg.pl###body-page:style(margin-top: 0px!important;)
! coś problem z usadzeniem headera, bo fika - przykładowy zrzut ekranu 3
! www.computerworld.pl,www.cxo.pl,www.internetstandard.pl,www.pcworld.pl##.container-navbar:style(position: absolute!important;)

! usunięcie przewiń do góry - zrzut ekranu 4
seminaria.idg.pl,e-seminaria.pl##.scrollup

! https://hit.idg.com.pl - jakaś nie działająca strona
```

Kopiuj & wklej, posortowane alfabetycznie:
```
!
!
! IDG
seminaria.idg.pl,e-seminaria.pl##.scrollup
www.idg.com.pl##.menu:style(position: absolute!important;)
www.idg.pl###body-page:style(margin-top: 0px!important;)
www.idg.pl###top-header:style(position: static!important;)
```

Zrzut ekranu 1:
![](https://s3.dodajfote.pl/2017/10/09/idg_header7e2bd117a120b05a.png)

Zrzut ekranu 2:
![](https://s3.dodajfote.pl/2017/10/09/idg_kiosk_header1db24561a0ab1d1d.png)

Zrzut ekranu 3:
![](https://s3.dodajfote.pl/2017/10/09/idg_internetstandard_header0e241ed96a416647.png)

Zrzut ekranu 4:
![](https://s3.dodajfote.pl/2017/10/09/idg_seminatria_do_gorye228c4eb830ebac2.png)

**Comment by gomoku** [comment]
Ale tu jest problem , więc "potrzebna pomoc".

**Comment by hawkeye116477** [comment]
Mnie się wydaje, że raczej trzeba będzie zamknąć temat, bo @F4z już na jeden temat nie odpowiedział od 25 dni, to pewnie i nie odpowie na to, on ma po prostu lepsze zajęcia zapewne 😄 .
Z tym, że ta reguła -> `www.computerworld.pl,www.cxo.pl,www.internetstandard.pl,www.pcworld.pl##.container-navbar:style(position: absolute!important;)` trochę psuje układ strony. Tak będzie trochę lepiej -> `www.computerworld.pl,www.cxo.pl,www.internetstandard.pl,www.pcworld.pl##.container-navbar-fixed`, ale to z kolei spowoduje defekt - trzęsący się pasek ze scrollem i jak przewiniesz trochę i odświeżysz, to wtedy menu zniknie.

**Comment by gwarser** [comment]
`www.computerworld.pl##script:inject(abort-on-property-read.js, setHeaderService)` reszty domen nie patrzyłem.
Pewnie psuje, do sprawdzenia.

**Comment by hawkeye116477** [comment]
@gwarser Dzięki, na wszystkich domenach idg jest ok 😄 .

**Comment by gomoku** [comment]
Potwierdzam, jest ok.
