### ISSUE TITLE
ekino-tv.pl slider fix

### ISSUE THREAD

**Issue by FadeMind** [azet12/PopupBlocker#19]
```
~ekino-tv.pl,pl##center
```

**Comment by blocker999** [comment]
ok

**Comment by gwarser** [comment]
tu też psuje `http://audioksiazki.cba.pl/`

**Comment by blocker999** [comment]
ok, później zrobie poprawke

**Comment by blocker999** [comment]
dodane

**Comment by gwarser** [comment]
Ten `center` to chyba trochę zły pomysł - tak jak byś zablokował `b`.

`http://niewygodne.info.pl/artykul7/03538-Zakaz-zadluzania-szansa-na-niezaleznosc.htm`

**Comment by blocker999** [comment]
ok niewiem moge usunąć te `center` ale oco chodzi z tym `b`?

**Comment by gwarser** [comment]
Bo to tag html. `center` do wyśrodkowania, a `b` do **pogrubiania**

**Comment by FadeMind** [comment]
@blocker999  po prostu niektóre reguły zawarte w PopupBlocker są zbyt ogólne i blokują pożądaną treść na stronie. 
:smiley:

**Comment by blocker999** [comment]
Ok bardziej powszechne reguły pousuwam a reszte musze niestety zostawić bo stron jest wiele a ja mam mało czasu, choć często coś poprawiam.

Generalnie lepiej za dużo za zablokować niż się wk.....ć, zawsze możecie taki błąd odblokować w ubloku jako kosmetyczny lub dodać strone do wyjątków a najlepiej zgłosić tą stronke do mnie.
Wiem że zdarzają się błędy w moim filtrze choć już ograniczyłem reguły tylko do "pl" a duble będe usuwał, chciałbym znaleźć jakiś kompromis, no ale mam nadzieje że z czasem ten filtr będzie bliżej ideału.
