### ISSUE TITLE
reguła blokuje wejscie na fanpage

### ISSUE THREAD

**Issue by gzenio22** [azet12/PopupBlocker#193]
witam znalazłem regułke ktora przez przypadek blokuje przejscie do niekturych fanpagey po zwykłych linkach z opisu np  ► http://fb.com/techmaniachd

po kliknięciu w link wyskakuje okno blokady screen z potrzebnymi danymi ponizej 

![screenshot_2](https://user-images.githubusercontent.com/21177361/31562146-a45dc21a-b05a-11e7-8a47-65119746811d.png)

Jak widac na załączonym obrazku filtr znajduje sie w liscie socjalnej

**Comment by hawkeye116477** [comment]
@gzenio22 Czyli pomyliłeś adres.
