### ISSUE TITLE
Kompatybilność z Adblockiem

### ISSUE THREAD

**Issue by hawkeye116477** [azet12/PopupBlocker#194]
Reguły, które odblokowują scroll po schowaniu popupa nie działają na Adblocku/Adblock Plusie, a być może i na Adguardzie. Dlatego też może warto byłoby przenieść kłopotliwe reguły, które odblokowują scroll i chowają popup na nową listę „Popup Blocker Simplus - uzupełnienie dla uBlocka". 
Co o tym sądzicie?

**Comment by gomoku** [comment]
Hmm mi to obojętne, ale tak przy okazji jeśli już, to albo ja czegoś nie rozumiem albo nie wiem...bo np. takie ze stylem: `6krokow.pl###header:style(position: absolute!important;)`, których jest 236 na PopupBlocker (które dodatkowo czasami występują również w kombinacji z drugim filtrem) również nie działają pod ADP, więc pytanie jaka w tym logika, żeby przenosić tylko część niedziałających pod ADP? No bo jeśli mamy jeden koszyk z jabłkami i gruszkami, to jeśli chcemy je rozdzielić to rozdzielamy czyli wszystkie jabłka do jednego koszyka, a wszystkie gruszki do drugiego...więc chętnie chciałbym zrozumieć o co tu chodzi z takim częściowym podziałem. I przy okazji zauważyłem, że na głównej polskiej liście również jest 12 reguł `:style` nieprzeniesionych do listy "Uzupełnienie", czy ktoś to po prostu przeoczył?

**Comment by hawkeye116477** [comment]
@gomoku 
> bo np. takie ze stylem: 6krokow.pl###header:style(position: absolute!important;), których jest 236 na PopupBlocker (które dodatkowo czasami występują również w kombinacji z drugim filtrem) również nie działają pod ADP, więc pytanie jaka w tym logika, żeby przenosić tylko część niedziałających pod ADP? 
Chodzi mi głównie o reguły, które sprawiają problemy na Adblocku, jak np te, które blokują popupa i odblokowują scrolla, na Adblocku scroll się nie odblokuje, więc obydwie reguły powinny zostać raczej przeniesione.  Chociaż tak w sumie resztę też można byłoby przenieść.

> I przy okazji zauważyłem, że na głównej polskiej liście również jest 12 reguł :style nieprzeniesionych do listy "Uzupełnienie", czy ktoś to po prostu przeoczył?

Zapewne nie robią problemów na Adblocku, więc zostały na głównej.

**Comment by gomoku** [comment]
No teraz to jasno i klarownie wyjaśnione / albo mój umysł z rana bardziej wypoczęty.
Co do przenoszenia też innych reguł uBO np. tych `:style` o `:matches-css` to kwestia tego żeby AdBlock nie musiał tych reguł niepotrzebnie przetwarzać (bo mogą spowalniać, zajmować pamięć). 

A tu statystyki ilości reguł uBO:
```
PopupBlocker PLUS PL: 236 :style + 1 :matches-css = 237
POL: polskie filtry:   12 :style + 6 :matches-css =  18
```
Trzeba też wziąć pod uwagę ewentualną możliwość, że niektóre reguły trzeba będzie również przenieść w parze z regułą ADP (tak jak te pary usuwająca popup + naprawiająca scroll), bo po zabraniu tych uBO, te osamotnione ADP bez pary mogą powodować problemy np. jakieś scrollujące nagłówki, które wymagały 2 reguł do usadzenia (1 ADP i 1 uBO) mogą po zabraniu reguł uBO się nagle rozjechać itp. Chociaż póki co nie sprawdzałem tego dokładnie czy takie pary papużki nierozłączki występują w `:style` czy `:matches-css`, ale w pamięci coś mi świta, że niektóre nagłówki były trudne do usadzenia i wymagały 2 reguł, jedna np. usuwająca pasek z nagłówka (ADP), a druga usadzająca nagłówek (uBO), więc trzeba by to sprawdzić.

**Comment by blocker999** [comment]
@hawkeye116477 Wiem że niewszystko działa z adblockiem dlatego proponuję to zgłosić do twórcy tego programu no chyba że to inna konstrukcja  niż ublock ale i tak warto, przynajmiej będziemy jasno to wiedzieć, a tworzenie osobnej listy tylko dla adblocka niewchodzi w gre bo zaraz będzie trzeba do adguarda takową tworzyć a i pewnie do wielu innych blokerów.

@gomoku Masz inne lepsze pomysły oprócz przenoszenia ?

**Comment by hawkeye116477** [comment]
@blocker999 Nie ma co zgłaszać, Adblock po prostu nie obsługuje reguł :style(), jest mocno ograniczony. Także zrobię osobną listę z regułami, które działają tylko na uBlocku. 

> zaraz będzie trzeba do adguarda takową tworzyć a i pewnie do wielu innych blokerów.

No Adguard nie obsługuje reguł :style(), zamiast tego ma coś tam innego. A co do reszty blokerów to już żaden inny chyba nie potrafi zmieniać css stron. Także tylko uBlock i opcjonalnie Adguard.

**Comment by blocker999** [comment]
@hawkeye116477  Może warto oto ich poprosić by dodali obsługe :style(), a jak nie to dopisać że paczka jest kompatybilna z ublockiem a używanie jej z innymi blokerami może powodować problemy.

**Comment by hawkeye116477** [comment]
@blocker999 Okazuje się, że Adguard od jakiegoś czasu obsługuje :style(). A po co dopisywać? Nie lepiej przenieść niekompatybilne reguły do innej nowej listy? Tak w sumie to można, też zmienić ten napis `[Adblock Plus 2.0]` na `[uBlock Origin 1.14+]` wtedy ci co mają Adblocka, to nie będą mogli pobrać tego filtra, ale chyba lepiej umożliwić im częściowe korzystanie z listy niż wcale zabronić.
A była już prośba 3 lata temu, żeby dodali coś co by zmieniało css i nie wiem, może za 10 lat dodadzą , na razie to twierdzą, że od tego jest Stylish 😃  .
https://issues.adblockplus.org/ticket/756

Spokojnie, ja się przenoszeniem zajmę, ty nie musisz tego robić, jeśli ci się nie chce 😄 .
Jedynie problem będzie z regułami script:inject, bo Adguard ma coś tam innego, a uBlock raczej tego nie obsługuje, ale są jedynie 3 takie reguły na naszej liście.

**Comment by blocker999** [comment]
@hawkeye116477 Skoro była takowa prośba do adblocka 3 lata temu, to masz racje niema co sie ponawiać.

Gdzie chcesz przenosić te reguły do nowej paczki?, poco uszkadza to ublocka?, niewiem ale ja od początku chciałem tworzyć jedną paczke a nie rozdrabniać się.

**Comment by hawkeye116477** [comment]
@blocker999 uBlocka nie uszkadza, ale ci co mają Adblocka to mają zablokowane scrolle, bo blokujemy popupy (dotyczy to gdzieś ok.20 stron) dlatego reguły, które powodują problemy wypadałoby przenieść do osobnej listy uzupełniającej, tak jak jest to u Majka. Natomiast w przypadku Adguarda, to mają tylko problem na nawozy.eu, bo tam odblokowaliśmy scroll przy pomocy script:inject, a Adguard ma coś tam innego zamiast tego.

Tak jak pisałem możemy zmienić napis na uBlock i powiedzieć, że nie wspieramy Adblocka, bo jest ograniczony, dziadowski i co raz więcej osób używa uBlocka, a Adguarda nie wspieramy, bo jest zamkniętoźródłowy. Ale chyba jednak lepiej dać wsparcie dla większej liczby osób, może dzięki temu pojawi się tu więcej testerów/zgłaszających.

**Comment by blocker999** [comment]
@hawkeye116477 

Dobra, racja paczka pasuje do ublocka ale każdy może zniej skorzystać, więc raczej zostawiamy a tą 
nową paczke do adblocka zrób jak chcesz ale nielicz namnie.

**Comment by hawkeye116477** [comment]
@blocker999 Ok, ja się tym sam zajmę, ale ja nie będę robił nowej paczki dla Adblocka, tylko dla uBlocka i ewentualnie dla Adguarda, z głównej powycinam to co sprawia problemy i przeniosę do nowej listy oraz ewentualnie przemyślę też kwestię przeniesienia reszty specyficznych dla uBlocka.

**Comment by gomoku** [comment]
Nie da się mieć 2 w 1, czyli zjeść ciastko i mieć ciastko, czyli nie da się mieć1 listy obsługującej w 100% kilka adblockerów, bo różne adblockery mają różne składnie, które nie są w 100% kompatybilne między sobą, co powoduje problemy, więc trzeba się zdecydować:

- wariant a) jedna pojedyncza lista pod jeden najlepszy adblocker
- wariant b) osobne listy - 1 główna pod ADP i osobne uzupełnienia pod uBO i AG

Więc trzeba sobie odpowiedzieć na pytanie czy lista ma działać pod jednym adblockerem (wtedy wariant a) czy pod kilkoma (wtedy wariant b), a jeśli pod jednym to pod którym - najpopularniejszym ADP czy najlepszym uBO, bo niestety ale, chociaż zazwyczaj to nie zawsze najpopularniejszy oznacza najlepszy i w adblockerach tak właśnie to wygląda, że ADP do dupy się nadaje (chociaż ma swoje plusy).

**Comment by hawkeye116477** [comment]
> wariant b) jest lepszy, chociaż ma skutki uboczne tak jak @blockeer999 wspomniał - rozdrobnienie, no ale coś za coś i na coś trzeba się zdecydować, przyjąć jakąś ideę.

Zgadza się, ja już się zdecydowałem na wariant B i raczej przy tym pozostaniemy. Na razie przeniosłem reguły robiące problemy ze scrollem, a za resztę może jutro się wezmę. Listę specjalną dla Adguarda też wkrótce zrobię, ale to by trzeba się poradzić eksperta co do 3 reguł `script:inject`.

**Comment by gomoku** [comment]
A wiesz co,  tak mnie trochę "olśniło" dzisiaj rano, i tak się zacząłem zastanawiać nad pewną sprzecznością pomiędzy twoim rozumowaniem a praktycznym działaniem, bo:
 
- z jednej strony piszesz, że ADP jest do dupy (nie zaprzeczam i sam się z tym zgadzam), i że wszyscy się powinni przesiąść i przesiądą niedługo na uBO, więc zgodnie z tą myślą raczej powinieneś iść w kierunku udupienia ADP i promowania uBO, czyli jedna lista pod uBO a jeśli komuś pod ADP coś nie działa to **dobrze bo szybciej przerzuci się ze ścierwa ADP na uBO**, przecież zdaje się, że właśnie o to ci (oraz zresztą mi i blockerowi też) chodzi?

- z drugiej strony robisz przeciwnie, rozdzielasz listy i wspierasz ADP i hamujesz jego udupianie, oraz hamujesz promowanie uBO (przesiadkę z ADP na uBO)

Jeśli mógłbyś wyjaśnić tę sprzeczność...

**Comment by hawkeye116477** [comment]
@gomoku A skąd tam wiesz, może jakbyśmy zrobili tylko listę dla uBlocka, to zaraz by konkurencja się pojawiła. Na ciastka już nam konkurencję robią -> http://pliki.wojtekmaj.pl/ciasteczka.txt 😃 .

> może martwisz się, że jeśli pod ADP z listą będą problemy, to ludzie używający ADP zrezygnują z listy

Skoro deklarujemy to już w pierwszym wierszu, że lista jest kompatybilna z Adblockiem, to tak powinno raczej być. Można niby napisać, że nie gwarantujemy poprawnego działania listy na Adblocku, że lista działa w pełni poprawnie jedynie na uBlocku. Tylko ciekawe czy ktoś to w ogóle przeczyta czy raczej wkurzą się i zrezygnują 😄 . A tak właściwie to ciekawe ile osób korzysta z Popup Blockera.
A co z Adguardem, nie wspieramy, bo jest zamknięto-źródłowy, a my jesteśmy zwolennikami open-source 😃 ?

**Comment by blocker999** [comment]
@hawkeye116477 W tym wypadku konkurencji nigdy zawiele.

Niewiem ale ten dzisiejszy komentarz @gomoku  mnie w 100% przekonuje, dlatego proponuje to oczym wczoraj pisałeś: 

"Tak w sumie to można, też zmienić ten napis [Adblock Plus 2.0] na [uBlock Origin 1.14+] wtedy ci co mają Adblocka, to nie będą mogli pobrać tego filtra" i zmienią stare nawyki.

". A tak właściwie to ciekawe ile osób korzysta z Popup Blockera "
Bardzo ciekawe ale jak to zmierzyć ?

**Comment by hawkeye116477** [comment]
Ok, macie rację, w takim razie cofnę zmiany, usunę [Adblock Plus 2.0] i dodam na początku [uBlock Origin 1.14+] i [AdGuard 2.7+]. Na AdGuardzie powinno być wszystko ok, oprócz tego, że filmiki będą latały. Jeden filtr z script:inject mógł powodować problem, ale okazuje się, że zamiast tego można po prostu zablokować skrypt blokujący scroll filtrem sieciowym 😄 . Najciekawsze jest to, że w AdGuard dla Chromium te filtry `:style()` nie działają, a na Waterfoksie działają, zapewne to jakiś bug.

**Comment by gomoku** [comment]
>  @hawkeye116477: A skąd tam wiesz, może jakbyśmy zrobili tylko listę dla uBlocka, to zaraz by konkurencja się pojawiła.

W sumie też racja, możliwe, nie pomyślałem o tym, chociaż z drugiej strony:
- i tak jakieś 80% filtrów na liście uBO, jest kompatybilnych z ADP
- jeśli się pojawi konkurencja to wtedy można będzie podzielić listę w razie czego, póki jej nie ma to raczej nie trzeba się z tym śpieszyć

**Comment by hawkeye116477** [comment]
@gomoku 
> i tak jakieś 80% filtrów na liście uBO, jest kompatybilnych z ADP (no chyba, że zmieni się nagłówek co proponujecie i tym samym lista będzie bezużyteczna pod ADP)

Już dokonałem tej zmiany, ci co używają czegoś innego niż AdGuard i uBlock, to od teraz nie mogą korzystać z Popup Blockera 😄 .

**Comment by gomoku** [comment]
Spoko, a przy okazji edytowałem post w momencie, w którym pisałeś swojego, zobacz na mój post na sam dół bo dodałem przed chwilą.

**Comment by hawkeye116477** [comment]
@gomoku O tym to ja wiem, kiedyś z tego korzystałem, tyle, że te statystyki dotyczą jedynie plików w Releases (https://github.com/azet12/PopupBlocker/releases), a my tam nic nie mamy.

**Comment by gomoku** [comment]
OK, tak tylko zaproponowałem na szybko na kolanie taki link, a sam się w niego nie zagłębiałem, no to szkoda, że nie da się mierzyć pobrań, w takim razie Github trochę w kulki leci no nie?

**Comment by gomoku** [comment]
Pomimo, że ogólnie jestem za uBO i go sam używam, to jednak mnie znowu "olśniło" i stwierdziłem, że tak czy inaczej lista powinna obsługiwać też ADP, popieram inicjatywę @hawkeye116477 i stworzenie listy uzupełniającej, i szkoda, że namieszałem, bo już było fajnie przeniesione, no ale za drugim razem powinno pójść jeszcze szybciej...

**Comment by blocker999** [comment]
@hawkeye116477 Dobra, decyzja należy do Ciebie

**Comment by hawkeye116477** [comment]
Ok, w takim razie chyba poprawimy jeszcze raz kompatybilność i dodamy listę uzupełniającą dla uBlocka. Chyba, że @blocker999 jeszcze nam coś powie, wypowie się w tej sprawie.

**Comment by hawkeye116477** [comment]
Ok, poprawiłem po raz kolejny kompatybilność i dodałem listę uzupełniające dla uBlocka i Adguarda. Listę uzupełniającą zrobiłem wspólną dla uBlocka i AdGuarda, gdyż tylko 1 reguła nie działa na AdGuardzie, a ona stopuje latanie filmików na polki.pl, więc raczej nie opłaca się robić kolejnej tylko dla AdGuarda.

**Comment by gomoku** [comment]
Hmmm lista główna 868 filtrów, uzupełniająca 642, ciekawe czy jeśli uzupełniająca prześcignie główną w ilości filtrów, to czy główna będzie dalej główną...
