### ISSUE TITLE
wp.pl

### ISSUE THREAD

**Issue by gwarser** [azet12/PopupBlocker#195]
`www.wp.pl###home-page-button, #newsfeed-player-column`
ukrywa wszystkie panele po prawej, na głównej stronie - jesteś pewny, że to ma być ukryte?

**Comment by blocker999** [comment]
Reguły są z #171 utworzonego przez @gomoku, więc może razem wypracujecie kompromis.

@hawkeye116477 rzuć okiem, prosze

**Comment by gomoku** [comment]
@blocker999 sorry ale to nie moja reguła, ja jej nie dodałem, ona już była na liście, ja ją jedynie przeniosłem w inne miejsce, czyli do grupy, więc może Ty lub @hawkeye116477 (w każdym bądź razie ten kto ją dodał) wypracuje jakiś kompromis z @gwarser 'em

https://github.com/azet12/PopupBlocker/issues/171#issue-262816127

```
! Usadzenie Grupy Wirtualna Polska Holding
! najpierw przeniesiemy do grupy to co jest w PopupBlockerze (a z PopupBlockera trzeba usunąć):
www.wp.pl###home-page-button, #newsfeed-player-column 
! koniec
```

> ! najpierw przeniesiemy do grupy to co jest w PopupBlockerze

**Comment by gomoku** [comment]
@gwarser tu masz sprawców...https://github.com/azet12/PopupBlocker/issues/36

**Comment by blocker999** [comment]
@gomoku Bardzo Cię przepraszam za niesłuszne oskarżenie no i dzięki za odświeżenie pamięci.

@gwarser Tak czy siak poczekam na @hawkeye116477
