### ISSUE TITLE
[Grupa PWN]

### ISSUE THREAD

**Issue by gomoku** [azet12/PopupBlocker#196]
https://pl.wikipedia.org/wiki/Grupa_kapita%C5%82owa_PWN
http://www.pwn.pl/

```
! Usadzenie Grupy PWN
! Generalnie można dodawać wszystkie filtry do listy, bo wszystko ogarnięte, z tym że nie zamykać
! wątku i dodać etykietę "potrzebna pomoc" bo z jedną stroną jest problem (dopobrania.pwn.pl), tak 
! poza tym kilka filtrów już jest na liście, więc trzeba będzie je usunąć z listy, 
! czyli wiersze: 295,286,297, 406,407 (a ja je już dodałem do grupy):
sjp.pwn.pl###content.container:style(margin-top: 0px!important;) 
sjp.pwn.pl###floater 
sjp.pwn.pl###search-bar:style(position: static!important;) 
www.ravelo.pl##.searchRow:style(position: absolute!important; margin-top: 0px!important;) 
www.ravelo.pl###modalAlertMethodNL 
! koniec

! początek scalonej grupy
! niektóre z przeniesionych filtrów, (reszta czyli filtry sjp.pwn.pl są w środku grupy)
www.ravelo.pl##.searchRow:style(position: absolute!important; margin-top: 0px!important;) 
www.ravelo.pl###modalAlertMethodNL 
! filtr dodany - usadzenie scrollującego panela po prawej - zrzut ekranu 1
www.ravelo.pl##.mobileHiden

! usunięcie jebutnego popupa na wejściu, zrzuty ekranu 2,3
sjp.pwn.pl,slowniki.pwn.pl###floater
www.ibuk.pl###login_box_placeholder

! usadzenie scrollującego nagłówka na 11 stronach - zrzuty ekranu 4-15
www.pwn.pl###menu_rozwijane:style(position: absolute!important;)
encyklopedia.pwn.pl,sjp.pwn.pl,slowniki.pwn.pl,translatica.pl###search-bar:style(position: static!important;)
encyklopedia.pwn.pl,sjp.pwn.pl,slowniki.pwn.pl,translatica.pl###content:style(margin-top: 0px!important;)
tlumaczenia-pwn.pl##.header_2.header_wrapper:style(position: static!important;)
ksiegarnia.pwn.pl,www.pwn.pl##.navbar-fixed-top:style(position: absolute!important;)
! tu trochę problem, bo header usadziłem, ale panel menu po lewej (.side-nav) coś dziwnie się usadza
! dopobrania.pwn.pl, (dodać wyżej do ##.navbar-fixed-top)
! dopobrania.pwn.pl##.side-nav:style(position: static!important;)
www.vulcan.edu.pl##header:style(position: absolute!important;)
www.vulcan.edu.pl###overHomeSlider:style(position: absolute!important; height: 345px!important;)
www.forumzdrowia.pl###search-panel:style(position: static!important;)
www.forumzdrowia.pl##.header-v4:style(position: static!important;)
oxford.pwn.pl###header:style(position: static!important;)
beztajemnic.pwn.pl##.top-bar:style(position: static!important;)
beztajemnic.pwn.pl###undefined-sticky-wrapper:style(display: block!important; opacity: 1!important;)

! usunięcie przewiń do góry - zrzut ekranu 16, 9
encyklopedia.pwn.pl,sjp.pwn.pl,translatica.pl###topcontrol
www.vulcan.edu.pl###b_gora

! usadzenie scrollującego panelu po lewej  - zrzut ekranu 17
www.rozpisani.pl##[class^="menuboth floatingmenu"]:style(width: auto!important; position: absolute!important; top: auto!important;)

! scrollujący panel-widżet-koszyk po prawej  - zrzut ekranu 18
www.lideria.pl##.slidingbasket

! facebook social widżet scrollujacy po prawej - zrzut ekranu 13, poszedł także na social listę >> 
! https://github.com/MajkiIT/polish-ads-filter/issues/4079
www.forumzdrowia.pl###face-slider

! facebook social przycisk statyczny na nagłówku poszedł tylko na listę social >> 
! https://github.com/MajkiIT/polish-ads-filter/issues/4078
```

Kopiuj-wklej:
```
!
!
! PWN
beztajemnic.pwn.pl###undefined-sticky-wrapper:style(display: block!important; opacity: 1!important;)
beztajemnic.pwn.pl##.top-bar:style(position: static!important;)
encyklopedia.pwn.pl,sjp.pwn.pl,slowniki.pwn.pl,translatica.pl###content:style(margin-top: 0px!important;)
encyklopedia.pwn.pl,sjp.pwn.pl,slowniki.pwn.pl,translatica.pl###search-bar:style(position: static!important;)
encyklopedia.pwn.pl,sjp.pwn.pl,translatica.pl###topcontrol
ksiegarnia.pwn.pl,www.pwn.pl##.navbar-fixed-top:style(position: absolute!important;)
oxford.pwn.pl###header:style(position: static!important;)
sjp.pwn.pl,slowniki.pwn.pl###floater
tlumaczenia-pwn.pl##.header_2.header_wrapper:style(position: static!important;)
www.forumzdrowia.pl###face-slider
www.forumzdrowia.pl###search-panel:style(position: static!important;)
www.forumzdrowia.pl##.header-v4:style(position: static!important;)
www.ibuk.pl###login_box_placeholder
www.lideria.pl##.slidingbasket
www.pwn.pl###menu_rozwijane:style(position: absolute!important;)
www.ravelo.pl###modalAlertMethodNL 
www.ravelo.pl##.mobileHiden
www.ravelo.pl##.searchRow:style(position: absolute!important; margin-top: 0px!important;) 
www.rozpisani.pl##[class^="menuboth floatingmenu"]:style(width: auto!important; position: absolute!important; top: auto!important;)
www.vulcan.edu.pl###b_gora
www.vulcan.edu.pl###overHomeSlider:style(position: absolute!important; height: 345px!important;)
www.vulcan.edu.pl##header:style(position: absolute!important;)
```

! tu czysto:
! http://akademiarozwoju.pwn.pl
! http://czytampolskie.pl
! http://diagnoza.wszpwn.com.pl
! http://feynman.pwn.pl
! http://it.pwn.pl
! http://ksiegarniaszkolnapwn.pl
! http://ksiegarnienaukowe.pl
! http://laboratorium.pwn.pl
! http://mikom.com.pl
! http://myslec.pwn.pl
! http://niezbednikakademicki.pwn.pl
! http://pe.wszpwn.com.pl
! http://poleng.pl
! http://przedszkole.pwn.pl
! http://szkolapodstawowa.pwn.pl
! http://www.dwpwn.pl
! http://www.instytutpwn.pl
! http://www.wszpwn.com.pl
! https://www.azymut.pl/pl
! https://www.biblionetka.pl
! https://www.supermemo.pl

Zrzut ekranu 1:
![](https://s3.dodajfote.pl/2017/10/22/pwn_ravelo_panel_po_prawej3a66cad359b719fe.png)

Zrzut ekranu 2:
![](https://s3.dodajfote.pl/2017/10/22/pwn_sjp_popup_header0bab605365582447.png)

Zrzut ekranu 3:
![](https://s3.dodajfote.pl/2017/10/22/pwn_ibuk_popup558de63aebf247ef.png)

Zrzut ekranu 4:
![](https://s3.dodajfote.pl/2017/10/22/pwn_www_headerd9412d211c6063db.png)

Zrzut ekranu 5:
![](https://s3.dodajfote.pl/2017/10/22/pwn_encyklopedia_header68a6b8037a06ef63.png)

Zrzut ekranu 6:
![](https://s3.dodajfote.pl/2017/10/22/pwn_sjp_headerad9ec34e03a571e9.png)

Zrzut ekranu 7:
![](https://s3.dodajfote.pl/2017/10/22/pwn_sjp_header_202d6a490e42d2ade.png)

Zrzut ekranu 8:
![](https://s3.dodajfote.pl/2017/10/22/pwn_translantica_headerd985423e4ff204a7.png)

Zrzut ekranu 9:
![](https://s3.dodajfote.pl/2017/10/22/pwn_tlumaczenia_headerabd14a8a5e0fc3b7.png)

Zrzut ekranu 10:
![](https://s3.dodajfote.pl/2017/10/22/pwn_ksiegarnia_header9c07e153e3c521b0.png)

Zrzut ekranu 11:
![](https://s3.dodajfote.pl/2017/10/22/pwn_do_pobrania_headerf81c032f7afe6b9f.png)

Zrzut ekranu 12:
![](https://s3.dodajfote.pl/2017/10/22/pwn_vulcan_header_to_topdc771598d0942b33.png)

Zrzut ekranu 13:
![](https://s3.dodajfote.pl/2017/10/22/pwn_forumzdrowia-_header_social9a0c47d6b05b1ce8.png)

Zrzut ekranu 14:
![](https://s3.dodajfote.pl/2017/10/22/pwn_oxford_headerffe62218582e9c81.png)

Zrzut ekranu 16:
![](https://s3.dodajfote.pl/2017/10/22/pwn_to_top5eb15c3683ff6b56.png)

Zrzut ekranu 17:
![](https://s3.dodajfote.pl/2017/10/22/pwn_rozpisani_panel_po_lewejce9a8bd58e0b0e99.png)

Zrzut ekranu 18:
![](https://s3.dodajfote.pl/2017/10/22/pwn_lideria_koszyk_po_praweje233f212ea68d5c8.png)

**Comment by gwarser** [comment]
Moglibyście pisać dokładnie do czego "potrzebna pomoc", bo się nie mogę połapać o tej porze :)

**Comment by hawkeye116477** [comment]
@gwarser Ok, chodzi o to:

> ! tu trochę problem, bo header usadziłem, ale panel menu po lewej (.side-nav) coś dziwnie się usadza
> ! dopobrania.pwn.pl, (dodać wyżej do ##.navbar-fixed-top)
> ! dopobrania.pwn.pl##.side-nav:style(position: static!important;)

**Comment by gwarser** [comment]
Nie widzę problemu.

**Comment by hawkeye116477** [comment]
@gwarser Problem jest taki, iż @gomoku chce usadzić panel menu po prawej, ale po użyciu filtra -> dopobrania.pwn.pl##.side-nav:style(position: static!important;), ten panel oraz inne elementy znikają.

**Comment by gwarser** [comment]
```
dopobrania.pwn.pl##.navbar-fixed-top:style(position: absolute!important;)
dopobrania.pwn.pl##.side-nav:style(position: absolute!important; bottom: auto!important;)
```

`bottom`!

**Comment by hawkeye116477** [comment]
@gwarser Działa, dzięki
