### ISSUE TITLE
orange.pl

### ISSUE THREAD

**Issue by FadeMind** [azet12/PopupBlocker#20]
```
##.box:nth-of-type(2)
```
@blocker999 ta reguła blokuje treść w wyskakujących dynamicznie ładowanych boxach w domenie orange.pl

**Comment by FadeMind** [comment]
@blocker999 
```
~orange.pl,pl##.box:nth-of-type(2)
```
Nie działa.
`https://www.orange.pl/moj_orange`

**Comment by blocker999** [comment]
chyba dotam tylko adres z przodu ( z kąd to wziełem tzn `##.box:nth-of-type(2`) ) a orange usune, chyba tak powinno być bez problemowo, co o tym sądzisz?

**Comment by FadeMind** [comment]
```
##.box:nth-of-type(2)
```
Jest bardzo ogólny i po prostu psuje niektóre strony.  W tym przypadku orange. Jeżeli chcesz takiego formatu użyć na jakiejś specyficznej stronie to należy zdefiniować dokładnie adresy, których ta reguła dotyczy (a nie dodawać wyjątki - białe listy).

**Comment by blocker999** [comment]
Ok, tak zrobie w tym przypadku jak i poprawie podobne w liście ale zaktualizuje to pewnie wieczorem.

**Comment by blocker999** [comment]
Poprawione

**Comment by FadeMind** [comment]
@blocker999 see: https://github.com/azet12/PopupBlocker/commit/626f3e72409cdbd2c1e93007e983285c43259fdc#commitcomment-20442982
