### ISSUE TITLE
kiep.pl

### ISSUE THREAD

**Issue by hawkeye116477** [azet12/PopupBlocker#201]
Po zastosowaniu filtru `kiep.pl##.popup` jest problem, cała strona jest przezroczysta. 
@F4z Możesz zerknąć czy da się coś z tym zrobić?

**Comment by F4z** [comment]
Sprawdź proszę:
`kiep.pl##.container:style(opacity: 1!important;)`
`kiep.pl##.navbar-nav:style(opacity: 1!important;)`
albo tak
`kiep.pl##[style*="opacity: 0.3;"]:style(opacity: 1!important;)`

Ewentualnie jeszcze jakoś inaczej, ale to już jak tam uważasz :)

**Comment by hawkeye116477** [comment]
@F4z Dzięki 😄 .
