### ISSUE TITLE
sport.pl

### ISSUE THREAD

**Issue by hawkeye116477** [azet12/PopupBlocker#202]
http://www.sport.pl/F1/7,96296,22597098,formula-1-robert-kubica-otrzymal-propozycje-kontraktu-od-williamsa.html
@F4z @gwarser Poradzicie coś na latające filmiki na tej stronie?

**Comment by gwarser** [comment]
Działa to na filmiki reklamowe `*$websocket,domain=sport.pl` ?

**Comment by hawkeye116477** [comment]
@gwarser Chodziło mi o to, żeby player usadzić. A ta reguła co próbowałeś, to co z nią jest nie tak, bo u mnie jest ok? U mnie wszystkie 3 reguły działają poprawnie, no chyba, że coś tam się psuje, a ja nie zauważyłem.

**Comment by gwarser** [comment]
Pierwsza nie działała wcale (choć niby dobra), druga blokowała autoplay (więc myślałem że wykrzacza cały skrypt).

**Comment by gwarser** [comment]
Teraz działa. Coś musiałem namieszać.

**Comment by hawkeye116477** [comment]
Ok, czyli druga jest najlepsza.

**Comment by hawkeye116477** [comment]
@gwarser A co do tych filmików reklamowych, to tutaj są jakieś reklamowe i gdzie one są?

**Comment by gwarser** [comment]
Przed wywiadem. Ale coś mi ten filtr przestał chyba działać.

**Comment by hawkeye116477** [comment]
@gwarser A no tak, czasem reklamy się pojawiają przed filmikiem. Na Waterfoksie to `*$websocket,domain=sport.pl` nie działa.

**Comment by gwarser** [comment]
Firefox ma buga. Websockety są widziane jako beihind-the-scene.
Przed websocketem łączy się chyba do `https://a.uzekrs.com` - później sprawdzę czy da się coś zrobić.

**Comment by F4z** [comment]
Jeśli się nie mylę, to oni korzystają z "uponit" - `http://static.gazeta.pl/static/video/playerjs/deploy/app/n3n12/js/player.jsgz` więc może ta reguła zablokuje te reklamy:
`video.gazeta.pl##script:inject(abort-on-property-write.js, upManager)`
