### ISSUE TITLE
fokusfashion.com

### ISSUE THREAD

**Issue by hawkeye116477** [azet12/PopupBlocker#205]
@blocker999 Takie widgety z ocenami sklepów też blokować?
![screenshot_20171105_124945](https://user-images.githubusercontent.com/19818572/32414475-de9295da-c227-11e7-881b-745705b078f6.png)
`||widgets.trustedshops.com/js/*$script`

Mam też pytanie do specjalisty zwanego @gwarser. Trzeba usadzić menu rejestracji i koszyka, ale wtedy trzeba byłoby dodać bardzo długie reguły:
```
fokusfashion.com###menu_additional_wrapper:style(position: static!important; top: 0px!important; right: 0px!important; background: none!important; border: 0px!important; margin-right: 0px!important; margin-top: 0px!important; box-shadow: none!important; border-radius: 0px!important;)

fokusfashion.com###menu_basket_box:style(position: absolute!important; top: 0px!important; right: 0px!important; background: none!important; border: 0px!important; margin-right: 0px!important; margin-top: 0px!important; width: auto!important; height: auto!important; box-shadow: none!important; border-radius: 0px!important;)
```
Czy nie dałoby radę zrobić do tego coś krótszego/wydajniejszego?

**Comment by blocker999** [comment]
@hawkeye116477 Tak to też oraz wszelkie obrazki po bokach nieumieją w dogodny sposób zrobić strony to już ich problem ja tylko sprzątam ten bajzel.

**Comment by hawkeye116477** [comment]
Ok, natomiast co do tego usadzania to rozumiem, że nie ma lepszego sposobu specjalisto @gwarser?

**Comment by gwarser** [comment]
fokusfashion.com##script:inject(abort-on-property-read.js, init_login_scroll)
fokusfashion.com##script:inject(abort-on-property-write.js, basket_makefloat)

**Comment by hawkeye116477** [comment]
@gwarser Dzięki.

**Comment by gomoku** [comment]
> @hawkeye116477: `||widgets.trustedshops.com/js/*$script`

- 1_ nie wiem czy przy tworzeniu PopupBlocker brana jest wpierw pod uwagę lista Fanboy’s Enhanced Tracking List, ale jeśli tak to już jest na niej filtr na ten widżet: `||widgets.trustedshops.com^$third-party`
- 2_ jeśli nie jest brana pod uwagę to tak czy inaczej należy się zastanowić dlaczego dali filtr jaki dali, to znaczy a) na całą domenę i b) blokujący wszystko a nie tylko skrypty, bo może też lepiej taki dać (a może i nie), 

- 3_ natomiast jeśli zostać na skrypcie @hawkeye116477 'a:
`||widgets.trustedshops.com/js/*$script` to zastanawiam się dlaczego nie tak
`||widgets.trustedshops.com/js/*.js` skoro jest krótsze o 4 znaki

**Comment by hawkeye116477** [comment]
Ok, skoro tak u nich jest, to zamienię.
A co do filtrów z script:inject

**Comment by hawkeye116477** [comment]
@gomoku Ok, skoro tak u nich jest, to zamienię.
A co do tych filtrów usadzających, to już niech się @gwarser wypowie.
Jest jeszcze pewna sprawa, na AdGuardzie filtry script:inject nie działają, więc może jednak lepiej byłoby je zamienić na te ze style.

**Comment by gwarser** [comment]
To jest tylko kwestia tego, który filtr ci łatwiej napisać. Nie ma sensu spędzać nad tym zbyt dużo czasu. Jak ktoś zgłosi, że nie działa, albo spowalnia, to wtedy można się pobawić.

**Comment by gwarser** [comment]
X, Y, X:
```
Average (valid): 3643.57 ms (11/12 iterations)  Last reload: 3785.09 ms
Average (valid): 3939.85 ms (11/16 iterations)  Last reload: 4017.20 ms
Average (valid): 3890.19 ms (11/16 iterations)  Last reload: 4918.18 ms
```

Nie ma sensu.

**Comment by gomoku** [comment]
Tylko jak cię rozszyfrować..może po kolei:

> X, Y, X

Hmm...nie X, Y, Z?

Rozumiem, że te litery oznaczają testy: bez filtrów, z jedną parą filtrów, z drugą parą filtrów.

Tylko jeśli byłbyś łaskaw napisać:
- a) które testy to które litery
- b) jaka przeglądarka
- c) czym i jak mierzyłeś czas

Ja tymczasem odświeżyłem swój poprzedni komentarz o wszystkie informacje, czekam na to samo, i będzie można szukać przyczyny rozbieżności wyników.

**Comment by gwarser** [comment]
HAHA :) Ślepy test.
Zestaw X, Y, jeszcze raz X. Specjalnie oznaczyłem XY, żeby nie było widać który jest "szybszy". Powtórzenie pierwszego testu żeby wyeliminować efekt "wygrzewania". Przeglądarka, system itd. - każdy ma inny. Narzędzie http://www.raymondhill.net/ublock/pageloadspeed.html Nie mam czasu na takie zabawy. Powinieneś zrobić swój fork listy. Reklamowałbyś go - "Tylko u mnie najszybsze sweterki!" :D

**Comment by gomoku** [comment]
To co zrobiłem ja:
- przeprowadziłem więcej testów - razem już 5 testów (odświeżyłem swój post) i w dalszym ciągu w zdecydowanej większości przypadków na filtrach `inject` strona ładuje się zdecydowanie najszybciej
- podałem dokładne szczegóły

To co zrobiłeś ty:
- przeprowadziłeś 1 test
- nie podałeś żadnych szczegółów, zwłaszcza, że powoływałeś się na narzędzie od goryla w dokumentacji którego: http://www.raymondhill.net/ublock/pageloadspeed-details.html jest wyraźnie wskazane, żeby podać szczegóły, a więc z jednej strony powołujesz się na narzędzie a z drugiej strony jednocześnie się do niego w pełni nie stosujesz:

> When you share the results, you should provide all the information:
> 
>     Browser, version, relevant settings (click-to-play, block 3rd-party cookies, etc.)
>     Blocker, version, filter lists, settings.
>     Which URL was benchmarked.
>     Disclose the whole average result of the benchmark, for example: Average (valid): 832.01 ms (10/13 iterations).
>     Etc. 

- na koniec wyskoczyłeś z ironią o sweterkach, może dlatego, że ci się mózg jeszcze dobrze nie "wygrzał"...bo efekt "wygrzewania" to jest ale w słuchawkach, no chyba, że jednak jest i w testach ale to musiałbyś podać jakieś szczegóły, podobnie jak i szczegóły odnoście samego testu.

Póki co jasno widać, że to ja podchodzę poważnie do kwestii i podaję szczegóły, podczas gdy ty urządzasz sobie zabawy, nie podając żadnych szczegółów lub skąpe, więc zastanawiam się dlaczego twierdzisz, że jest odwrotnie, że to ja urządzam zabawy...

**Comment by gwarser** [comment]
>przeprowadziłem więcej testów...

Najwyraźniej ci się nudzi i masz dużo wolnego czasu.

>To co zrobiłeś ty:

Pokazałem, że nie ma żadnego problemu.

>że ci się mózg jeszcze dobrze nie "wygrzał"

xD
Chodzi o to jak pracuje interpreter js. Częściej wykonywany kod jest bardziej optymalizowany. Plus różnego rodzaju cache.

>Póki co jasno widać, że to ja podchodzę poważnie

Ale nie porofesionalnie, bo zmarnowałeś już dwa dni goniąc za czymś czego nie ma.

**Comment by gomoku** [comment]
> Najwyraźniej ci się nudzi i masz dużo wolnego czasu.

Albo ty za mało, żeby wykonać wystarczająco dużo testów i podać szczegóły, tylko wtedy lepiej w ogóle się za to nie zabierać.

> Pokazałem, że nie ma żadnego problemu.

Za pomocą:
- 1 testu
- na 1 narzędziu 
- na nie wiadomo jakiej 1 przeglądarce 
- na nie wiadomo jakich listach filtrów
- na nie wiadomo jakim łączu
- nie wiadomo jakim procesorze

A jak pokazałem, że jest problem za pomocą:
- 5 testów
- na 2 narzędziach
- na 2 wiadomo jakich przeglądarkach
- na wiadomo jakich listach filtrów
- na wiadomo jakim łączu
- na wiadomo jakim procesorze
- i na wielu innych wiadomo jakich ustawieniach

Być może problem jest większy na Firefoxie, niż na chromopodpobnych przeglądarkach, ale jest, bo ewidentnie na skryptach inject strona ładuje się szybciej, co widać w tabelce z wynikami, być może to problem nie w różnicy szybkości samych filtrów tylko przeglądarek, ich silników, itp., ale ja nigdzie nie pisałem, że jedne filtry są szybsze od drugich, tylko pisałem że na jednych filtrach strona ładuje się szybciej, a na drugich wolniej, czyli pokazywałem praktyczny czas załadowania się strony, a nie szybkość samych filtrów, które same w sobie w sterylnych laboratoryjnych warunkach mogą się szybkością zbyt wiele nie różnić, ale w połączeniu z przeglądarką efekt jest jaki widać. więc jeśli chcesz zaprzeczyć moim testom, to musisz zrobić swoje i podać wyniki, bo wyniki i suche liczby można zaprzeczyć tylko innymi wynikami i suchymi liczbami, a nie słowami.

> Chodzi o to jak pracuje interpreter js. Częściej wykonywany kod jest bardziej optymalizowany. Plus różnego rodzaju cache.

Ludzie nie wchodzą, na stronę i nie przeładowują jej 10 razy tylko po to żeby ją wygrzać i żeby zaczęła trochę szybciej działać, żeby potem zacząć ją przeglądać, lecz od razu po prostu  wchodzą na stronę i ją przeglądają, myślisz, że ktoś wygrzewa strony przed ich przeglądaniem, wygrzeją się przy okazji z czasem, w miarę przeglądania strony i podstron. Więc po co te wygrzewanie na siłę, ja pokazuję praktyczne pomiary, zwyczajnie wchodzę na stronę, to nie mecz piłki nożnej żeby się wygrzewać przed nim.

> Ale nieprofesjonalnie, bo zmarnowałeś już dwa dni goniąc za czymś czego nie ma. Możesz.

Twój profesjonalizm już właśnie pokazałem, nie będę się powtarzał. Jak już pisałem, to dyskusja naukowa, a w takiej dyskusji pokazuje się pomiary, testy, suche liczby, i można je obalić innymi liczbami, a nie słowami i próżnym ględzeniem, którym zmarnowałeś 2 dni goniąc za czymś czego nie ma.

**Comment by gomoku** [comment]
Ale to tylko jedna przypadkowa strona, która akurat łapie jakieś lagi bo serwer czy łącze nie daje rady, być może strona ma jakiś lipny serwer czy łącze i wg. ciebie już wszystkie strony są tak samo lipne i łapią takiego samego laga, i wrzucasz je do tego samego worka, pisząc po co przejmować się filtrami i prędkością ładowania wszystkich stron bo trafiła się jedna zalagowana? No sorry ale to, że czasem trafi się jakaś jedna zalagowana strona to nie od razu znaczy, że wszystkie takie są.  Więc lepiej byłoby gdybyś swojej argumentacji nie dopasowywał pod linię obrony, i nie opierał się na wygodnych wybiórczo wybranych pojedynczych zalagowanych stronach/testach/przypadkach robiąc z nich ogólny wyznacznik wszystkich innych stron/testów/przypadków, na innych stronach różnice są większe, choćby na tej stronie, a na pewno znajdą się przypadki gdzie różnica będzie jeszcze większa.

Poza tym nawet w instrukcji adblocka autorzy napisali, że różne filtry mogą mieć wpływ na wydajność, i żeby na to uważać, czyli oznacza to, że przy tworzeniu filtrów trzeba kierować się pewnym kompromisem pomiędzy szybkością ładowania strony a skutecznością i trwałością filtra, a nie tylko jego trwałością, nawet jeśli są to części sekundy, a nie całe sekundy.

Dalej nawet także autor uBO jest bardzo wyczulony na punkcie wydajności, i tworzy uBO w oparciu przede wszystkim o wydajność i dla niego liczy się każdy detal, każda najmniejsza nawet optymalizacja, bo ziarnko do ziarnka i uzbiera się miarka.

Nawet twórcy Firefoxa harują i optymalizują każdą linijkę po linijce żeby go przyspieszyć.

A przychodzi taki @gwarser i rzuca stwierdzeniami, najpierw, że nie ma co się przejmować, i że nie ma różnicy w szybkości ładowania się strony na danym filtrze, a potem gdy się okazało, że jednak jest, to zmienia nieco wersję i już twierdzi, że nie to, że nie ma różnicy, ale że jest ona mała, a że oparł to podając jakieś wyselekcjonowane pojedyncze zalagowane strony jako wyznacznik wszystkich stron, to już dochodzimy do punktu w którym jednak ta różnica jest większa, ale pewnie zraz znowu coś wymyśli, żeby temu zaprzeczyć...

Nie wiem do czego zmierzasz.

**Comment by gwarser** [comment]
>Ale to tylko jedna przypadkowa strona, która akurat łapie jakieś lagi bo serwer czy łącze nie daje rady...

Jedyny przypadek na którym widać znaczące różnice. Tylko że tutaj powinieneś testować łącze, a nie filtry.

>Więc lepiej byłoby gdybyś swojej argumentacji nie dopasowywał pod linię obrony, i nie opierał się na wygodnych wybiórczo wybranych pojedynczych zalagowanych stronach/testach/przypadkach robiąc z nich ogólny wyznacznik wszystkich innych stron/testów/przypadków, na innych stronach różnice są większe, choćby na tej stronie, a na pewno znajdą się przypadki gdzie różnica będzie jeszcze większa.


Masz bujną wyobraźnię i na razie to ty nie przedstawiłeś tej jedynej strony na której to różnice będą większe.

>Poza tym nawet w instrukcji adblocka autorzy napisali, że różne filtry mogą mieć wpływ na wydajność, i żeby na to uważać, czyli oznacza to, że przy tworzeniu filtrów trzeba kierować się pewnym kompromisem pomiędzy szybkością ładowania strony a skutecznością i trwałością filtra, a nie tylko jego trwałością, nawet jeśli są to części sekundy, a nie całe sekundy.

**Kompromisem**

>Dalej nawet także autor uBO jest bardzo wyczulony na punkcie wydajności, i tworzy uBO w oparciu przede wszystkim o wydajność i dla niego liczy się każdy detal, każda najmniejsza nawet optymalizacja, bo ziarnko do ziarnka i uzbiera się miarka.

Bo lubi, takie ma hobby.

>Nawet twórcy Firefoxa harują i optymalizują każdą linijkę po linijce żeby go przyspieszyć.

Nie. linijka po linijce optymalizuje się tylko najbardziej spowalniające funkcje.

>A przychodzi taki @gwarser i rzuca stwierdzeniami, najpierw, że nie ma co się przejmować wydajnością, bo nie ma różnicy, a potem gdy się okazało, że jednak jest, to zmienia nieco wersję i już twierdzi, że nie to, że nie ma różnicy, ale że jest ona mała, 

Cały czas twierdzę,  że niema na tyle znaczącej różnicy, by się nią zajmować.

Przykład dobrej optymalizacji to wp - strona zamulała, to przepisano filtry i jest ok.

**Comment by hawkeye116477** [comment]
Temat zamykam, nie widzę sensu dalszej dyskusji z powodu tylko 0,5s różnicy. A filtr zamienię na swój, gdyż uzupełnienie jest też dla AdGuarda. A gołym okiem różnicy pewnie nikt nie zauważy.
