### ISSUE TITLE
neon24.pl

### ISSUE THREAD

**Issue by mat41997** [azet12/PopupBlocker#206]
migający popup

moje filtry
https://gist.github.com/mat41997/51ae1f1fb7f2a32d795c0a17b855feef

ubo 1.14.16 & ubo-pe 12.58
chrome 62.0.3202.75

**Comment by hawkeye116477** [comment]
Popupu nie widzę, ale strzałka jest do schowania.

**Comment by mat41997** [comment]
pojawia się na kilka mili-sekund po przeładowaniu strony

**Comment by hawkeye116477** [comment]
@mat41997 Chyba już wiem o co chodzi, to jest komunikat ciasteczkowy, ale skoro to popup, to chyba powinien trafić na 2 listy. Nie wiem tylko czy da się coś zrobić na te pojawianie się i znikanie. Czy tak jest lepiej?
```
###jqmCookieMonster:not(body):not(html)
www.neon24.pl#@#:not(input)[id*="Cookie"]
```

**Comment by gwarser** [comment]
@mat41997 najczęściej za pierwszym razem w sesji? Tak działa uBlock. Można wzmocnić ten filtr `neon24.pl##.jqmOverlay`

**Comment by mat41997** [comment]
@gwarser ślemy ticketa?
https://github.com/gorhill/uBlock/issues

**Comment by gwarser** [comment]
Nie. Ten typ tak ma. Dla filtrów bez domeny UBO skanuje stronę i ukrywa elementy dopiero po załadowaniu. Takie filtry są cachowane w sesji - jak odświeżysz drugi raz, to filtr jest pobierany z cache i nie miga.

**Comment by mat41997** [comment]
@gwarser ale za pierwszym razem miga >: C

**Comment by gomoku** [comment]
U mnie nic nie miga, (jak coś to mam takie ustawienia: https://github.com/azet12/PopupBlocker/issues/205#issuecomment-342224484)

**Comment by gwarser** [comment]
neon24.pl##script:inject(abort-on-property-read.js, Service.cookieMonster)
