### ISSUE TITLE
hebe.pl

### ISSUE THREAD

**Issue by mat41997** [azet12/PopupBlocker#207]
![2017-11-06 16_01_59-drogeria hebe - zdrowie i piekno _ hebe pl](https://user-images.githubusercontent.com/5884000/32447297-f183c7d8-c30b-11e7-89bf-1e0b43ef4796.png)

moje filtry
https://gist.github.com/mat41997/51ae1f1fb7f2a32d795c0a17b855feef

ubo 1.14.16 & ubo-pe 12.58
chrome 62.0.3202.75

**Comment by hawkeye116477** [comment]
Na popup -> `www.hebe.pl##.splash`
Natomiast przydałoby się jeszcze usadzić header, ale problem jest taki, iż o ile na głównej stronie to działa ok -> `www.hebe.pl##body > header:style(position: static!important;)`, to na podstronach już header się rozłazi. Dlatego też proszę o pomoc @gwarser.

**Comment by gomoku** [comment]
`www.hebe.pl##script:inject(abort-on-property-read.js, $splash)` (średni czas ładowania strony 6.6s) lub
`www.hebe.pl##.splash` (średni czas ładowania strony 6.3s)

Na takich ustawieniach https://github.com/azet12/PopupBlocker/issues/205#issuecomment-342224484 + PopupBlocker

**Comment by hawkeye116477** [comment]
@gomoku U mnie na Vivaldim ok.3s 😄 .

**Comment by gomoku** [comment]
Mi na Operze też, a to ciekawe dlaczego na Firefoxie 2x dłużej.

**Comment by hawkeye116477** [comment]
@gomoku Normalka, w Firefoksie wszystkie strony otwierają się 2x dłużej, taki lichy silnik. Ale chwalą się, że Firefox Quantum będzie 2x szybszy niż Chrome i będzie żżerał 30% mniej ramu od Chrome.

**Comment by gwarser** [comment]
@hawkeye116477 ten drugi pasek to `.main-belt`

**Comment by hawkeye116477** [comment]
@gwarser Ta, ale wejdź tu https://www.hebe.pl/promocje/0426102017-3560-dove i zobacz co się stanie po zastosowaniu filtra `www.hebe.pl##body > header:style(position: static!important;)`, można zamiast tego dać absolute, ale wtedy też będzie problem, bo header zakryje lewe menu.

**Comment by gomoku** [comment]
> @gomoku Normalka, w Firefoksie wszystkie strony otwierają się 2x dłużej, taki lichy silnik. Ale chwalą się, że Firefox Quantum będzie 2x szybszy niż Chrome i będzie żżerał 30% mniej ramu od Chrome.

Lol hmm ale Firefox to muł, zobacz czasy ładowania stron (FF 56.0.2 64bit i Opera 48 64bit):
                 FF     O   ile raz wolniejszy jest FF
hebe.pl     6s    0.5s 12x
neon24.pl 1.5s 0.6s 2.5x

Masakra z tym FF, jedyna nadzieja w nadchodzącym FF 57

**Comment by gwarser** [comment]
Tak naklepałem:
```
www.hebe.pl##body > header:style(position: static!important;)
www.hebe.pl##body > aside:style(top: 100px!important;)
www.hebe.pl##.main-belt:style(position: static!important; padding-left: 0px!important;)
www.hebe.pl##.main-content:style(padding-top: 0px!important;)
www.hebe.pl###main:style(margin-top: 0px!important;)
```

**Comment by hawkeye116477** [comment]
@gwarser Dzięki mistrzu 😄
