### ISSUE TITLE
tychy.info

### ISSUE THREAD

**Issue by hawkeye116477** [azet12/PopupBlocker#209]
@gwarser Jak usadzić ten header?
Próbowałem tak, ale niestety coś tam nadal się przemieszcza -> `www.tychy.info##.menu-stay-on-top:style(position: static!important;)`. Próbowałem też tak -> `www.tychy.info##script:inject(abort-current-inline-script.js, $, menu-stay-on-top)`, ale to znowu blokuje możliwość wyświetlania się obrazków.

**Comment by gwarser** [comment]
```
www.tychy.info##.menu-stay-on-top:style(position: static!important;)

www.tychy.info##.menu-left-side
www.tychy.info##.menu-right-side:style(padding-left: 0px!important;)
```

**Comment by gwarser** [comment]
U ciebie też "PORTALE" skacze? Bo pojęcia nie mam czemu. Nic się nie zmienia w inspektorze dla tego elementu.

**Comment by hawkeye116477** [comment]
@gwarser U mnie skaczą i portale i ogłoszenia.

**Comment by hawkeye116477** [comment]
```
tychy.info##.menu-left-side
tychy.info##.menu-right-side:style(padding-left: 0px!important; width: 100%!important; margin-right: 0!important;)
tychy.info##.menu-stay-on-top:style(position: static!important;)
```
