### ISSUE TITLE
otmuchow.pl

### ISSUE THREAD

**Issue by mat41997** [azet12/PopupBlocker#213]
![2017-11-25 00_59_02-gmina otmuchow strona glowna](https://user-images.githubusercontent.com/5884000/33225645-ebf7df9c-d17b-11e7-9c0b-1de6a0924f36.png)

https://github.com/MajkiIT/polish-ads-filter/issues/4576

moje filtry
https://gist.github.com/mat41997/809ef17633ba86197db6df03d6790f16

ubo 1.14.18 & ubo-pe 12.104
chrome 62.0.3202.94

**Comment by hawkeye116477** [comment]
Tylko problem jest taki, że po zablokowaniu colorboxa nie można obejrzeć zdjęc w trybie powiększonym.

**Comment by blocker999** [comment]
@hawkeye116477 Wielkie dzięki za czujność w takim razie , o pomoc prosze.

**Comment by hawkeye116477** [comment]
@F4z @gwarser Coś poradzicie? 
Z regułami fancybox jest podobnie, na jednej stronie po kliknięciu na zdjęcie, to wcale zamiast powiększenia scroll się blokował, dlatego jedną regułę wywaliłem.

**Comment by gwarser** [comment]
Spalił mi się komp i jestem daleko od domu. Małe szanse z mojej strony na pomoc w najbliższym  czase :/

**Comment by F4z** [comment]
W przypadku `otmuchow.pl` można by spróbować z `:has`, na przykład:
`otmuchow.pl###colorbox:has(#komunikaty)`
`otmuchow.pl###cboxOverlay` albo `otmuchow.pl##body > script ~ #cboxOverlay`
Tylko wtedy jak kliknie się na zdjęcie, to tło nie będzie się przyciemniało, ale w tej chwili nie mam lepszego pomysłu niestety.

**Comment by hawkeye116477** [comment]
Zdaje się, że z tą regułą jak się kliknie na zdjęcie, to tło się przyciemnia -> otmuchow.pl##script ~ #cboxOverlay, a więc jest tak jak miało być.
Dzięki @F4z.
