### ISSUE TITLE
black-friday.pl

### ISSUE THREAD

**Issue by mat41997** [azet12/PopupBlocker#215]
![2017-11-26 20_28_33-black friday polska 2017 - oficjalna strona](https://user-images.githubusercontent.com/5884000/33243530-7b523882-d2e8-11e7-9a8c-e517d7bd317e.png)

moje filtry
https://gist.github.com/mat41997/809ef17633ba86197db6df03d6790f16

ubo 1.14.18 & ubo-pe 12.112
chrome 62.0.3202.94

**Comment by hawkeye116477** [comment]
`www.black-friday.pl###ffbp, #ffbp-bg`
