### ISSUE TITLE
losyziemi.pl

### ISSUE THREAD

**Issue by mat41997** [azet12/PopupBlocker#216]
![2017-11-27 22_02_22-losyziemi pl - ibm udostepnil serwer dns ip_ 9 9 9 9 ktory blokuje adresy z w](https://user-images.githubusercontent.com/5884000/33289224-2625874c-d3bf-11e7-80f5-1f13caa96431.png)
`http://losyziemi.pl/ibm-udostepnil-serwer-dns-ip-9-9-9-9-ktory-blokuje-adresy-z-wirusami-botnetami-oraz-te-odpowiedzialne-za-ataki-hakerskie`

moje filtry
https://gist.github.com/mat41997/809ef17633ba86197db6df03d6790f16

ubo 1.14.18 & ubo-pe 12.113
chrome 62.0.3202.94

**Comment by hawkeye116477** [comment]
`||losyziemi.pl/?spu_action=spu_load&lang=`
