### ISSUE TITLE
kulturawplot.pl

### ISSUE THREAD

**Issue by mat41997** [azet12/PopupBlocker#217]
![2017-11-27 23_46_46-skasowal brudasow i z bazgrania po samochodach uczynil sztuke](https://user-images.githubusercontent.com/5884000/33293484-411774d0-d3cd-11e7-9a8c-b00ef8cd5317.png)
`http://kulturawplot.pl/2017/11/23/brudas-samochod/`

moje filtry
https://gist.github.com/mat41997/809ef17633ba86197db6df03d6790f16

ubo 1.14.18 & ubo-pe 12.113
chrome 62.0.3202.94

**Comment by hawkeye116477** [comment]
> 1 książka = 1/10 obiadu dla autora, zlituj się i kup to

Heh 😃 
`||kulturawplot.pl/wp-content/plugins/exit-popup/js/exit-popup.js`
