### ISSUE TITLE
pulshr.pl

### ISSUE THREAD

**Issue by mat41997** [azet12/PopupBlocker#218]
![2017-11-29 20_44_37-pulshr - zarzadzanie ludzmi edukacja rekrutacja](https://user-images.githubusercontent.com/5884000/33395549-35ac6dba-d546-11e7-9f57-6496f970f89a.png)

moje filtry
https://gist.github.com/mat41997/809ef17633ba86197db6df03d6790f16

ubo 1.14.18 & ubo-pe 12.115
chrome 62.0.3202.94

**Comment by hawkeye116477** [comment]
`/axnewsletter.js`
