### ISSUE TITLE
doradcasmaku.pl

### ISSUE THREAD

**Issue by mat41997** [azet12/PopupBlocker#220]
![2017-11-30 23_45_15-przepisy kulinarne i gotowanie dla kazdego - doradcasmaku pl](https://user-images.githubusercontent.com/5884000/33458961-8e9b050c-d628-11e7-8990-9435b56e4929.png)

https://github.com/MajkiIT/polish-ads-filter/issues/4680

moje filtry
https://gist.github.com/mat41997/809ef17633ba86197db6df03d6790f16

ubo 1.14.18 & ubo-pe 12.115
chrome 62.0.3202.94

**Comment by hawkeye116477** [comment]
`||doradcasmaku.pl/index/get-popup$xmlhttprequest`
