### ISSUE TITLE
spidersweb.pl

### ISSUE THREAD

**Issue by mat41997** [azet12/PopupBlocker#222]
![2017-12-08 23_12_03-spider s web - blog blisko technologii](https://user-images.githubusercontent.com/5884000/33787397-561c9b64-dc6d-11e7-8c61-0a2a5aaed2bc.png)

moje filtry
https://gist.github.com/mat41997/809ef17633ba86197db6df03d6790f16

ubo 1.14.20 & ubo-pe 12.130
chrome 62.0.3202.94

**Comment by hawkeye116477** [comment]
@mat41997 Zasubskrybuj filtry uzupełniające do uBlocka i AdGuarda.
https://raw.githubusercontent.com/azet12/PopupBlocker/master/PPB_uBlock_AdGuard.txt

**Comment by mat41997** [comment]
no mam, zobacz
![2017-12-08 23_45_46-ublock panel sterowania](https://user-images.githubusercontent.com/5884000/33788352-f593f8d2-dc71-11e7-9364-86d4eeb2c581.png)

**Comment by hawkeye116477** [comment]
@mat41997 Ale mi chodzi o Popup Blocker PLUS - uzupełnienie do uBlocka i AdGuarda 😄 .

**Comment by mat41997** [comment]
@hawkeye116477 nakomplikowane

**Comment by hawkeye116477** [comment]
@mat41997 Niektóre filtry sprawiały problemy na Adblocku, dlatego utworzyłem drugą listę, która stanowi uzupełnienie listy Popup Blocker.

**Comment by mat41997** [comment]
to nie lepiej zgłosić to do twórców ublocka i adguarda? oni wtedy mogli by zaimplikować jakiś sposób dodawania filtrów który nie ksułby nic na zwykłym adblocku.

**Comment by hawkeye116477** [comment]
@mat41997 Ale jak by niby to mieli zrobić.
Skoro mam np.
```
ergokantor.pl##.mfp-ready
ergokantor.pl##html:style(overflow: visible!important; margin-right: 0px!important)
```
i ten drugi filtr nie zadziała na Adblocku, przez co scroll się zablokuje.
To chyba raczej musieliby coś zrobić ludzie od Adblocka, a oni nie chcą nic robić.
Dlatego tak samo Majk też zrobił drugą listę tylko dla uBlocka.

**Comment by mat41997** [comment]
aaa, np. tak
```
!!!spidersweb.pl##.mfp-ready
!!!spidersweb.pl##html:style(overflow: visible!important; margin-right: 0px!important)
```

**Comment by hawkeye116477** [comment]
Tylko ciekawe czy by to wypaliło, czy by chcieli w ogóle coś takiego robić z powodu takiego, że u konkurencji są problemy. 
@MajkiIT też w sumie nie zgłaszał nic takiego, tylko od razu zrobił drugą listę.

**Comment by mat41997** [comment]
@ale chodzi o to że teraz tutaj są dwie polskie listy
![2017-12-08 23_45_46-ublock panel sterowania](https://user-images.githubusercontent.com/5884000/33788352-f593f8d2-dc71-11e7-9364-86d4eeb2c581.png)

sam pisałeś że twórca ublocka nie doda kolejnych, więc trzeba połączyć te dwie w jedną by można było dodać kolejną, jaką jest pb+

**Comment by mat41997** [comment]
> Tylko ciekawe czy by to wypaliło, czy by chcieli w ogóle coś takiego robić z powodu takiego, że u konkurencji są problemy.

myślę że tak. w końcu projekt jest open source i każde rozwiązanie które wspiera tą idee jest dobre.
abp nadal nie będzie wspierał tych filtrów, więc nie ujmie to popularności ublockowi i adguardowi.
a dla tworzących listy będzie to bardzo wygodne. nie będą musieli się martwić tworzeniem wielu list dla wielu różnych adblocków.

**Comment by mat41997** [comment]
@hawkeye116477 załatwione, gorhill obiecał że to zrobi.

**Comment by hawkeye116477** [comment]
Ok, gorhilla przekonałeś, teraz kolej na ludzi od AdGuarda.
Jeśli to wypali, to połączę obie listy w jedną.

**Comment by mat41997** [comment]
@hawkeye116477 była kolej na xxcriticxx, to teraz możesz trochę mnie poudawać i napisać do teamu adguarda

https://github.com/AdguardTeam/AdguardBrowserExtension

**Comment by hawkeye116477** [comment]
https://github.com/AdguardTeam/AdguardBrowserExtension/issues/913

**Comment by mat41997** [comment]
https://github.com/gorhill/uBlock/issues/3332

**Comment by mat41997** [comment]
gut

**Comment by hawkeye116477** [comment]
Tylko, że jest jeszcze pewien problem, na AdGuardzie nie działają reguły script:inject() i te xpath też nie wiem czy działają. Nie wiem też czy któraś z tych reguł w kombinacji z inną nie będzie robić problemów na AG. Chociaż chyba po prostu skorzystać z`!+ NOT_PLATFORM()`.  Dopisać wszystkie platformy i wtedy na AdGuardzie po prostu nie będą działały te reguły. 
https://kb.adguard.com/en/general/how-to-create-your-own-ad-filters

**Comment by hawkeye116477** [comment]
Tylko, że jest jeszcze pewien problem, na AdGuardzie nie działają reguły script:inject() i te xpath też nie wiem czy działają. Nie wiem też czy któraś z tych reguł w kombinacji z inną nie będzie robić problemów na AG.
Można niby zrobić tak-> `!+ PLATFORM(ext_ublock)`. Tylko ciekawe czy to będzie działać, bo jak próbuje tak zrobić z PPB, to coś nie działa, ale w ogóle może to dlatego, że w AdGuardzie nie ma opcji, by dodawać listy filtrów, można jedynie zaimportować do filtrów użytkownika.
