### ISSUE TITLE
polona.pl

### ISSUE THREAD

**Issue by mat41997** [azet12/PopupBlocker#223]
![2017-12-09 22_41_34-panorama warszawy ze szczytu wiezy zamkowej polona](https://user-images.githubusercontent.com/5884000/33799747-21eff6e0-dd32-11e7-8ff6-243de81f20a7.png)
`https://polona.pl/item/panorama-warszawy-ze-szczytu-wiezy-zamkowej,NTc4NTUxOQ/0/#item`

moje filtry
https://gist.github.com/mat41997/809ef17633ba86197db6df03d6790f16

Nano Adblocker 1.0.0.3
Nano Defender 12.134
Chrome 63.0.3239.84

**Comment by hawkeye116477** [comment]
Do tej sprawy jeszcze wrócimy, trzeba jakoś usadzić tą stopkę w inny sposób najwyraźniej.
