### ISSUE TITLE
defence24.com

### ISSUE THREAD

**Issue by mat41997** [azet12/PopupBlocker#225]
![2017-12-13 03_30_21-defence24](https://user-images.githubusercontent.com/5884000/33918880-1b8d9a60-dfb6-11e7-8cfe-618bae343638.png)

moje filtry
https://gist.github.com/mat41997/809ef17633ba86197db6df03d6790f16

Nano Adblocker 1.0.0.10
Nano Defender 13.0
Chrome 63.0.3239.84

**Comment by blocker999** [comment]
Tu trzeba odblokować scrolla więc może @hawkeye116477 pomoże

**Comment by hawkeye116477** [comment]
@mat41997 @blocker999 Ale to już jest na liście uzupełniającej -> https://raw.githubusercontent.com/azet12/PopupBlocker/master/PPB_uBlock_AdGuard.txt. Mat zasubskrybuj to, bo tak prędko pewnie tego nie połączymy, a gorhilowi trochę zajmie utworzenie tych nowych zapisów.

**Comment by mat41997** [comment]
@hawkeye116477 przecież mam zasubskrybowaną listę
```
! Title: Popup Blocker PLUS - uzupełnienie do uBlocka
! Last modified: 12 Dec 2017
```

**Comment by hawkeye116477** [comment]
@mat41997 No to nie zaktualizowałeś tego na gist. A ja się pomyliłem, bo jest na to reguła, ale na polską stronę, a ta jest ta sama, tylko, że po angielsku, a my się zajmujemy raczej stronami, które są po polsku.

**Comment by mat41997** [comment]
@hawkeye116477 przepraszam, ale co chwile coś zmieniam.

**Comment by hawkeye116477** [comment]
@mat41997 Być może coś mówiłeś, a ja jestem zapominalski 😄 .
