### ISSUE TITLE
medycznamarihuana.com

### ISSUE THREAD

**Issue by KonoromiHimaries** [azet12/PopupBlocker#240]
![2017-12-20 05_06_56-medycznamarihuana com - portal rzetelnych informacji](https://user-images.githubusercontent.com/5884000/34190894-a59a0fe4-e543-11e7-9da8-2c2ef46965be.png)

moje filtry
tylko polskie filtry

tylko polskie filtry
Nano Adblocker 1.0.0.15
Nano Defender 13.5
Chrome 63.0.3239.108

**Comment by hawkeye116477** [comment]
Co ty się masz z tą marychą, a potem 100 zgłoszeń dziennie dla Majka od tej marychy :smiley:.

**Comment by KonoromiHimaries** [comment]
@hawkeye116477 zachowaj owe insynuacje bezwiedne na późniejszy okres
