### ISSUE TITLE
dowbit.pl

### ISSUE THREAD

**Issue by KonoromiHimaries** [azet12/PopupBlocker#241]
![2017-12-20 12_02_02-francja stara sie o poruszenie kwestii bitcoina podczas szczytu g20 - dowbit pl](https://user-images.githubusercontent.com/5884000/34204154-fb77b602-e57d-11e7-91b4-7310532cd7cc.png)
`https://dowbit.pl/francja-stara-sie-o-poruszenie-kwestii-bitcoina-szczytu-g20/`

moje filtry
polskie filtry + easylist

Nano Adblocker 1.0.0.15
Nano Defender 13.5
Chrome 63.0.3239.108

**Comment by hawkeye116477** [comment]
@KonoromiHimaries U mnie tego nie ma. Nadal to masz?

**Comment by KonoromiHimaries** [comment]
ten mniejszy element owszem

**Comment by hawkeye116477** [comment]
@KonoromiHimaries Ok, dorwałem to, ale musiałem najwyraźniej wyłączyć uBlock filters - Privacy, żeby się wyświetliło - > `dowbit.pl##.mcwidget-overlay`.
