### ISSUE TITLE
portel.pl

### ISSUE THREAD

**Issue by KonoromiHimaries** [azet12/PopupBlocker#245]
![2017-12-21 12_05_25-elblag ma swoje dobre strony - elblaska gazeta internetowa portel pl](https://user-images.githubusercontent.com/5884000/34253362-7f47848e-e647-11e7-9b0f-460a514075ac.png)

moje filtry
polskie filtry + easylist

Nano Adblocker 1.0.0.15
Nano Defender 13.8
Chrome 63.0.3239.108

**Comment by hawkeye116477** [comment]
Ja tego nie mam.
