### ISSUE TITLE
policja.pl

### ISSUE THREAD

**Issue by gwarser** [azet12/PopupBlocker#25]
`http://www.policja.pl/pol/aktualnosci/137593,Czemu-miala-sluzyc-ta-dziennikarska-prowokacja.html`

`pl##.bg` ukrywa całą stronę

Może robić tak jak z ciastkami - `...:not(body):not(html)`?

**Comment by blocker999** [comment]
@gwarser 

A nie lepiej dodać tą strone do wyjątków?

**Comment by gwarser** [comment]
Lepiej. Tak tylko gadam.

**Comment by blocker999** [comment]
#22
