### ISSUE TITLE
eska.pl

### ISSUE THREAD

**Issue by KonoromiHimaries** [azet12/PopupBlocker#253]
![2017-12-22 13_15_20-sylwester zakopane_ luis fonsi zaspiewa despacito w zakopanem za 150 tys zloty](https://user-images.githubusercontent.com/5884000/34297745-44078f08-e71a-11e7-8ecb-2b99415524a9.png)
`http://www.eska.pl/hotplota/news/sylwester-zakopane-luis-fonsi-zaspiewa-despacito-w-zakopanem-za-150-tys-zlotych/n/106342`

moje filtry
easylist + polskie filtry

Nano Adblocker 1.0.0.17
Nano Defender 13.9
Chrome 63.0.3239.108

**Comment by hawkeye116477** [comment]
Tak w zasadzie to to już jest w Pete Low's Ad and tracking server list, w EasyPrivacy też jest, ale z racji tego, że to jest popup i pewnie nie wszyscy mają te listy, to zaraz dodam odpowiednią regułę.
