### ISSUE TITLE
joemonster.org

### ISSUE THREAD

**Issue by KonoromiHimaries** [azet12/PopupBlocker#255]
![2017-12-22 15_11_58-co roku setki fanow karpia z dyskontow poluje na nie niczym wsciekle wilki - joe](https://user-images.githubusercontent.com/5884000/34300889-93522ef0-e72a-11e7-9b81-9bd99da87526.png)
`http://joemonster.org/filmy/88011/Co_roku_setki_fanow_karpia_z_dyskontow_poluje_na_nie_niczym_wsciekle_wilki`

moje filtry
easylist + polskie filtry

Nano Adblocker 1.0.0.17
Nano Defender 13.9
Chrome 63.0.3239.108

**Comment by hawkeye116477** [comment]
@KonoromiHimaries Mam schować tą strzałkę tylko czy coś jeszcze?

**Comment by KonoromiHimaries** [comment]
Wystarczy ukryć okienko.

**Comment by hawkeye116477** [comment]
@KonoromiHimaries A, czyli jednak chodzi o te okienko z filmikiem. Tego się właśnie obawiałem, ale to jest jeden i ten sam filmik, tylko, że te okienko lata ze scrollem i tu właśnie jest problem, że ja nie wiem jak go zatrzymać. Potrzebna jest pomoc @F4z.

**Comment by F4z** [comment]
To nie wystarczy ukryć tego elementu po lewej?

**Comment by hawkeye116477** [comment]
@F4z No właśnie nie, bo jeśli zrobię tak -> `joemonster.org###mtv_main_swf`, to wtedy filmik się schowa, bo to jest jako jeden element.

**Comment by hawkeye116477** [comment]
@F4z Ok, już nie potrzebna pomoc, jednak sam znalazłem już rozwiązanie :smile:.
