### ISSUE TITLE
onet.pl

### ISSUE THREAD

**Issue by gwarser** [azet12/PopupBlocker#27]
Potworek na onecie pojawia się z powodu oto takiego, że stosowane są filtry specyficzne "dla .pl":

    pl##.up
    pl##.adsbygoogle

Mimo, że Adblock & uBlock polish filters stosuje dla onetu $generichide żeby tam za bardzo nie chowało.

UBO 1.11.5b0
Fx 54

**Comment by blocker999** [comment]
@gwarser 

Czy obecna aktualizacja jest ok czy proponujesz inną?.

**Comment by gwarser** [comment]
`.adsbygoogle` jest w Easylist, `.up` to nie wiem co to i mam razem z `.in` z "Adblock polskie reguly social" dodane do wyjątków bo za dużo problemów mi sprawiało.

**Comment by blocker999** [comment]
Dobra usunąłem te dwie reguły a tym " .in " zajmę się później.
