### ISSUE TITLE
ergokantor.pl

### ISSUE THREAD

**Issue by hawkeye116477** [azet12/PopupBlocker#29]
![screenshot_20170715_202414](https://user-images.githubusercontent.com/19818572/28241797-bfcb6a9e-699b-11e7-8be9-6cef8b7e73f9.png)

@azet12 Dasz radę to zablokować mistrzu, by nie było problemów? Próbowałem kosmetycznymi:
```
ergokantor.pl##.white-popup
ergokantor.pl##.mfp-ready.mfp-bg
```
ale problem jest w tym, że po pewnym czasie, tzn. w tym czasie co miał się pojawić popup, strona blokuję się, nie można scrollować.

**Comment by blocker999** [comment]
@hawkeye116477 Ja zajmuje się tymi filtrami jak i socialem pl do którego zgłoszenia przyjmuje w https://github.com/MajkiIT/polish-ads-filter/issues , gdyż współtworzę tą paczkę.
Natomiast różne dziwne i irytujące elementy, zgłaszaj tu, gdyż prędzej czy później nimi się zajmne.
a Pan @azet12 poprostu napoczątku pośredniczył i tak już zostało, trochę to poplątane ale tak już jest.
On tworzy filtry " KAD " z którymi warto się zapoznać : 
https://github.com/azet12/KAD

**Comment by hawkeye116477** [comment]
@blocker999 Ok

**Comment by blocker999** [comment]
Oczywiście, zaraz zobacze.

**Comment by blocker999** [comment]
Dobra dodane ale dokładniej się przyjrze tej stronce wieczorem.

A tak na marginesie co sądzisz o blokadzie tego paska na dole?, bo według mnie tylko odwraca uwage informując o rzeczach oczywistych.

**Comment by hawkeye116477** [comment]
@blocker999 `ergokantor.pl###przesuwany_tekst`  
Możesz dodać, ale to już jest w polskich filtrach do uBlocka i Adblocka.

**Comment by blocker999** [comment]
Z tym paskiem to już niebęde dublował skoro już jest w Polskich bo to jest tylko dodatek do niego.

Cześć z mej listy by się przydało dodać do głównej pl ale konkretnie które to już sam niewiem a niemam zbytnio czasu by to sortować, gdybym odrazu przekazał info o tych elementach to pewnie były by one w tam no ale ja zająłem się osobnym filtrem wiec jest jak jest.

**Comment by hawkeye116477** [comment]
@blocker999 Ja bym proponował połączyć polskie filtry cookies z PopupBlockerem w jeden filtr - polskie filtry annoyance, tak jak to mają fanboye (no może oprócz sociala, to może zostać osobno).

**Comment by blocker999** [comment]
Atam niech już tak będzie no ale Swoje pomysły możesz przekazać MajkiIT, bo cookies to jego paczka aha żeby była jasność umnie niema cookies, reklam, sociali bo dotych trzech są przecież osobne paczki a ja mam głównie popupy oraz inne śmiecie które są przydatne dlatego nie są w całości w PL.

**Comment by hawkeye116477** [comment]
@blocker999 Ok, przekazałem.

**Comment by blocker999** [comment]
bez pomocy się nieobędzie, wiec bardzo proszę @F4z pomoc

**Comment by F4z** [comment]
Na odblokowanie przewijania strony można dodać tę regułę:
`ergokantor.pl##html:style(overflow: visible!important; margin-right: 0px!important;)`

**Comment by hawkeye116477** [comment]
@F4z Działa poprawnie, ale ten średnik przy końcu chyba jest nie potrzebny.

@blocker999 Możesz dodać: 
```
ergokantor.pl##.mfp-ready
ergokantor.pl##html:style(overflow: visible!important; margin-right: 0px!important)
```

A to niepotrzebne, więc do usunięcia `pl##img[src="/images/popup-beztresci4.jpg"]`.
