### ISSUE TITLE
stokrotka.pl

### ISSUE THREAD

**Issue by hawkeye116477** [azet12/PopupBlocker#33]
Strona jest przyciemniona.
`stokrotka.pl##.fancybox-overlay-fixed.fancybox-overlay`

![screenshot_20170721_104842](https://user-images.githubusercontent.com/19818572/28456381-638d6550-6e02-11e7-86e7-a6625bbf5939.png)

**Comment by hawkeye116477** [comment]
@blocker999

**Comment by hawkeye116477** [comment]
@blocker999

**Comment by blocker999** [comment]
Trzeba jeszcze odblokować tzw. pierwsze wejście tzn: ekran blokady jest gdy się wchodzi na tą strone poraz pierwszy na innej przeglądarce mimo aktualnych filtrów " Popupblockera " dlatego  trzeba dodać regułę odblokowującą i wtej sprawie zwracam się o pomoc do specjalisty @F4z

**Comment by F4z** [comment]
Z tym "specjalistą", to bez przesady :)
Powinno działać:
`stokrotka.pl##html.fancybox-lock:style(margin-right: 0px!important; overflow: auto!important;)`

**Comment by hawkeye116477** [comment]
@F4z Działa, dzięki mistrzu.
