### ISSUE TITLE
google.pl

### ISSUE THREAD

**Issue by hawkeye116477** [azet12/PopupBlocker#34]
@blocker999 Coś z tych filtrów blokuje możliwość wylogowania z Google, nie mogę kliknąć w ogóle na przycisk.
Zgaduję, że to: `google.pl##.gb_ga`

**Comment by blocker999** [comment]
Myśle że warto to zostawić a wylogowywanie dodać do wyjątków ,dlatego proszę abyś podał konkretną regułe gdyż niemam tam konta a niechce się specjalnie rejestrować.

**Comment by hawkeye116477** [comment]
@blocker999 
`google.pl#@#.gb_g.gb_ga.gb_mb`

Jak nie jest się zalogowanym, to na dole jest pasek: przypomnienie o polityce prywatności, to też do twoich filtrów?

**Comment by hawkeye116477** [comment]
@blocker999 Jak przerobić to na regulę odblokowującą? 
`google.pl##.gb_ga.gb_mb`

**Comment by hawkeye116477** [comment]
@blocker999 Tylko, że te 2 reguły chowają taki prostokąt odpowiedzialny za wylogowanie.
```
pl##.gb_g.gb_ga
pl##.gb_ga
```
Reguła chowająca prostokąt wylogwujacy czy jak to tam nazwać ma taką postać: `pl##.gb_g.gb_ga.gb_mb`
Co miało być tym zablokowane?

**Comment by hawkeye116477** [comment]
@F4z Mistrzu, możesz zerknąć?

**Comment by F4z** [comment]
Nie wiem do czego były te reguły, ale to powinno odblokować ten prostokąt:
`google.pl#@#.gb_ga`
`google.pl#@#.gb_g.gb_ga`

**Comment by hawkeye116477** [comment]
@F4z Tyle, to i ja wiem. Powiedzial bym, że lepiej wywalić te 2 reguły, bo na 100% niczego innego jak czegoś na Google nie blokują.

**Comment by blocker999** [comment]
@hawkeye116477 @F4z 

Napewno coś na wyszukiwarce googla, prawdopodopodobnie popup z informacją o regulaminiie który pojawia się podczas pierwszego wejścia no ale teraz niewiem jak to wywołać dlatego proponuje te reguły usunąć.

**Comment by hawkeye116477** [comment]
@blocker999 To działaj.

**Comment by blocker999** [comment]
@hawkeye116477 Usunąć to, czy tylko pozmieniać reguły by niekolidowały z " wylogowywaniem "?.

**Comment by hawkeye116477** [comment]
@blocker999 Usuń to

**Comment by blocker999** [comment]
OK

**Comment by blocker999** [comment]
@hawkeye116477 takie rzeczy jak regulaminy, polityka danej firmy itp, omijać?.

**Comment by hawkeye116477** [comment]
@blocker999 Politykę blokuj. Ale regulamin to ja bym zostawił raczej.

**Comment by blocker999** [comment]
@hawkeye116477 Nierozumiem, skoro to są reguły blokujące polityke wujka, to poco mam to usuwać?.

**Comment by hawkeye116477** [comment]
@blocker999 Tylko, że ty i ja nie jesteśmy pewni, czy te reguły na pewno to blokują. One blokują, ale na pewno prostokąt wylogowujący. Nawet jak to te reguły zwhitelistuję, to polityka się nie wyświetla.

**Comment by blocker999** [comment]
Dobra, usunąłem, pasuje ?.

**Comment by hawkeye116477** [comment]
Tak, dzięki.
