### ISSUE TITLE
ceneo.pl

### ISSUE THREAD

**Issue by hawkeye116477** [azet12/PopupBlocker#35]
@blocker999 Na ceneo z włączonym filtrem PopupBlocker nie można wyświetlić powiększenia zdjęcia. Przykładowy link: https://www.ceneo.pl/51206008 .
Proszę o dodanie wyjątku: `ceneo.pl#@#.popup`

**Comment by blocker999** [comment]
@hawkeye116477 Pewnie gdzie indziej też, dlatego proponuje usunąć `pl.##.popup` ?.

**Comment by hawkeye116477** [comment]
@blocker999 Nie wiem, ale po coś chyba to dodałeś, więc decyzja należy do ciebie. 
Po znaku zapytania raczej nie stawia się kropki.

**Comment by blocker999** [comment]
Na pewno tylko niewiadomo do jakiej bo adres z przodu wyparował, ale spróbuje to odnaleźć, wiec albo dodam pełen adres albo usune.

**Comment by hawkeye116477** [comment]
@blocker999 Zdaje się, że chodziło o to: https://github.com/azet12/PopupBlocker/issues/24

**Comment by hawkeye116477** [comment]
https://github.com/azet12/PopupBlocker/commit/cd41b0a120b3f6943fd3bc698900e130c0a39fa9

**Comment by blocker999** [comment]
No właśnie więcej chyba więcej z tym problemu niż pożytku niż pożytku, dlatego też już to usunąłem, ale zawsze można dodać z powrotem tym razem z pełnym adresem.

**Comment by hawkeye116477** [comment]
@blocker999 Dzięki
