### ISSUE TITLE
pepco.pl

### ISSUE THREAD

**Issue by hawkeye116477** [azet12/PopupBlocker#38]
@blocker999 Newsletter Popup
`pepco.pl##.in.modal-newsletter.fade.modal`

Tylko, trzeba teraz jakoś odblokować scroll.

**Comment by hawkeye116477** [comment]
@F4z Mistrzu możesz zerknąć?

**Comment by F4z** [comment]
`pepco.pl##body.modal-open:style(padding-right: 0px!important; overflow: visible!important;)`

**Comment by hawkeye116477** [comment]
@F4z Dzięki
Jeszcze tylko rozjaśnienie: `pepco.pl##.in.fade.modal-backdrop`
