### ISSUE TITLE
pilot.wp.pl

### ISSUE THREAD

**Issue by hawkeye116477** [azet12/PopupBlocker#40]
@blocker999 Do PopupBlockera do dodania, gdyż blokuje playera: `pilot.wp.pl#@##Player0`.

**Comment by hawkeye116477** [comment]
@blocker999 Dzięki

**Comment by hawkeye116477** [comment]
@blocker999 Wkradł się u ciebie mały błąd, na końcu nie powinno być kropki.

**Comment by blocker999** [comment]
ok, zle skopiowałem, zaraz poprawie

**Comment by hawkeye116477** [comment]
@blocker999 Dzięki
