### ISSUE TITLE
rylko.com

### ISSUE THREAD

**Issue by blocker999** [azet12/PopupBlocker#43]
Po zastosowaniu reguł
```
 rylko.com###modal-newsletter
rylko.com##.in.fade.modal-backdrop
```  
występuje ekran blokady wiec proszę @F4z o pomoc.

**Comment by F4z** [comment]
Tak chyba będzie w porządku:
`rylko.com##body.modal-open:style(padding-right: 0px!important; overflow: auto!important;)`

**Comment by blocker999** [comment]
@F4z Dzięki
