### ISSUE TITLE
foreca.pl

### ISSUE THREAD

**Issue by hawkeye116477** [azet12/PopupBlocker#44]
@blocker999 Po lewej zniknęlo parę przydatnych linków - `foreca.pl#@#.top`.
Na górze brakuje wyszukiwarki, gdzie pogodę ma znaleźć - `foreca.pl#@##topbar`.

**Comment by blocker999** [comment]
@hawkeye116477 Ok dodam.

Ostatnio zabieram się za porządki w Popblokerze i nieukrywam że potrzebował bym listy " reguł których unikać " co bardzo pomogło by mi przy tworzeniu kolejnych aktualizacji.
Chciałem stworzyć taką liste na podstawie starych aktualizacji a konketnie reguł które usunełem tzn chodzi mi o scalenie wszystkich usuniętych reguł ze starych list w jedną liste, tylko niewiem jak to wykonać dlatego proszę Cię o pomoc.

**Comment by hawkeye116477** [comment]
@blocker999 Ok, przyjrzę się i zobaczę co tu możnaby usunąć. Generalnie to reguły typu gora, dogóry, top, itd. raczej należy stosować bezpośrednio do konkretnych stron :smile: .

**Comment by blocker999** [comment]
@hawkeye116477 dzięki za uwagi ale bardzo mi zależy na automatycznym wykonaniu tego pliku gdyż przeglądanie starych aktualek ( a jest ich około 130 ) niezabardzo mi się uśmiecha a taki plik mocno by ułatwił dalszą prace.

**Comment by hawkeye116477** [comment]
@blocker999 

> chodzi mi o scalenie wszystkich usuniętych reguł ze starych list w jedną plik tylko niewiem jak to wykonać dlatego proszę Cię o pomoc.

> dzięki za uwagi ale bardzo mi zależy na automatycznym wykonaniu tego pliku gdyż przeglądanie starych aktualek ( a jest ich około 130 ) niezabardzo mi się uśmiecha a taki plik mocno by ułatwił dalszą prace.
Nie wiem jak tego dokonać i czy coś takiego się da zrobić automatycznie w ogóle.

**Comment by hawkeye116477** [comment]
Tu reguły do usunięcia wg. mnie: https://github.com/hawkeye116477/PopupBlocker/commit/6d7720294dc22ecb0cf51314bff9e4d50cba72b0 . Może lepiej zapytaj o pomoc wielkiego mistrza @F4z, bo ja tu tylko sprzątam .... :smiley:

**Comment by hawkeye116477** [comment]
Tu reguły do usunięcia wg. mnie: https://github.com/hawkeye116477/PopupBlocker/commit/f8bf1ec906f2bca7c7159219d4f21128e0d74dfb . Może lepiej zapytaj o pomoc wielkiego mistrza @F4z, bo ja tu tylko sprzątam .... :smiley:

**Comment by hawkeye116477** [comment]
@blocker999 Ok, chyba zdaje się już wiem. GitKrakenem mogę zaznaczyć wszystko i zrobić merge.

**Comment by hawkeye116477** [comment]
@blocker999 Wszystko scalić właściwie można za pomocą GitKrakena, ale wszystko, nie tylko usunięte.

**Comment by blocker999** [comment]
@hawkeye116477 Wielkie dzięki !!!
