### ISSUE TITLE
Scalenie usunietych reguł

### ISSUE THREAD

**Issue by blocker999** [azet12/PopupBlocker#45]
Ostatnio zabieram się za porządki w Popblokerze i nieukrywam że potrzebował bym listy " reguł których unikać " co bardzo pomogło by mi przy tworzeniu kolejnych aktualizacji.
Chciałem stworzyć taką liste na podstawie starych aktualizacji a konketnie reguł które usunąłem tzn chodzi mi o scalenie wszystkich usuniętych reguł ze starych list w jeden plik tylko niewiem jak to wykonać dlatego proszę @F4z o pomoc.

**Comment by F4z** [comment]
Szczerze mówiąc nie znam się za bardzo na tym i nie wiem jak to dobrze zrobić.
Wydaje mi się, że sprawę utrudnia też to, że były tego typu zmiany - https://github.com/azet12/PopupBlocker/commit/dfc6212ee945fb040c0e4b0cfd6005efc30ae34d
Masa reguł została usunięta i zmieniona na `pl.##[...]` i jeśli chciałbyś uwzględnić wszystkie zmiany, to też by się w to wliczało. Oprócz tego, jak zmieniałeś pozycję reguły, to też w pewnym sensie jest jako usunięta, na przykład `sfinks.info` tutaj - https://github.com/azet12/PopupBlocker/commit/14afea4306db008d251e96963acd15971ef7754b#diff-e8b662a22222e5fb9f02df67781b8dccL85
https://github.com/azet12/PopupBlocker/commit/14afea4306db008d251e96963acd15971ef7754b#diff-e8b662a22222e5fb9f02df67781b8dccR74

Jeśli się nigdzie nie pomyliłem, to tutaj jest lista wszystkich usuniętych reguł - http://wklej.org/id/3229263/txt/
Tutaj tylko z tego roku - http://wklej.org/id/3229262/txt/
Tutaj od maja tego roku - http://wklej.org/id/3229264/txt/

Tylko tak jak pisałem wcześniej, w to się wlicza każda usunięta reguła, czy też zmiana pozycji reguły, no ale niestety nie mam lepszego pomysłu jak to zrobić.

**Comment by blocker999** [comment]
@F4z Ogromne dzięki, oto mi chodziło choć nieprzypuszczałem że aż tyle trudu Cię to będzie kosztowało no ale fakt namieszałem, jeszcze raz dzięki i zabieram się za edycje PopupBlockera.
