### ISSUE TITLE
mediaexpert.pl

### ISSUE THREAD

**Issue by blocker999** [azet12/PopupBlocker#48]
Na stronie z przedmiotami np tu https://www.mediaexpert.pl/glosniki-mobilne/glosnik-mobilny-jbl-charge-2-czarny,id-574875
jest ekran blokady, jakie reguły dodać, by to odblokować @F4z

**Comment by hawkeye116477** [comment]
@blocker999 `mediaexpert.pl##html:style(overflow: visible!important; margin-right: 0px!important)`

**Comment by blocker999** [comment]
zaraz dodam

**Comment by hawkeye116477** [comment]
@blocker999 Znowu coś się tu pojawiło?

**Comment by blocker999** [comment]
@hawkeye116477 Trzeba to poprawić bo mediaexpert.pl##.mfp-ready blokuje też podgląd przedmiotów na tej stronie.

**Comment by hawkeye116477** [comment]
@blocker999 Ok, to może coś takiego: `pl##.mfp-ready.mfp-bg`? To już w sumie jest w PopupBlockerze, więc może najlepiej byłoby po prostu usunąć `mediaexpert.pl##.mfp-ready`, a na newsletter jest `mediaexpert.pl##.nletter_popup` w głównym polskim filtrze, może to powinno być przeniesione do PopupBlockera.

**Comment by blocker999** [comment]
@hawkeye116477 Co do popupa, to tak zrobie jak mówisz, natomiast o newsletter to już z @MajkiIT trzeba rozmawiać, gdyż jego paczka powstała długo przed moją.

**Comment by hawkeye116477** [comment]
@blocker999 Już to zgłosiłem do niego: https://github.com/MajkiIT/polish-ads-filter/issues/3229

**Comment by hawkeye116477** [comment]
@blocker999 Ok, już usunął, czyli możesz dodać: `mediaexpert.pl##.nletter_popup`.

**Comment by blocker999** [comment]
@hawkeye116477 OK
