### ISSUE TITLE
homebook.pl

### ISSUE THREAD

**Issue by blocker999** [azet12/PopupBlocker#50]
`@hawkeye116477
Skoro odblokowałeś mediaexperta to pewnie i teraz dasz rade.

Mianowicie po zablokowaniu popupa jest blokada, mam tylko `homebook.pl##.popup-overlay--dark.popup-overlay` i co dalej?

**Comment by hawkeye116477** [comment]
@blocker999 Jasne, jasne, w tamtym przypadku znalazłem już te same reguły, które były w filtrze i działały też dla tamtej strony. Ja takich reguł sam nie umiem układać, to tylko wielki mistrz @F4z potrafi.

**Comment by hawkeye116477** [comment]
@blocker999 Ok, jednak chyba coś tam umiem: `homebook.pl##body.has-open-popup:style(overflow: visible!important;)`.

**Comment by hawkeye116477** [comment]
@blocker999 `homebook.pl##body.has-open-popup:style(overflow: visible!important;)`
A na popup to raczej wystarczy tylko: `pl##.popup-overlay`.

**Comment by blocker999** [comment]
Ok

**Comment by blocker999** [comment]
@hawkeye116477 czy te `pl##.popup-overlay` nie zbyt za ogólne tzn czy czegoś przypadkiem nie uszkodzi?.

**Comment by hawkeye116477** [comment]
@blocker999 Jak sama nazwa brzmi popup, więc chyba raczej jest tylko do popupów, zresztą podobną regułę już masz: `pl###popup-overlay` i problemów chyba nikt nie zgłaszał. Ale jeśli masz takie obawy, to może lepiej jednak na razie dać `homebook.pl##.popup-overlay`.
A tak BTW, to po znaku zapytania nie stawia się kropki.

**Comment by hawkeye116477** [comment]
@blocker999 Fanboye na swojej liście mają dane: `mysmartprice.com##.popup-overlay`, ale nie mają tego jako `com##.popup-overlay`. Więc jeśli oni tak dali, to chyba jednak lepiej dać: `homebook.pl##.popup-overlay`.

**Comment by blocker999** [comment]
@hawkeye116477 Oj zdziwił byś się zdarzają się że strony które wykorzystują takie reguły do zupełnie czego innego i potem jest problem ale po szczegóły to zapraszam do zamkniętych tematów w issuse.

Dobra będe dalej skracał za wyjątkiem tych co się nazbierały od początku popupblockera.

**Comment by hawkeye116477** [comment]
@blocker999 Nie no, tak jak mówię, oni tego nie mają jako general, więc chyba jednak lepiej `homebook.pl##.popup-overlay`.

**Comment by hawkeye116477** [comment]
@blocker999 Tylko daj bez kropki tym razem.

**Comment by blocker999** [comment]
@hawkeye116477 Może tak być?

**Comment by hawkeye116477** [comment]
@blocker999 Jeszcze kropkę usuń na końcu.

**Comment by blocker999** [comment]
@hawkeye116477 No znowu coś namieszałem ale na przyszłość proszę Cie kropek niedawaj, bo jak kopiuje to niepatrze.

**Comment by hawkeye116477** [comment]
@blocker999 Ok
