### ISSUE TITLE
limango.pl

### ISSUE THREAD

**Issue by blocker999** [azet12/PopupBlocker#52]
@hawkeye116477 - Proszę o pomoc

**Comment by hawkeye116477** [comment]
@blocker999 
```
limango.pl##.modal
limango.pl##body.welcome_main.modal-open:style(overflow: visible!important;padding-right: 0px!important;)
```

Nie ma problemu. Tyle starczy czy coś jeszcze :smile: ?

**Comment by blocker999** [comment]
@hawkeye116477

 Narazie wystarczy jeśli działa, pewnie jutro znajde kolejne stronki, rozumiem że moge na Ciebie liczyć ?

**Comment by hawkeye116477** [comment]
@blocker999 Tak :smile:.
