### ISSUE TITLE
mycenter.pl

### ISSUE THREAD

**Issue by blocker999** [azet12/PopupBlocker#57]
@hawkeye116477 Popup

**Comment by hawkeye116477** [comment]
@blocker999 
mycenter.pl###js-newsletterPopup
mycenter.pl##html:style(overflow: visible!important; margin-right: 0px!important;)

Czyli to samo, co #55.
A więc można dać po prostu tak:
```
mixmedia.pl,mycenter.pl###js-newsletterPopup
mixmedia.pl,mycenter.pl##html:style(overflow: visible!important; margin-right: 0px!important;)
```

**Comment by blocker999** [comment]
@hawkeye116477 OK
