### ISSUE TITLE
habys.pl

### ISSUE THREAD

**Issue by hawkeye116477** [azet12/PopupBlocker#58]
@blocker999 
Popup. 
`habys.pl###cp-widget`

Jeszcze tylko scrolla trzeba odblokować. Tu jest trudniej, cwaniaki dali important, przez to się moja reguła na scrolla podmienia, ale może coś zaraz wykombinuję.

**Comment by blocker999** [comment]
Jak trudne to ja napewno niepomoge ale zato bardzo proszę o pomoc @F4z

**Comment by F4z** [comment]
Na przykład takie coś powinno działać:
`habys.pl##body#index.cp-widget--open:style(overflow: visible!important;)`
Ewentualnie tak też może być:
`habys.pl##html > body.cp-widget--open:style(overflow: visible!important;)`

https://stackoverflow.com/questions/11178673/how-to-override-important

**Comment by F4z** [comment]
Z tego co widzę tam jest więcej "popupów", nie tylko na stronie głównej, więc takie coś powinno być lepsze:
`habys.pl##html > body:style(overflow: visible!important;)`
Nie testowałem tego, bo nie mam teraz na to czasu, ale jak nie działa to wykombinujcie coś innego :)

**Comment by F4z** [comment]
Dodatkowe dwa:
`habys.pl##html.fancybox-lock:style(overflow: visible!important;)`
`habys.pl##html.fancybox-lock > body:style(overflow: visible!important;)`

**Comment by blocker999** [comment]
Ok, @F4z Dzięki, ja już potestuje i ewentualnie się odezwe.

**Comment by hawkeye116477** [comment]
@F4z Dzięki.
@blocker999 Jeszcze to na ściemnione tło na reszcie stron: `habys.pl##.fancybox-overlay-fixed`

**Comment by blocker999** [comment]
@hawkeye116477 OK

**Comment by hawkeye116477** [comment]
@blocker999 Jeszcze margines można poprawić na reszcie stron:
`habys.pl##html.fancybox-margin:style(margin-right: 0px!important;)`
