### ISSUE TITLE
flashscore.pl

### ISSUE THREAD

**Issue by adreporter** [azet12/PopupBlocker#6]
http://www.flashscore.pl/
Od czasu do czasu wyskakuje to okienko rejestracyjne
![przechwytywanie](https://cloud.githubusercontent.com/assets/18214146/20216210/9fbf7144-a819-11e6-8b5d-616122afd707.PNG)
Niestety, ale te filtry nie rozwiązują problemu
`www.flashscore.pl##.selected.registration`
`www.flashscore.pl###lsid-window-mask`
`||www.flashscore.pl/res/image/icon-close-3.png$image`
ponieważ jak ktoś będzie chciał się zarejestrować, to nie będzie mógł tego zrobić. Proszę znaleźć rozwiązanie.

**Comment by blocker999** [comment]
Proszę konkretnie opisać tzn: czy ma wyskakiwać to okienko rejestracyjne czy nie i co z tym problemem zarejestrowania się i na jakiej przeglądarce jest ten problem?, bo u mnie to zjawisko nie występuje.

**Comment by adreporter** [comment]
Nie ma wyskakiwać to okienko rejestracyjne, ale tak jak napisałem od czasu do czasu wyskakuje, napisałbym nawet rzadko, ale zawsze wyskakuje. Po prostu jak byś dodał te filtry które napisałem to nie będzie można się zarejestrować, dlatego proszę znaleźć rozwiązanie. Używam Firefox'a.

**Comment by blocker999** [comment]
OK

**Comment by blocker999** [comment]
Jak to wychwycić? 

Bo poluje na to od godziny.

Więcej

**Comment by blocker999** [comment]
Kiedy te okienko się pojawia tzn: co ile minut lub w jakich okolicznościach?.

**Comment by blocker999** [comment]
Nie wiem, może o to chodzi :


@@www.flashscore.pl##.selected.registration
www.flashscore.pl###lsid-window-mask
||www.flashscore.pl/res/image/icon-close-3.png$image

Teraz pasuje?, jeśli tak, to jutro to dodam a jeżeli nie to proszę o szczegóły.

**Comment by adreporter** [comment]
`@@flashscore.pl##.selected.registration`
Ten filtr rozwiązuje problem.

**Comment by blocker999** [comment]
Czy coś zmieniać na tej stronie czy zostawić tak jak jest?

**Comment by adreporter** [comment]
@F4z @gwarser Macie rację, mój błąd, ta reguła `@@www.flashscore.pl##.selected.registration` jest niepotrzebna. Myślałem, że rozwiąże ona "problem z usiłowaniem rejestracji wyskakującym okienkiem", ale jednak to nie jest ta reguła. Chodziło mi właśnie o to, żeby to okienko po prostu nie wyskakiwało: ma wyskakiwać tylko i wyłącznie jak się kliknie "REJESTRACJA". Pomożecie znaleźć odpowiednią regułę?

**Comment by gwarser** [comment]
`http://www.flashscore.pl/x/js/core_3_1227000000.js` w tym pliku to siedzi. Można zdekodować tutaj http://jsbeautifier.org/ . Funkcja `PopUpRegistration` zapisuje licznik w localStorage i po czasie wyświetla ten dialog.

**Comment by adreporter** [comment]
Dziękuję za odpowiedź. Nie ma co w to się bawić. Zamykam.
