### ISSUE TITLE
bartek.com.pl

### ISSUE THREAD

**Issue by blocker999** [azet12/PopupBlocker#66]
@hawkeye11647  Popup

**Comment by hawkeye116477** [comment]
@blocker999
```
bartek.com.pl##.journal-popup
bartek.com.pl##html:style(overflow: visible!important; margin-right: 0px!important;)
bartek.com.pl##.mfp-ready
```

**Comment by blocker999** [comment]
@hawkeye116477 Te chwilowe przyciemnienie ekranu które znika zaraz po wejściu na strone ma zostać i czy nic nieda się z tym zrobić?.

**Comment by hawkeye116477** [comment]
@blocker999 Nie wiem czy da się coś z tym zrobić, może trzeba spytać eksperta w tej dziedzinie zwanego @F4z.

**Comment by F4z** [comment]
A jak dodacie tę regułę:
`bartek.com.pl##.mfp-bg`
to nadal macie to chwilowe przyciemnienie?

**Comment by hawkeye116477** [comment]
@F4z Dzięki, teraz już nie ma.

**Comment by blocker999** [comment]
@F4z Potwierdzam, dzięki o to chodziło
