### ISSUE TITLE
nawozy.eu

### ISSUE THREAD

**Issue by blocker999** [azet12/PopupBlocker#67]
@hawkeye116477 Popup

**Comment by hawkeye116477** [comment]
@blocker999 `nawozy.eu##.newsletterPopup`

**Comment by blocker999** [comment]
@hawkeye116477 dzięki ale jeszcze scroll

**Comment by hawkeye116477** [comment]
@blocker999 `nawozy.eu##body:style(overflow: auto!important;)`

**Comment by blocker999** [comment]
@hawkeye116477 Fjnie, pieknie ale niedziała, poprawisz to czy lepiej wezwać kogoś do pomocy?

**Comment by hawkeye116477** [comment]
@blocker999 Dziwne, wcześniej zdaje się, że działało, teraz sprawdziłem i u mnie też nie działa. Dośc problematyczna strona, więc potrzebna jest pomoc speca @F4z.

**Comment by F4z** [comment]
W tym przypadku **chyba** się nie da tego zrobić przy użyciu reguły `:style()`, ale to powinno działać:
`nawozy.eu##script:inject(setTimeout-defuser.js, $(document).lockscroll(true);)`
Tylko proszę sprawdźcie czy niczego nie psuje.

**Comment by blocker999** [comment]
@F4z dzięki,działa, potestuje
