### ISSUE TITLE
nadmiarowe reguły

### ISSUE THREAD

**Issue by MajkiIT** [azet12/PopupBlocker#71]
```
rooader.pl###nicePopupWrapper has been made redundant by rooader.pl###nicePopupWrapper
homebook.pl##.popup-overlay--dark.popup-overlay has been made redundant by homebook.pl##.popup-overlay
limango.pl##.modal.in.fade.normalized has been made redundant by limango.pl##.modal
darmoweogłoszenia.pl###sidebar-boxes has been made redundant by pl###sidebar-boxes
darmoweogłoszenia.pl##.left_adv has been made redundant by pl##.left_adv
```

**Comment by blocker999** [comment]
@MajkiIT Dzięki

**Comment by MajkiIT** [comment]
@blocker999 nie ma problemu. Polecam się na przyszłość

**Comment by MajkiIT** [comment]
@blocker999 machnąłem pull https://github.com/azet12/PopupBlocker/pull/72

Pytanie ==> czy możesz w nagłówku dodać coś takiego ? Pozwoli to na szybkie wskazanie edycji pliku. 
`! v.2017082205 aktualizacja: wt, 22 sierpnia 2017, 21:35:00`

**Comment by blocker999** [comment]
@MajkiIT Moge dodać ten nagłówek, to jak?

**Comment by MajkiIT** [comment]
@blocker999 coś się namieszało ... 
np. nie ma ani darmoweogłoszenia.pl##.left_adv ani pl##.left_adv

Tą wartość dodajesz np. 11 linii i jak zmieniasz listę to podajesz konkretną datę i godzinę

**Comment by blocker999** [comment]
@MajkiIT To teraz co mam zrobić dodać ten nagłówek w punkcie 11 ?

**Comment by MajkiIT** [comment]
zrobię ci pulla :P

**Comment by blocker999** [comment]
@MajkiIT OK

**Comment by MajkiIT** [comment]
@blocker999 już

**Comment by blocker999** [comment]
@MajkiIT Dodane, teraz chyba ok?

**Comment by MajkiIT** [comment]
@blocker999 tak nagłówek jest ok, tylko reguły poginęły. Mój comment sprzed ok 10 min ..

**Comment by blocker999** [comment]
@MajkiIT Zaraz poprawie

**Comment by MajkiIT** [comment]
@blocker999 bo ty usunąłeś ogólne a ja w pull usunąłem nieogólne ... chyba namieszałem... sorry

**Comment by blocker999** [comment]
@MajkiIT To teraz jakie dać, czy obojętniie?

**Comment by MajkiIT** [comment]
ja bym dodał ogólne ... ale to moja wizja świata

**Comment by blocker999** [comment]
@MajkiIT OK, w takim razie tak poprawie.

**Comment by blocker999** [comment]
@MajkiIT Poprawione, przy okazji posortowałem, pasuje ? ( troche to trwało )

**Comment by MajkiIT** [comment]
Pięknie ... o dobry pomysł... dorobię do stronki sortowanie w sekcjach .... dziękuje

**Comment by MajkiIT** [comment]
Next time polecam to http://textmechanic.com/text-tools/basic-text-tools/sort-text-lines/

**Comment by blocker999** [comment]
@MajkiIT Wielkie dzięki
