### ISSUE TITLE
Popupy

### ISSUE THREAD

**Issue by hawkeye116477** [azet12/PopupBlocker#77]
@blocker999 Witaj rozrabiako! I gdzie ta robota, co miała dzisiaj być? Ja tu czekam od rana i nic nie ma, zawiodłeś mnie :smiley:.
A tak BTW to co tak wcześniej narozrabiałeś, że cb boty sprzątnęły? Bawiłeś się w spamera?

**Comment by blocker999** [comment]
@hawkeye116477 Spokojnie robota nie zając sorry tak wyszło że dziś się niewyrobiłem ale jutro oczekuj maila na gmailu a ten chwilowy ban to chyba przez osobe która straszyła mnie tu ostatnio moderatorem ale  
to tylko moje domysły więc nierozdrapujmy starych ran, najważniejsze że już jestem.

**Comment by hawkeye116477** [comment]
@blocker999 Ok, też tak myślałem, że to przez tą osobę, ale @azet12 twierdził, że to nie ma nic z tym wspólnego i powiedział, że cię sprzątnęli, bo bawiłeś się w spamera tak jak @xxcriticxx :smiley:. Ale dobrze, że wróciłeś i się zajmujesz PopupBlockerem, bo @xxcriticxx coś nie za bardzo był chętny do szukania popupów.

**Comment by blocker999** [comment]
@hawkeye116477 Co do pop-up to będe to dalej kontynuował wiec roboty Ci napewno niezabraknie ale chciał bym wreszcie dokończyć tą wersje z socialami bo już od tygodnia czeka na dodanie, no to jak pomożesz z tym pullem ?.

**Comment by hawkeye116477** [comment]
@blocker999 A z czym konkretnie masz problem?

**Comment by blocker999** [comment]
@hawkeye116477 Konkretnie chodzi mi o pożądny pull request czyli skopiuj sobie to : https://github.com/MajkiIT/polish-ads-filter/pull/3382
usuń to co niepotrzebne dodaj swoje ostatnie zmiany i scal a następnie dodaj jako swój pull na profillu MajkiIT a ja wtedy usune swój pull i będzie ok.

**Comment by gomoku** [comment]
Wydawało się, że sprawa została zakończona, ale jednak nie, bo:

> pewna osoba

coś dalej wrzuca na mnie, więc wybaczcie chłopaki, ale muszę się odnieść (jak coś to pretensje do tej osoby, że wszczyna):

`Początek obrony przed tą osobą:`

> @blocker999 więc nierozdrapujmy starych ran

To po co je rozdrapujesz? Nie ma to jak troll rozdrapujący stare rany, a jednocześnie prawiący o nierozdrapywaniu starych ran, to zwykła hipokryzja, którą zresztą już wcześniej u ciebie zaobserwowałem.

> @blocker999 która straszyła mnie

Znowu hipokryzja/odwracanie, bo jest odwrotnie, jeśli ktoś jest tym złym i tu/kogoś straszy co najwyżej ty swoim zachowaniem, opornym na jakiekolwiek argumenty, więc inaczej z tobą się nie da niż upomnieć/ostrzec cię (a nie straszyć), że zawoła się moderatora. Straszyć to mogą duchy albo strachy na wróble, jeśli czujesz się przestraszony, to możesz zawołać na pomoc Pogromców Duchów, ale to ciebie wciągną do odkurzacza.

Wydawało się, że sprawa została zakończona, ale jednak nie, bo tak jak w tamtym wątku, to i tutaj kontynuujesz swój personalny off-topic, wrzutkę na mnie i przedstawianie mnie jako agresora, kogoś złego, który straszy, a siebie jako pokrzywdzonej przestraszonej ofiary, za pomocą trollowych chwytów (hipokryzja, odwracanie kota ogonem), więc musiałem się do tego odnieść, a jeśli znowu zaczniesz rozdrapywać stare rany i coś o mnie pisać nieprawdziwego to znowu się odniosę, i tak w kółko, a to ty zarzucałeś mi przecież:

> @blocker999: a Ty dalej piszesz więc koniec.

Na co ci odpisałem, że to ty wszczynasz:

> @gomoku: To ty robisz wycieczki osobiste w moim kierunku i ciągniesz tę aferę, więc tylko odpisuję, a ty teraz kłamliwie i bezczelnie wszystko odwracasz i trolujesz, że to ja zaczynam

Już tam miałem rację, a tutaj tylko się ona potwierdziła, że to ty zaczepiasz mnie, a nie odwrotnie, przez co zmuszasz mnie do odpisywania, i w kolejnym wątku robisz flame.
`
Koniec obrony przed tą osobą`

Czy 

> ta osoba

dalej będzie zaczynać?

**Comment by hawkeye116477** [comment]
Ja tam nie wiem, co ty masz do @blocker999, ale temat zamykam, nie mam ochoty ani czasu na jakieś wojny/przepychanki.

**Comment by gomoku** [comment]
> @hawkeye116477 Ja tam nie wiem, co ty masz do @blocker999 

A ja z kolei tam nie wiem co ty do mnie masz, że imputujesz mi nieprawdę, że to ja coś mam do @blockera999, bo to nie ja mam coś do niego, tylko on coś do mnie znowu miał, a ja na to coś mu odpisałem, a teraz wyobraź sobie, że muszę na takie samo coś odpisywać teraz tobie, bo i ty coś do mnie jak widać już masz, nie wiem co wy do mnie macie, ale zamiast bronić za wszelką cenę kolegi i palić głupa jak on i odwracać kota ogonem, to lepiej się nie kompromituj jak twój kolega i zamknij ten wątek, bo nie mam ochoty ani czasu na jakieś wojny/przepychanki ze strony ciebie i twojego kolegi, a jeśli nie macie kogo się czepić, to możecie czepić się tramwaju. Jak widać, teraz muszę odkręcać, nie tylko hipokryzję i odwracanie kota ogonem ze strony @blockera999, ale teraz już ze strony jego broniącego go kolegi @hawkeye116477, ciekawe czy jeszcze ktoś się przyłączy do tej obrony kolegi za wszelką cenę.
