### ISSUE TITLE
https://dogry.pl

### ISSUE THREAD

**Issue by gomoku** [azet12/PopupBlocker#79]
! 29.08.2017, 10:51:25 https://dogry.pl/league-of-legends/qaa/8751922/co-tak-wlasciwie-znaczy-flame/

`dogry.pl##.register-overlayer--game.register-overlayer`
`dogry.pl##.register-modal`

![](https://s3.dodajfote.pl/2017/08/29/dogry_pl9b586.jpg)

**Comment by Ravizz** [comment]
Nie wiem czy teraz to kwalifikuje się do
Polskie filtry elementów irytujących czy do 
Polskie filtry społecznościowe, ale dalej wyskakuje Popup na wejściu:

https://dogry.pl/league-of-legends/qaa/8751922/co-tak-wlasciwie-znaczy-flame/?lead=promotion&utm_campaign=SEO&utm_target=forum&utm_format=www.google.pl&utm_source=other&language=pl

przykładowa gotowa reguła: `dogry.pl##.register-overlayer--game.register-overlayer, .register-modal`

### Co trzeba zrobić, aby pojawił się irytujący element?
1. Wejść na stronę

### Moja konfiguracja
**Przeglądarka internetowa:** 
FF 57.0.4 / O 50.0.2762.58 (PGO)
**System operacyjny:** 
Windows 7 PL SP1 U 64
**Bloker:** 
Nano Defender 13.20
uBO v1.14.25rc1
**Używane filtry:**
1. Polskie filtry elementów irytujących
2. POL: polskie filtry do Adblocka i uBlocka​​​​​
3. POL: polskie filtry do uBlocka uzupelnienie
4. Polskie filtry ciasteczkowe
5. KAD - Przekręty​
6. Adblock & uBlock polish filter - Adguard supplement
7. EasyList
8. Adblock Warning Removal List
9. Adguard Base Filters
10. uBlock filters
11. uBlock filters – Unbreak
12. Nano Defender Integration
13. NanoBase
14. NanoTimer
15. NanoWhitelist
16. Fanboy’s Social Blocking List
17. Polskie filtry społecznościowe

### Zrzut ekranu
![](https://s3.dodajfote.pl/2018/01/19/gry3cd53df350763f1e.png)

**Comment by hawkeye116477** [comment]
@Ravizz Jak najbardziej to do Polskich filtrów elementów irytujących. Dzięki, zaraz dodam :smile:.
