### ISSUE TITLE
wanika.pl

### ISSUE THREAD

**Issue by hawkeye116477** [azet12/PopupBlocker#85]
@blocker999 Takie coś też blokujemy?
![screenshot_20170911_180645](https://user-images.githubusercontent.com/19818572/30284816-4f3cc648-971c-11e7-903c-d07ea2c32560.png)

`wanika.pl###cloudBox`

**Comment by blocker999** [comment]
@hawkeye116477 TAK wszelkiego typu buttony które są na marginesie stron blokujemy a wszczególności takie  " natrętne " jak ten, tzn jeżdżące za nami,
