### ISSUE TITLE
kodiwpigulce.pl

### ISSUE THREAD

**Issue by hawkeye116477** [azet12/PopupBlocker#86]
@blocker999 Coś ten gość jest za nachalny z tymi dotacjami, więc chyba schowamy to, nie :smile:?
https://screenshots.firefox.com/JYvyjLUGDhUNrGGm/kodiwpigulce.pl

`kodiwpigulce.pl##.is-fixed.sidebar-box`

**Comment by blocker999** [comment]
@hawkeye116477 niewiem, poprosze kogoś trzeciego o opinie np @gzenio22 bo korzysta z tej strony.

**Comment by blocker999** [comment]
@hawkeye116477 OK blokujemy poprostu wczoraj zasugerowałem się screenem i pomyślałem że to zwykłe info z prośbą o wsparcie no ale jak dziś weszłem na strone to już zrozumiałem oco ten krzyk bo o ile ten scroll na głównej to picuś tak już w jakimkolwiek artykule on wkurza delikatnie mówiąc no i ten sam problem jest w pozostałych załadkach, mało tego to jest jesz na forum.

Swoją drogą to niewiem co on przez to chce osiągnąć?.

**Comment by gzenio22** [comment]
jesli dobrze rozumiem chodzi o ten bannerek po prawej o kawie Xd zdejmijcie to w diabły lata to na kazdej podstronie

**Comment by hawkeye116477** [comment]
@blocker999 @gzenio22 Ewentualnie można go zostawić, tylko zrobić tak, żeby nie latał:
`kodiwpigulce.pl##.is-fixed.sidebar-box:style(position:static!important;)`.

**Comment by blocker999** [comment]
@hawkeye116477 Pomysł z zatrzymaniem tego ok, tylko to niezmienia faktu że kto będzie chciał im wpłacić to bez info się obędzie a jak ktoś niechce to ani prośbą ani grożbą, narazie to usune a jak ktoś się kiedyś przyczepi to ewentualnie to zmienimy na statyczny.

**Comment by blocker999** [comment]
@hawkeye116477 Aha oprócz info są dwa irytujące elementy mianowicie tzw " podpowiadacz artykułów i strzałka, je też usunąć?

![kodi](https://user-images.githubusercontent.com/23176832/30321881-ecec131c-97b7-11e7-93f1-74e9881b23ad.png)

**Comment by gzenio22** [comment]
strzalke zostaw a podpowiadacza moim zdaniem mozna ukryc

**Comment by hawkeye116477** [comment]
@blocker999 Ja podpowiadacza nie widzę. Ale strzałkę to można zostawić.

**Comment by blocker999** [comment]
@hawkeye116477 podpowiadacz jest tylko najpierw trzeba wejść w jakiś artykuł zjechać całkiem do dołu stronyi pojawi się po prawej, widocznie strzałki tylko mnie drażnią ale do czego one skoro to nie las?.

**Comment by hawkeye116477** [comment]
@blocker999 Po to żeby przejść szybciej na górę strony. Niestety nadal podpowiadacza nie widzę, wyświetla się czasami jedynie taka niespodzianka.
![screenshot_20170912_130203](https://user-images.githubusercontent.com/19818572/30322700-a658ff7a-97ba-11e7-99e9-f2b38210b511.png)

**Comment by gomoku** [comment]
Może żeby uporządkować trochę kwestię pływającego banera donacji - tak naprawdę są trzy rozwiązania:
1) podane przez hawkeye116477: 
`kodiwpigulce.pl##.is-fixed.sidebar-box` - 
**jest połączeniem unieruchomienia z usunięciem** 
po zastosowaniu tej reguły, baner z dotacją dalej się pojawia, ale jest unieruchomiony, i znika dopiero po przewinięciu strony trochę w dół
2) podane również przez hawkeye116477: 
`kodiwpigulce.pl##.is-fixed.sidebar-box:style(position:static!important;)` 
**to unieruchomienie**
3) podane przeze mnie: 
`kodiwpigulce.pl###right1-sidebar`
`kodiwpigulce.pl###left1-sidebar` 
**to usunięcie**

I teraz dwa pytania:
a) które rozwiązanie wybrać
b) kto ma decydować o wyborze rozwiązania:
- wszyscy współtwórcy solidarnie (demokracja, głosowanie)
- główny współtwórca (blocker999)
- zgłaszający reklamę (hawkeye116477)

Dalej, to co co się wiąże z odpowiedzią na obydwa pytania to ogólne pytanie pochodne: 
c) czy są jakieś jasne ogólne z góry ustalone zasady/regulamin/obyczaje, które by odpowiedziały na te pytania, a jeśli nie ma to czy powinny być lub czy za każdym trzeba się zastanawiać i debatować nad każdą tego typu reklamą.

Myślę, że najpierw trzebaby sobie odpowiedzieć na pytanie czy gdyby ten element z donacją był z góry unieruchomiony przez twórcę strony i nie jeździł razem z suwakiem, to czy wtedy zostałby całkowicie usunięty jak typowa reklama? Jeśli tak to teraz należy wybrać rozwiązanie 3 czyli właśnie całkowicie go usunąć, a jeśli nie zostałby usunięty, to trzeba teraz generalnie wybrać rozwiązanie 2 czyli unieruchomienie,  W sumie zaintrygowało mnie rozwiązanie 1 -  jest ono na swój sposób ciekawe, i jest takim kompromisem, czyli usunąć reklamę, ale nie tak bestialsko i odrazu w trymig, tylko niech przez chwilę sobie pobędzie.

**Comment by hawkeye116477** [comment]
Mnie się wydaję, że jednak lepiej byłoby dać to jako statyczne. Bo tak to jeśli to usuniemy, to raczej nikt się nie dowie o możliwości wsparcia. No chyba, że gdzieś jest jeszcze jakiś link dot. wsparcia, a ja nie zauważyłem. No i wybór powinien być raczej demokratyczny, czyli to co wybierze większość.

**Comment by gzenio22** [comment]
nie ma innej informacji o dotacjach wiec lepiej tą poprostu usadzic na jednym miejscu ci co tworza ta strone robia dobra robote nie ukrywajmy a server tez odrobine pewnie kosztuje szczegulnie jak zrobili forum

**Comment by blocker999** [comment]
@hawkeye116477 strzałke zostawiam bo widze że jest pomocna choć ja używam na laptopie skrótów klawiaturowych, wiec mi to wydawało się zbędne ale teraz zmieniłem zdanie no bo niezawsze istnieje ocja klawiatury lub jest ona utrudniona.

**Comment by blocker999** [comment]
@hawkeye116477 To jak robimy?, bo mi to lotto.
.
Z ciekawostek powiem że to samo jest na forum.

![forum](https://user-images.githubusercontent.com/23176832/30329323-400e8484-97d2-11e7-87cb-2a033e19b1c6.png)

**Comment by hawkeye116477** [comment]
@blocker999 Tak robimy: `kodiwpigulce.pl##.is-fixed.sidebar-box:style(position:static!important;)` :smile:.

**Comment by blocker999** [comment]
@hawkeye116477 Ok a forum?

**Comment by hawkeye116477** [comment]
@blocker999 Zostawiamy.
