### ISSUE TITLE
mods-kodi.pl

### ISSUE THREAD

**Issue by gzenio22** [azet12/PopupBlocker#87]
Co byscie sie nie nudzili chłopcy przy włączonym popup blockerze plus nie wskakuje okno logowania da rade to naprawic czy to wada krytyczna? Xd 

@hawkeye116477 @blocker999

**Comment by hawkeye116477** [comment]
Problemem jest ta reguła -> `pl###dialog`, więc albo to do usunięcia albo wyjątek -> `mods-kodi.pl#@##dialog`
