### ISSUE TITLE
goldenline.pl

### ISSUE THREAD

**Issue by gomoku** [azet12/PopupBlocker#89]
http://www.goldenline.pl/grupy/Komputery_Internet/zarabianie-przez-internet/casino-euro-sposob-na-szybkie-pomnozenie-kapitalu,3020574/

![](https://s3.dodajfote.pl/2017/09/13/goldenlinePopupd62a6.png)

**Comment by hawkeye116477** [comment]
`goldenline.pl##.ui-widget-overlay, .invitationDialog`

**Comment by gomoku** [comment]
@hawkeye116477, być może i wystarczy, ale ja tego nie sprawdzę, bo gdy tu tę stronę zgłaszałem to od razu chciałem zrobić i w komentarzu podać jakiś gotowy filtr, tak jak teraz ty, ale wyobraź sobie, że po kilkuminutowych męczarniach odpuściłem bo nie mogłem wejść na stronę bo ciągle wyskakiwała captcha do wypełnienia, a gdy ją wypełniłem to następna i tak bez końca, chyba ich poj....ło z tą captchą równo, ile razy można captchę wypełniać zanim człowiek zwariuje? To jest jakaś wyjątkowo złośliwa i upierdliwa captcha, z jaką się wcześniej ni spoktałem, i która skutecznie mnie zniechęciła, a w sumie to jest captcha po captchy chyba z 10 czy 15 captch pod rząd wypełniłem i dalej kolejne captche, za drugim razem to samo, odpuściłem temu ścierwu. A z ciekawości zapytam czy u ciebie ta captcha też wyskakiwała tyle razy? I jak sobie z nią poradziłeś? Jak to wyglądało u ciebie? W sumie to być dałoby się ją wyłączyć w adblocku jakimś filtrem sieciowym ale dopiero teraz mi to do głowy, chociaż nie wiem czy tak się da, bo nigdy tego nie próbowałem bo nigdy nie miałem tak złośliwej captchy w życiu. :)

**Comment by hawkeye116477** [comment]
@gomoku Captcha wyświetlała się gdzieś tak z 3-4 razy. Ale chyba regułą niestety się nie da tego zablokować, a szkoda, bo też mnie to wkurza.

**Comment by gomoku** [comment]
Hehe najpierw zaatakowała mnie ta złośliwa captcha, ale jak pewnie zauważyłeś to nie jedyny problem u mnie, bo także zaatakował mnie złośliwy github, obydwa ataki/incydenty w tym samym momencie, myślę sobie tak, że brakuje, żeby mnie jeszcze komar ugryzł w tyłek i będzie hattrick problemów na dziś :)
