### ISSUE TITLE
390 filtrów niepoprawnych

### ISSUE THREAD

**Issue by gwarser** [azet12/PopupBlocker#9]
Filtry kosmetyczne zaczynające się od kropki (`.pl##...`) są niepoprawne, troszkę się gryzą z logiem uBlocka (puste szczegóły jak się kliknie na filter), a gorhill pisze, że w ABP nie działają wcale.

Jest też kilka niepoprawnych selektorów - możesz sprawdzić tutaj https://arestwo.org/famlam/redundantRuleChecker.html

**Comment by azet12** [comment]
Ok, usunąłem kropki. Resztą niech zajmie się @blocker999

**Comment by blocker999** [comment]
Poprawiłem ale nie wiem czy to wszystko?

**Comment by gwarser** [comment]
Nadal są błędy. Niepoprawnie wskazuje tylko te z `...:style(overflow: auto !important;)`, bo to rozszerzenie Ublocka.

To jest coś dziwnego: `@@www.flashscore.pl##.selected.registration`.
Wyjątki robi się tak: `www.flashscore.pl#@#.selected.registration`

Te mogą być tylko `pl`, bez `radomsport`, albo brakuje `~` (negacja) przed radomsport.
   pl,radomsport.pl###skyscraper
   pl,radomsport.pl###skyscraper2

To wygląda na dwie sklejone linie `pl###popup_prettyone###ab5793095750e7d8deaf0a68309dec76e` ?

**Comment by blocker999** [comment]
ok zajme się dziś tym

**Comment by blocker999** [comment]
Ok troche poprawiłem, tzn:

 `  ...:style(overflow: auto !important;)` - zostawiłem gdyż ten skrypt jest do strony aligoo.pl i został zaproponowany przez @F4z w tym temacie: autokult.pl #1387
ewentualnie proszę o inny skrypt by go wymienić.

Te dziwne wyjątki też zostawiłem gdyż chyba są poprawne ale mogę się mylić, więcej tu : https://mozillapl.org/wiki/Tworzenie_filtrów_dla_rozszerzenia_Adblock_Plus

a pozostałe filtry pozmieniałem według Twych sugestii.

**Comment by gwarser** [comment]
Te są do odblokowywania adresów https://adblockplus.org/en/filters#whitelist
a te do odblokowywania elementów strony https://adblockplus.org/en/filters#elemhide_exceptions

**Comment by blocker999** [comment]
Ok dzięki za lekture, poczytam kilka razy ze zrozumieniem i ewentualnie coś poprawie ale to wieczorem.

**Comment by blocker999** [comment]
Nie jestem pewie czy to zmieniać, więc postanowiłem otworzyć temat flashscore.pl #6

**Comment by F4z** [comment]
@blocker999 jak dla mnie, to tę regułę - `@@www.flashscore.pl##.selected.registration` - można wyrzucić, bo tak jak już napisał @gwarser jest nieprawidłowa i z tego co widzę niepotrzebna.
Jak wejdziesz na stronę - `http://www.flashscore.pl/` to na górze masz przycisk "Rejestracja" i działa normalnie.
W zasadzie, to nie wiem o co dokładnie chodziło w tym zgłoszeniu - https://github.com/azet12/PopupBlocker/issues/6
Nie wiedzę żeby taka reguła - `www.flashscore.pl##.selected.registration` - była na liście przed tym zgłoszeniem, więc chyba zostało to tam podane żeby tego nie dodawać do listy?

Tak samo nieprawidłowe są jeszcze te dwie reguły:
`@@aligoo.pl##.remodal-wrapper`
`@@caseih.com.pl###cboxOverlay`
Poprawnie powinno to wyglądać tak:
`aligoo.pl#@#.remodal-wrapper`
`caseih.com.pl#@##cboxOverlay`

**Comment by blocker999** [comment]
ok tak poprawie ale temat zostawie otwarty może ktoś jeszcze coś powie
