### ISSUE TITLE
polki.pl

### ISSUE THREAD

**Issue by gomoku** [azet12/PopupBlocker#90]
http://polki.pl/zdrowie/prawa-pacjenta,alkohol-w-ciazy-bedzie-przymusowe-leczenie-dla-ciezarnych,10425184,artykul.html

Coś podobnego i równie agresywnego jak https://github.com/azet12/PopupBlocker/issues/86 Wchodzimy na przykładową podstronę podaną wyżej, przewijamy w dół nie za szybko, do momentu aż odpali się automatycznie statycznie osadzony film z reklamą, gdy będziemy dalej kontynuować przewijanie w dół, film wyskoczy ze swojego miejsca jak niemiec z bunkra albo Filip z konopii, zmniejszy się do postaci miniatury i przyczepi się do rolki przewijania po prawej stronie i będzie za nami bezczelnie jeździł w dół jak w  https://github.com/azet12/PopupBlocker/issues/86, gdy zaczniemy przewijać z powrotem w górę, film dalej będzie jeździł do momentu przewinięcia strony do miejsca gdzie był wcześniej osadzony i wtedy powiększy się do pierwotnego rozmiaru i wskoczy z powrotem do swojego legowiska, jeśli zaczniemy przewijać w dół, znowu wyskoczy i tak w kółko.

**Comment by hawkeye116477** [comment]
Tutaj się wyjątkowo postarali. Nie wiem jak usadzić ten filmik na miejscu, więc proszę o pomoc @F4z.

**Comment by gomoku** [comment]
Hehe no właśnie, też z początku próbowałem jakiś filtr wymyślić, ale dałem sobie siana. :)

**Comment by blocker999** [comment]
@gomoku 

Przyjże się tej sprawie i coś zadziałamy ale to jutro.

**Comment by gomoku** [comment]
> @blocker999: zachęcające do profilaktyki kobiet

no i właśnie to jest kwestia dyskusyjna, bo jeżeli intencją tego czegoś byłoby rzeczywiście, tak jak piszesz, zachęcanie do profilaktyki, to to coś raczej nie byłoby tak agresywne, żeby latać po całej stronie: przeskakiwać z lewej na prawo, siadać na scrollu,  jeździć za scrollem i molestować użytkownika. Intencją tak agresywnego zachowania jest raczej nagabywanie na płatne badania, żeby lekarze zarobili.

**Comment by hawkeye116477** [comment]
Ale tutaj to chyba jest coś przydatnego -> http://polki.pl/dom/porady-domowe,jak-ustawic-pralke-porady,10044431,artykul.html .

**Comment by hawkeye116477** [comment]
Ale tutaj to chyba jest coś przydatnego -> http://polki.pl/dom/porady-domowe,jak-ustawic-pralke-porady,10044431,artykul.html .
@gomoku Od autoplaya są skrypty, np. https://greasyfork.org/en/scripts/30974-autoplay-disabled-for-html5-videos-pause-on-switch-tab albo https://greasyfork.org/pl/scripts/30271-html5-video-autoplay-blocker. Ten pierwszy to na pewno działa na tą stronę.

**Comment by gomoku** [comment]
Dzięki :) obydwa działają, video nie tylko zatrzymane, ale nawet siedzi na dupie i nie lata, bo np. zwykłym sposobem typu Firefox > about:config > media.autoplay.enabled > false, to co prawda też się  nie odtwarzało, ale dalej wyskakiwało z gniazda, a teraz to cisza i spokój.

**Comment by hawkeye116477** [comment]
@gomoku Autoplaya raczej nie zablokujemy filtrem. Jedynie może da radę coś zdziałać na ten latający filmik, ale to już w tej kwestii ekspert @F4z musi się wypowiedzieć :smile:.

**Comment by gomoku** [comment]
OK, to wtedy wystarczy dodatkowo `Firefox > about:config > media.autoplay.enabled > false` żeby zastopować i będzie git.

**Comment by hawkeye116477** [comment]
W kodzie skryptu też można dodać whitelist 😄.
Violentmonkey->Otwórz panel sterowania->AutoPlay Disabled->Edytuj
```
// For websites you won't to disable this script on, you can add domains (with or without subdomain, must not include http://, etc.) to always allow auto-play (doesn't affect pause on leave tab)
    var autoPlaySitesWhitelist = [
        // "youtube.com"
    ];
```

**Comment by gomoku** [comment]
Nadal za dużo grzebania się, powinno to być tak proste jak dodanie strony do zakładek - jedno kliknięcie.

**Comment by hawkeye116477** [comment]
No i niestety lipa, bo @AdamWr jak widać woli pomagać zagranicznym niż Polakom 😞 .

**Comment by hawkeye116477** [comment]
No i niestety lipa, bo my jesteśmy dopiero na miejscu 999 w kolejce u @AdamWr / @F4z, czyli może za miesiąc nas odwiedzi jak się uda 😃 .

**Comment by AdamWr** [comment]
Szczerze mówiąc nie chce mi się dokładnie tego sprawdzać, bo dla mnie to mało istotny problem i nie mam ostatnio za dużo czasu, ale możecie sprawdzić tę regułę (u mnie po dodaniu tej reguły odtwarzacz zostaje na swoim miejscu):
`polki.pl##script:inject(addEventListener-defuser.js, scroll, d.stopPropagation)`

Nie mam pojęcia, czy czegoś gdzieś na stronie nie psuje, jeśli coś nie działa, to musicie coś sami wymyślić :)
Ewentualnie poczekać w kolejce aż zrobię inne 998 zgłoszeń (😛), chociaż i tak nie obiecuję, że uda mi się coś lepszego znaleźć.

**Comment by blocker999** [comment]
Reguła  Adama jest prawie ok bo usuwa ten drugi player ale autoplay pozostaje, dlatego narazie proponuje wtyczke Disable HTML5 Autoplay do trzech wersji przeglądarek i ich pochodnych, wiem że to połowiczne rozwiązanie ale lepsze narazie i to.

https://chrome.google.com/webstore/detail/disable-html5-autoplay/efdhoaajjjgckpbkoglidkeendpkolai/related

https://addons.mozilla.org/pl/firefox/addon/disable-autoplay/

https://addons.opera.com/pl/extensions/details/disable-html5-autoplay/?display=en

@hawkeye116477  Proponuje to dodać jako ogólnik,, bo podobnych playerów jest kilka, co?

**Comment by hawkeye116477** [comment]
@blocker999 Co nie znaczy, że na wszystko będzie działać ok, lepiej zostawić na razie na tą jedną stronę.

**Comment by hawkeye116477** [comment]
@blocker999 Co nie znaczy, że na wszystko będzie działać ok. A pamiętam, że na wp jakaś reguła z script:inject sprawiała problemy. Ale tak w ogóle to tego się nie da dać jako ogólnik, musi być do konkretnej strony, bo inaczej to nie działa.
Jaki drugi player, jak player jest i był jeden, tylko że się ruszał 😃 .

**Comment by blocker999** [comment]
@hawkeye116477 Skoro tak, to dodaj tak jak jest a jak znajdą się inne strony o tym samym problemie to się je dopisze.

**Comment by hawkeye116477** [comment]
@blocker999 Ok, no w sumie innego wyjścia nie ma, bo ta reguła nie działa jako ogólna, tak dobrze nie ma niestety albo stety, może tak specjalnie jest to zrobione, by niczego nie popsuć 😄 .

**Comment by gomoku** [comment]
@blocker999 ale zobacz co napisałem tu: https://github.com/azet12/PopupBlocker/issues/108#issuecomment-330217372, a w skrócie ten dodatek nie działa u mnie na FF w ogóle, szkoda bo to o taki dokładnie dodatek chodzi, prosty jak budowa cepa, jednym kliknięciem się ustawia na której stronie ma blokować autoplay lub nie. 

A u was on działa?
@blocker999 u ciebie ten dodatek działa skoro polecasz?
@hawkeye116477 a u ciebie działa,  bo tu: https://github.com/azet12/PopupBlocker/issues/108#issuecomment-330062808 pisałeś, że nie testowałeś, czy już przetestowałeś, jeśli nie to czy mógłbyś?

**Comment by hawkeye116477** [comment]
@gomoku Na Waterfoksie 55.0.2  na polki.pl niby działa, ale wtedy wcale filmik nie chce się odtwarzać 😃. A na YT to tak jak piszą w komentarzach, nie działa. 
Natomiast na Vivaldim działa na polki.pl i filmik normalnie się odtwarza, ale na YT już to nie działa.

Skrypty chyba lepsze, bo przynajmniej na YT działają, ale ten z Pause on Switch Tab to tak nie do końca, bo przez sekundę się odtwarza.

**Comment by blocker999** [comment]
@gomoku u mnie jest idealnie ale na Slimjet a FF nietestowane, być może się pośpieszyłem ale będe to korygował w kolejnych dniach.

**Comment by hawkeye116477** [comment]
Google już pracuje nad natywnym blokowaniem autoplaya -> https://blog.chromium.org/2017/09/unified-autoplay.html .  A w Operze już chyba jest natywne zdaje się -> http://ccm.net/faq/29452-opera-disable-the-auto-play-multimedia-content.

**Comment by gomoku** [comment]
@hawkeye116477 u mnie wszystko tak samo jak u ciebie, z tą różnicą, że u mnie działa bezproblemowo na Operze, a u ciebie na Vivaldi, a u @blockera na Slimjet, czyli u każdego działa, ale na innej przeglądarce, śmiać mi się chce (parsknął śmiechem). Zobacz też mój post wyżej bo edyowałem.

**Comment by hawkeye116477** [comment]
@gomoku Tak, chyba będzie globalnie, ale będzie też można całkowicie wyłączyć dźwięk dla wybranej strony.

> Starting in Chrome 64, autoplay will be allowed when either the media won’t play sound, or the user has indicated an interest in the media.

> Not all users have the same preferences for autoplay media, so Chrome 63 will add a new user option to completely disable audio for individual sites. This site muting option will persist between browsing sessions, allowing users to customize when and where audio will play.

Tak właściwie, to Slimjet, Opera i Vivaldi bazują na Chromium. W przypadku Vivaldi to nawet chyba nie usuwali nic z kodu Chromium, tylko nakładkę dali. Także te 3 przeglądarki można uznać za jedną.

A te zmiany Google, to dopiero od nowego roku wejdą.

![obraz](https://user-images.githubusercontent.com/19818572/30614010-524a0660-9d8a-11e7-83eb-c88fddb82591.png)

**Comment by gomoku** [comment]
Co do tych 3 przeglądarek to racja, to wszystko Chromium.

A co do autoodtwarzania filmów, ale bez dźwięku, to nadal efekt uboczny, bo nadal buforuje i zjada łącze, oraz film leci co rozprasza uwagę.

**Comment by hawkeye116477** [comment]
@gomoku No w sumie racja, ale przynajmniej nie będzie głośno na komputerswiat.pl i innych stronach 😃  Bo tam to normalnie kołtuna można dostać jak nagle filmik się odpala. 
Autoplay domyślnie będzie blokowany, więc miejmy nadzieję, że może to Google rozwiąże lepiej niż Mozilla i będzie można normalnie odtwarzać filmiki, a wtedy ten whitelist nie będzie potrzebny.
Ale jeśli na jakiejś stronce zrobią tak, że wyłączą dźwięk, a autoplay będzie leciał, no to już Google niestety tego nie zablokuje.

**Comment by blocker999** [comment]
Niewiem ale umnie jest ok i na polski.pl i na nerwica.com to wszystko sprawdzane na Slimjet oraz teraz sprawdzałem na Waterfoxie, więc chyba warto przesiąść się na Waterfokca bo stary dobry FF.

**Comment by hawkeye116477** [comment]
@blocker999 No jasne, że warto, tym bardziej, że nadal będą tam stare rozszerzenia, tj. Classic Theme Restorer, All in One Sidebar, DownThemAll i inne pozwalające na spore zmiany w przeglądarce oraz nie będzie cenzury.

**Comment by blocker999** [comment]
@hawkeye116477 Ja to wiem i korzystam ale @gomoku to powiedz, bo ja żegnam.

**Comment by hawkeye116477** [comment]
@blocker999 Ok.
@gomoku Polecam Waterfox, lepszy niż Firefox 😄 .

**Comment by gomoku** [comment]
I tak na dniach będę się przesiadał z FF 32bit na FF64bit, więc nie omieszkam także przetestować przy okazji Waterfoxa, jeśli okaże się lepszy od FF, to się na niego przerzucę.

**Comment by blocker999** [comment]
@gomoku SUPER, tylko po testach jakbyś móg ją tu troche opisz tzn czy jest lepsza/gorsza i dlaczego.

**Comment by hawkeye116477** [comment]
Waterfox niedługo będzie też na Androida, ciekawe tylko jak będzie z wydajnością, bo w przypadku Firefoxa to na Androidzie kiepsko. Dlatego też ja korzystam tam z Yandex Browser, do którego nie dość, że można uBlocka doinstalować i inne rozszerzenia z Chrome, to jest szybszy, wydajniejszy. 

A tak ap ropo to powiem wam, że Alex zamierza hostować własny addon store dla Waterfoxa i inne usługi, by uniezależnić się od Moz://:.  Na pewno będzie Waterfox Sync, no bo skoro ma kontynuować wsparcie dla starych rozszerzeń, no to bez tego się nie obędzie. 
Jedyną wadą Waterfoxa jest chyba to, że aktualizacje są nieco później niż te dla Firefoksa. Cyberfox niby szybciej wydaje aktualizacje, ale niestety aktualnie już tylko do 52 ESR. A no i może wadą jest też to, iż nie ma specyficznych wyszukiwarek dla języków, czyli np. Wikipedia jest domyślnie angielska, ale w sumie można sobie ręcznie to dodać, więc nie jest to aż taka wielka wada.

**Comment by gomoku** [comment]
A więc zainstalowałem tego Waterfoxa 55.0.2 64bit i jeśli chodzi o ten dodatek do blokowania autoplay to nic się nie zmieniło i dalej jest to samo co w FF, jak opisałem tu: https://github.com/azet12/PopupBlocker/issues/90#issuecomment-330653910 

@blocker999 skoro pisałeś, że ci działa ręczne odpalanie filmu na polki.pl na Waterfoxie to prawdopodobnie zadziałało ci losowo raz akurat właśnie jak sprawdzałeś, bo faktycznie dzisiaj sprawdzałem dokładnie i losowo to on potrafi zadziałać, ale raz na kilka razy o czym napisałem dzisiaj tu: https://github.com/azet12/PopupBlocker/issues/90#issuecomment-330653910 << przeczytajcie ten post bo go edytowałem. 

@blocker999 i (jeśli da radę to @hawkeye116477) mógłbyś sprawdzić jeszcze raz, tylko kilka razy np. odśwież stronę i znowu sprawdźi tak kilka razy, potem zamknij kartę i znowu wejdź na stronę, prawdopodobnie zauważysz, że częściej nie działa, niż działa, a czasem to nawet zamiast przycisku play jest przycisk pauzy i wtedy to na pewno filmu się nie uruchomi.

Druga rzecz to taka, że na Waterfoxie jest uwalona czcionka, bo jest cholernie brzydka, rozmazana i nieostra:
![](https://s3.dodajfote.pl/2017/09/20/fontblurry1b479.png)

Więc niestety nie mam powodów na razie, żeby przesiadać się na WF.

**Comment by blocker999** [comment]
@gomoku Niewiem czemu mi działa wszystko nawet YT, sprawdzałeś na slimjet?, jeśli nie to sprawdż, choćby testowo.

**Comment by hawkeye116477** [comment]
@gomoku Faktycznie, u ciebie widzę rozmazaną czcionkę, ale u mnie tak nie jest. Może wyłączenie akceleracji graficznej coś pomoże.

**Comment by gomoku** [comment]
@blocker999 A po co na SlimJet, skoro to jest na bazie Chromium, a jak już pisałem na Operze dodatek działa, ale moją główną przeglądarką jest FF.

@hawkeye116477 pomogło, ale kosztem tego, że teraz:
- przy przewijaniu strony występuje flickering
- no i nie ma akceleracji sprzętowej
No i:
- działanie dodatku nadal się nie zmieniło

**Comment by blocker999** [comment]
@gomoku Rób co chcesz

**Comment by hawkeye116477** [comment]
@gomoku Czyli zrobiłeś tak -> https://support.mozilla.org/en-US/kb/troubleshoot-extensions-themes-to-fix-problems#w_turn-off-hardware-acceleration i nie pomogło. A w Firefoksie masz włączoną akcelerację i ten problem nie występuje, nie masz rozmazanej czcionki? A działanie dodatku, to wiadomo, że od tego się nie zmieni. 
@blocker999 @gomoku Ma rację.

**Comment by gomoku** [comment]
> @hawkeye116477: @gomoku Czyli zrobiłeś tak -> https://support.mozilla.org/en-US/kb/troubleshoot-extensions-themes-to-fix-problems#w_turn-off-hardware-acceleration i nie pomogło.

Dokładnie tak zrobiłem i przecież napisałem, że pomogło, a gdzie ty wyczytałeś, że nie pomogło? No, chyba, że literówkę walnąłeś bo napisałeś "i nie pomogło" zamiast "pomogło" ?.

> @hawkeye116477: A w Firefoksie masz włączoną akcelerację i ten problem nie występuje, nie masz rozmazanej czcionki?

Dokładnie.

**Comment by hawkeye116477** [comment]
@gomoku Ta, miało być pomogło. Czyli pewnie Alex coś sknocił. A mi na Linuxie działa ok, może to tylko Windy dotyczy. Ale ja to w sumie mam trochę inną wersję niż oficjalną, sam kompilowałem z poprawkami dla lepszej integracji z KDE Plasma , no i też parę rzeczy wywaliłem, które kompletnie mi się nie przydadzą 😃  .

**Comment by gomoku** [comment]
@blocker999 na SlimJet dodatek działa na polki.pl i www.nerwica.com, czyli lepiej niż na Operze bo na Operze działał tylko na polki.pl. A czy teraz mógłbyś łaskawie odpowiedzieć jaki masz system?

**Comment by hawkeye116477** [comment]
@gomoku Sprawdzałem u siebie na W7 I mam poszarpaną czcionkę zarówno na Waterfoxie jak i Firefoksie i wyłączenie akceleracji nie wiele pomaga, tylko Chrome poprawnie wyświetla.

**Comment by gomoku** [comment]
@hawkeye116477 ale poszarpana, a rozmyta to mogą być dwie różne kwestie, bo ja też miałem poszarpaną na FF ale naprawiłem wpisem w about:config:
` gfx.font_rendering.cleartype_params.rendering_mode` na `true`

**Comment by hawkeye116477** [comment]
@gomoku Nic z tego, chyba już wszystkiego próbowałem i nadal jest poszarpana, ale nie jest rozmyta, tylko poszarpana i akceleracja czy jej brak niczego nie zmienia, na WF i FF tak samo.

**Comment by gomoku** [comment]
Zastanawia mnie jakim cudem u @blocker999 ten dodatek działa na FF/WF na polki.pl i www.nerwica.com przy ręcznym odpalaniu filmu, skoro i u ciebie i u mnie na FF nie działa ręczne odpalanie filmu na polki.pl (no może czasem od biedy zaskoczy raz na kilka razy), a na www.nerwica.com w ogóle ten dodatek nam nie działa. No już dwa razy się go pytałem jaki ma system to odpowiedzi brak.

**Comment by hawkeye116477** [comment]
Ciekawe, w about:support pisze, że proces GPU jest niedostępny  i  wymaga aktualizacji Windows 7 Platform, może dlatego mam te problemy.

**Comment by blocker999** [comment]
Sprawdzałem na Waterfoxie i dalej jest ok, może to rzeczywiście kwestia systemu no ale niewie bo technicznie zabardzo nieznam.

Natomiast mój system to MOD Windowsa 10
Konkretnie to: https://winclub.pl/topic/11032-win-10-pro-1703-extreme-pw-x64-2k17/

**Comment by hawkeye116477** [comment]
Zresetowalem gfx font do domyślnych, akcelerację włączyłem, zrobiłem update Windows 7 Platform i czcionka teraz jest git, nie jest poszarpana ani rozmazana.

**Comment by gomoku** [comment]
@blocker999 możliwe, że to kwestia systemu, albo WF pod Win 10 czymś się różni od WF pod Win 7.
@hawkeye116477 ja te platform update mam zainstalowane, jak widać ty nie miałeś.

**Comment by hawkeye116477** [comment]
@blocker999 @blocker999 Macie mi za złe, że parę minut temu poprawiłem parę stron i header usadziłem na miejscu 😃 ? 
Oprócz tego jeszcze znalazłem parę stron, ale one są dość problematyczne, mimo, że je usadzam to pojawia się defekt taki, że menu przeskakuje, to pewnie dlatego, że wskakuje nowa klasa sticky i tu właśnie jest problem, iż nie wiem jak temu zapobiec, dlatego te problematyczne strony zostawiłem takie jak są na razie 😄 .

**Comment by blocker999** [comment]
@hawkeye116477 Niewybacze ci tego, nigdy, niewypłacisz się do końca życia, składam zawiadomienie do prokuratury !.

W uzasadnieniu powiem że działasz na działasz na szkode Popupblokera, w celu osiągnięcia korzyści majątkowej,

**Comment by hawkeye116477** [comment]
@blocker999 Heh 😃 .

**Comment by hawkeye116477** [comment]
@blocker999 Heh 😃 . 
Chodziło o to, że może jednak wolicie, by menu/header się ruszał, ale widać najwyraźniej jednak nie 😃

**Comment by hawkeye116477** [comment]
@blocker999 Heh 😃 . 
Myślałem, że może jednak wolicie, by menu/header się ruszał, ale widać najwyraźniej jednak nie 😃,

**Comment by blocker999** [comment]
@hawkeye116477 Dobra wybaczam ci ale zeby mi to było ostatni raz, w takim razie działaj dalej, bo z tego tak łatwo się niewywiniesz.
