### ISSUE TITLE
asport.pl

### ISSUE THREAD

**Issue by hawkeye116477** [azet12/PopupBlocker#91]
@All Chłopaki, hity tygodnia też chowamy czy zostawiamy 😃 ?
![screenshot_20170917_100016](https://user-images.githubusercontent.com/19818572/30519159-2d51e28a-9b8f-11e7-883a-947ef32a4fbc.png)

**Comment by blocker999** [comment]
@hawkeye116477 Jeżeli to hity tego sklepu to zostawiamy.

**Comment by blocker999** [comment]
@hawkeye116477 sorry inaczej button ten czerwony chowamy ale pasek z promocykamji zostawiamy no i newsletter i coś pod spodem do sociali i git.

**Comment by hawkeye116477** [comment]
@blocker999 Newsletter to jest static, więc raczej zostawiamy. A ten button czerwony to hity tego sklepu, więc na pewno mamy to schować?

**Comment by hawkeye116477** [comment]
@blocker999 Newsletter to jest static, więc raczej zostawiamy. A ten button czerwony to hit tygodnia tego sklepu i zdaje się, że w promocjach tego nie ma, także chyba jednak to zostawimy.

**Comment by blocker999** [comment]
@hawkeye116477 Ok ten newsletter narazie zostawiamy no ale ten czerwony button scrollujący usuwamy, niedość że mają pasek z promocyjkami to jeszcze zakładke " Strefa okazji " to oczojebny button musieli dać, ze skarpetkami które niezchodzą,, nie dzięki za ich nachalne buttony ze skarpetkami, to głównie poto jest ta paczka by to blokować .

**Comment by hawkeye116477** [comment]
@blocker999 Ok, faktycznie, masz rację, chowamy skarpetki 😄 .

**Comment by gomoku** [comment]
> @blocker999: ze skarpetkami które niezchodzą
> @hawkeye116477: chowamy skarpetki 😄

Sorry za off-topic chłopaki, ale ten tekst o skarpetkach to mistrzostwo świata,  mnie rozbawiliście do łez :smiley:
