### ISSUE TITLE
winiary.pl

### ISSUE THREAD

**Issue by hawkeye116477** [azet12/PopupBlocker#92]
`winiary.pl###kwit_brandwidget_btn`

**Comment by blocker999** [comment]
@hawkeye116477 po jakimś czasie wyskakuje popup

**Comment by hawkeye116477** [comment]
`winiary.pl###newsletter_popup`

**Comment by blocker999** [comment]
.winiary.pl##.mask

winiary.pl###newsletter_popup

**Comment by hawkeye116477** [comment]
@blocker999 Już to dodałem. a mask jest zbędne, wystarczy tylko `pl###newsletter_popup.`
