### ISSUE TITLE
bikecs.com

### ISSUE THREAD

**Issue by hawkeye116477** [azet12/PopupBlocker#93]
`bikecs.com##.bcs_site, .bcs_switch`

**Comment by blocker999** [comment]
Oczywiście że te boki usuwamy, poprostu w temacie #91 wprowadziłem Cie przez nieuwage w  błąd, ponieważ nie zauważyłem tego czerwonego maleństwa, no nieweszłem na strone tylko spojrzałem na screna i zasugerowałem się paskiem z promocyjkami za co jeszcze raz bardzo przepraszam.
