### ISSUE TITLE
inwestujwmyjnie.pl

### ISSUE THREAD

**Issue by hawkeye116477** [azet12/PopupBlocker#99]
`inwestujwmyjnie.pl###czater-contener`

**Comment by blocker999** [comment]
@hawkeye116477 A ten social, wiem co powiesz że to static ale ja powiem że mamy paczke antysocial wiec tam ich miejsce, to jak?

**Comment by hawkeye116477** [comment]
@blocker999 No co ty, to oczywiście, że blokujemy. Zaraz to dodam.
